### ISSUE TITLE
Running pythonnet on Windows Mono

### ISSUE THREAD

**Issue by nuukedo29** [pythonnet/pythonnet#1013]
### Environment
- Pythonnet master#5f56ebc8f0785f6581c10d5beb9c1a8fffe6c650
- Python 3.7
- Windows 7, Windows 10 18362.418
- Mono 6.6.0.161

### Details

I have a project that specifically requires Mono to run properly and i also need this program to run under windows.  From what i can see pythonnet's setup.py defaults `DEVTOOLS` to be `MsDev` when library is installed on windows. I have tried changing this constant to `Mono` but it ends up with an error which i dont know how to solve.

The error:
```
C:\Users\user\Desktop\pythonnet\pythonnet.sln (Build) ->
(Build target) ->
C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj (default targets) ->
C:\Program Files\Mono\lib\mono\xbuild\14.0\bin\Microsoft.CSHARP.Targets (CoreCompile target) ->

        CSC: error CS0041: Unexpected error writing debug information -- 'Operation is not supported on this platform.'
```

Full stack and steps:
```
C:\Users\user\Desktop\pythonnet>"C:\Program Files\Mono\\bin\setmonopath.bat"
Mono version 6.6.0.161
Prepending 'C:\Program Files\Mono\bin\' to PATH

C:\Users\user\Desktop\pythonnet>wget https://curl.haxx.se/ca/cacert.pem --no-check-certificate && cert-sync cacert.pem
C:\Users\user\Desktop\pythonnet>py -3.7 setup.py install
C:\tools\py37\lib\site-packages\setuptools\dist.py:475: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
  normalized_version,
running install
running build
running build_ext
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 5.3.1.
NuGet.exe is up to date.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files\Mono\lib\mono\xbuild\14.0\bin'.
WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
All packages listed in packages.config are already installed.

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 6.6.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 12/14/2019 10:35:08 AM.
__________________________________________________
Project "C:\Users\user\Desktop\pythonnet\pythonnet.sln" (Clean target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "ReleaseMono|x64".
        Target Clean:
                Project "C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj" (Clean target(s)):
                        Target CoreClean:
                                Deleting file 'G:\_sync\tarkovradar\pythonnet\src\runtime\obj\x64\ReleaseMono\.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                                Deleting file 'G:\_sync\tarkovradar\pythonnet\src\runtime\obj\x64\ReleaseMono\Python.Runtime.resources.clr.py'
                                Deleting file 'C:\Users\user\Desktop\pythonnet\src\runtime\obj\x64\ReleaseMono\.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                                Deleting file 'C:\Users\user\Desktop\pythonnet\src\runtime\obj\x64\ReleaseMono\Python.Runtime.csproj.FilesWrittenAbsolute.txt'
                Done building project "C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj".
                The project 'clrmodule' is disabled for solution configuration 'ReleaseMono|x64'.
Done building project "C:\Users\user\Desktop\pythonnet\pythonnet.sln".

Build succeeded.
         0 Warning(s)
         0 Error(s)

Time Elapsed 00:00:00.7755002

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

XBuild Engine Version 14.0
Mono, Version 6.6.0.0
Copyright (C) 2005-2013 Various Mono authors

Build started 12/14/2019 10:35:09 AM.
__________________________________________________
Project "C:\Users\user\Desktop\pythonnet\pythonnet.sln" (Build target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "ReleaseMono|x64".
        Target Build:
                Project "C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: ReleaseMono Platform: x64
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool C:\Program Files\Mono\bin\csc.bat execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj\x64\ReleaseMono\Python.Runtime.dll /resource:obj\x64\ReleaseMono\Python.Runtime.resources.clr.py,clr.py finalizer.cs Properties\AssemblyInfo.cs ..\SharedAssemblyInfo.cs arrayobject.cs assemblymanager.cs classderived.cs classbase.cs classmanager.cs classobject.cs clrobject.cs codegenerator.cs constructorbinder.cs constructorbinding.cs converter.cs CustomMarshaler.cs debughelper.cs delegatemanager.cs delegateobject.cs eventbinding.cs eventobject.cs exceptions.cs extensiontype.cs fieldobject.cs generictype.cs genericutil.cs importhook.cs indexer.cs interfaceobject.cs interfaces.cs interop.cs iterator.cs managedtype.cs metatype.cs methodbinder.cs methodbinding.cs methodobject.cs methodwrapper.cs modulefunctionobject.cs moduleobject.cs modulepropertyobject.cs nativecall.cs overload.cs propertyobject.cs pyansistring.cs pydict.cs pyfloat.cs pyint.cs pyiter.cs pylist.cs pylong.cs pynumber.cs pyobject.cs pyscope.cs pysequence.cs pystring.cs pythonengine.cs pythonexception.cs pytuple.cs runtime.cs typemanager.cs typemethod.cs Util.cs platform\Types.cs platform\LibraryLoader.cs interop37.cs obj\x64\ReleaseMono\.NETFramework,Version=v4.0.AssemblyAttribute.cs /target:library /unsafe+ /define:"PYTHON37;PYTHON3;UCS2" /nowarn:1591 /doc:bin\Python.Runtime.xml /langversion:7.3 /nostdlib /reference:"C:\Program Files\Mono\lib\mono\4.5\..\xbuild-frameworks\.NETFramework\v4.0\RedistList\..\..\..\..\4.0-api\System.dll" /reference:"C:\Program Files\Mono\lib\mono\4.5\..\xbuild-frameworks\.NETFramework\v4.0\RedistList\..\..\..\..\4.0-api\System.Core.dll" /reference:"C:\Program Files\Mono\lib\mono\4.0-api\\mscorlib.dll"
                                Microsoft (R) Visual C# Compiler version 3.4.0-beta4-19569-03 (82f2e254)
                                Copyright (C) Microsoft Corporation. All rights reserved.
finalizer.cs(67,45): warning CS0067: The event 'Finalizer.IncorrectRefCntResolver' is never used
CSC: error CS0041: Unexpected error writing debug information -- 'Operation is not supported on this platform.'
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj".-- FAILED
                Done building project "C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "C:\Users\user\Desktop\pythonnet\pythonnet.sln".-- FAILED
Done building project "C:\Users\user\Desktop\pythonnet\pythonnet.sln".-- FAILED

Build FAILED.

Warnings:

C:\Users\user\Desktop\pythonnet\pythonnet.sln (Build) ->
(Build target) ->
C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj (default targets) ->
C:\Program Files\Mono\lib\mono\xbuild\14.0\bin\Microsoft.CSHARP.Targets (CoreCompile target) ->

        finalizer.cs(67,45): warning CS0067: The event 'Finalizer.IncorrectRefCntResolver' is never used

Errors:

C:\Users\user\Desktop\pythonnet\pythonnet.sln (Build) ->
(Build target) ->
C:\Users\user\Desktop\pythonnet\src\runtime\Python.Runtime.csproj (default targets) ->
C:\Program Files\Mono\lib\mono\xbuild\14.0\bin\Microsoft.CSHARP.Targets (CoreCompile target) ->

        CSC: error CS0041: Unexpected error writing debug information -- 'Operation is not supported on this platform.'

         1 Warning(s)
         1 Error(s)

Time Elapsed 00:00:03.8039976
Traceback (most recent call last):
  File "setup.py", line 665, in <module>
    zip_safe=False,
  File "C:\tools\py37\lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "C:\tools\py37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\tools\py37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\tools\py37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 599, in run
    return install.install.run(self)
  File "C:\tools\py37\lib\distutils\command\install.py", line 545, in run
    self.run_command('build')
  File "C:\tools\py37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\tools\py37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\tools\py37\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\tools\py37\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\tools\py37\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\tools\py37\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\tools\py37\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\tools\py37\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 353, in build_extension
    subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
  File "C:\tools\py37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON37%3BPYTHON3%3BUCS2" /p:PythonBuildDir="C:\Users\user\Desktop\pythonnet\build\lib.win-amd64-3.7" /p:PythonInteropFile="interop37.cs" /p:PackageId=pythonnet_py37_x64 /verbosity:normal /t:Build' returned non-zero exit status 1.```

**Comment by filmor** [comment]
The build system changed quite significantly, this should not be an issue anymore (although we are not running tests for this, yet).
