### ISSUE TITLE
Unable to AddReference to Windows.Media

### ISSUE THREAD

**Issue by ripdog** [pythonnet/pythonnet#1024]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6.8
-   Operating System: Win10x64 18362.535

### Details

-   Describe what you were trying to get done.
Hello. I'm trying to use the SystemMediaTransportControls in Windows.Media. However, I can't get the assembly to import. Is this supposed to work?

I found the largest Windows.Media.dll on my system in System32, so I assume that's the correct one to use. However, dotPeek calls the dll 'unsupported', so does that mean the dll is not importable by pythonnet? Am I using the right tool? Thanks for the help.

I'm referencing https://docs.microsoft.com/en-us/uwp/api/Windows.Media.SystemMediaTransportControls
>Assemblies:
    Windows.Media.dll, Windows.dll 
-   What commands did you run to trigger this issue? 
```python
 sys.path.append(r'C:\Windows\System32')
WinMedia = clr.AddReference(r"C:\Windows\System32\Windows.Media.dll")
#also
#WinMedia = clr.AddReference(r"C:\Windows\System32\Windows.Media")
#and
#WinMedia = clr.AddReference("Windows.Media")
from Windows.Media import SystemMediaTransportControls
```

-   If there was a crash, please include the traceback here.

```python
  File "windowsIntegration.py", line 6, in <module>
    WinMedia = clr.AddReference("Windows.Media")
System.IO.FileNotFoundException: Unable to find assembly 'Windows.Media'.
   at Python.Runtime.CLRModule.AddReference(String name)
```

**Comment by saroad2** [comment]
Had the same problem.

**Comment by lostmsu** [comment]
Shallow googling did not show any supported way to load .winmd files at runtime with .NET variants :(

**Comment by lostmsu** [comment]
As a workaround you can try winmd reference to a custom build of Python.Runtime.

**Comment by Kenny2github** [comment]
I found that importing `System.Media` was at least not an error, but I have no idea what this is referencing; however I doubt it's correct:
```py
>>> import clr
>>> import System.Media
>>> System.Media.Core
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    System.Media.Core
AttributeError: Core
>>> System.Media.Playback
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    System.Media.Playback
AttributeError: Playback
>>> System.Media.SystemMediaTransportControls
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    System.Media.SystemMediaTransportControls
AttributeError: SystemMediaTransportControls
```

**Comment by lostmsu** [comment]
Another workaround is to create a library, that directly references winmd file, and have a public `Create` method, that instantiates the necessary class for you. Touching any class there might actually load the whole winmd and make it available to Python.NET (not tested, you need to see if that causes [`AppDomain.AssemblyLoad` event](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.assemblyload) to fire).

**Comment by ODtian** [comment]
Same problem, in my case it's windows.media.ocr

**Comment by elibroftw** [comment]
Any update? winrt hasn't been updated in some time. Should we just fork winrt?

**Comment by elibroftw** [comment]
winrt hasn't been updated since 2021.
