### ISSUE TITLE
System.DllNotFoundException when trying to import clr, despite referenced assembly existing

### ISSUE THREAD

**Issue by levihb** [pythonnet/pythonnet#1034]
### Environment

-   Pythonnet version: Tried latest from pip, latest from git
-   Python version: Tried 3.5, 3.7, 3.8
-   Operating System: Arch Linux

### Details

Trying to import clr so that I can import a library.

```python
import clr
```

When trying to import this, the following error is thrown:

```python
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: System.DllNotFoundException: /usr/lib/../lib/libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.GetNonCryptographicallySecureRandomBytes(byte*,int)
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <894a218ab05a4151a4fb84b414f81888>:0 
  at System.Guid.FastNewGuidArray () [0x00020] in <894a218ab05a4151a4fb84b414f81888>:0 
  at System.Reflection.Emit.ModuleBuilder..ctor (System.Reflection.Emit.AssemblyBuilder assb, System.String name, System.String fullyqname, System.Boolean emitSymbolInfo, System.Boolean transient) [0x00035] in <894a218ab05a4151a4fb84b414f81888>:0 
  at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (System.String name, System.String fileName, System.Boolean emitSymbolInfo, System.Boolean transient) [0x0005b] in <894a218ab05a4151a4fb84b414f81888>:0 
  at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (System.String name) [0x00000] in <894a218ab05a4151a4fb84b414f81888>:0 
  at Python.Runtime.CodeGenerator..ctor () [0x0002b] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.DelegateManager..ctor () [0x00061] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.PythonEngine.Initialize (System.Collections.Generic.IEnumerable`1[T] args, System.Boolean setSysArgv, System.Boolean initSigs) [0x0000a] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.PythonEngine.Initialize (System.Boolean setSysArgv, System.Boolean initSigs) [0x00005] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.PythonEngine.InitExt () [0x00000] in <1d25771ef5ab45e58a874c804663e59c>:0 
>>> 
```

I'm not sure what is going on, msbuild and mono work just fine, the referenced libmono-native library exists in the location specified (not sure why it drops back a directory, then goes back into lib though?).

**Comment by levihb** [comment]
After upgrading to Mono 6.11, I get the following, slightly different error:

```
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: System.TypeInitializationException: The type initializer for 'Sys' threw an exception. ---> System.DllNotFoundException: /lib/../lib/libmono-native.so assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Interop+Sys.LChflagsCanSetHiddenFlag()
  at Interop+Sys..cctor () [0x00000] in <c2db598b04474bb8b2ca952ec0b0ce8b>:0 
   --- End of inner exception stack trace ---
  at Interop.GetRandomBytes (System.Byte* buffer, System.Int32 length) [0x00000] in <c2db598b04474bb8b2ca952ec0b0ce8b>:0 
  at System.Guid.FastNewGuidArray () [0x00020] in <c2db598b04474bb8b2ca952ec0b0ce8b>:0 
  at System.Reflection.Emit.ModuleBuilder..ctor (System.Reflection.Emit.AssemblyBuilder assb, System.String name, System.String fullyqname, System.Boolean emitSymbolInfo, System.Boolean transient) [0x00035] in <c2db598b04474bb8b2ca952ec0b0ce8b>:0 
  at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (System.String name, System.String fileName, System.Boolean emitSymbolInfo, System.Boolean transient) [0x0005b] in <c2db598b04474bb8b2ca952ec0b0ce8b>:0 
  at System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule (System.String name) [0x00000] in <c2db598b04474bb8b2ca952ec0b0ce8b>:0 
  at Python.Runtime.CodeGenerator..ctor () [0x0002b] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.DelegateManager..ctor () [0x00061] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.PythonEngine.Initialize (System.Collections.Generic.IEnumerable`1[T] args, System.Boolean setSysArgv, System.Boolean initSigs) [0x0000a] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.PythonEngine.Initialize (System.Boolean setSysArgv, System.Boolean initSigs) [0x00005] in <1d25771ef5ab45e58a874c804663e59c>:0 
  at Python.Runtime.PythonEngine.InitExt () [0x00000] in <1d25771ef5ab45e58a874c804663e59c>:0 
```

**Comment by Zer0897** [comment]
I am experiencing an identical issue. Also on Arch Linux.

**Comment by lostmsu** [comment]
Judging by stack trace, this must be a Mono issue. You can try reproducing it by opening a REPL and running `System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule("__CodeGenerator_Module")`.

**Comment by Zer0897** [comment]
Compiled mono master branch directly and it seems to be fixed (mono v16.13.0)

**Comment by Zer0897** [comment]
There's a similar issue open over at mono https://github.com/mono/mono/issues/17079

So far everyone encountered the issue has been using Arch and Python.

**Comment by lostmsu** [comment]
@Zer0897 as a workaround you could try adding the true path to `libmonosgen-2.0.so.1` to `PATH`?

**Comment by Zer0897** [comment]
@lostmsu Yeah I was able to get that recognized by adding it to path, but `libmono-native.so` is still not found. I feel like this path is super fishy `/usr/local/lib/../lib/libmono-native.so`. If it's not expanding correctly then it may be the culprit.

**Comment by filmor** [comment]
I'm actually observing the same issue on my Gentoo system, looking into it. The path is fine, the actual issue (if you run with `MONO_LOG_LEVEL=debug`) seems to be that Mono fails to find the symbol `mono_add_internal_call_with_flags` while running (or loading) `libmononative.so`. However, that symbol is defined in `libmonosgen-2.0.so` which is already loaded, so the issue seems to be with Mono's P/Invoke implementation seems to get confused with libraries that require Mono's own symbols.

**Comment by b0g2** [comment]
I experienced a similar problem in Ubuntu 18.4, not via `import clr` but by loading the mono embedded runtime from a Python extension library written in C++ (I am not using PythonNet). There were a lot of exceptions similar to the ones mentioned here, including failing to find the symbol `mono_add_internal_call_with_flags`. 

For me, the solution was to *pre-load* `libmono-2.0.so` and `libstdc++.so` (important: this library contains the _ZTIPi symbol)
```
LD_PRELOAD="libmono-2.0.so libstdc++.so" python3 test/test.py
```
By doing this, the problem went away. It can also be done from code, via `dlopen`, prior to `import clr`.

**Comment by masutanissan** [comment]
Same issue on Amazon Linux in SageMaker : https://stackoverflow.com/questions/67212443/pythonnet-on-sagemaker-cannot-import-clr

**Comment by Masutani** [comment]
Same issue on Amazon Linux in SageMaker : https://stackoverflow.com/questions/67212443/pythonnet-on-sagemaker-cannot-import-clr

**Comment by lostmsu** [comment]
@Masutani there's a workaround for 2.4.0 mentioned above. Previews of 3.0.x do not have this issue anymore.
