### ISSUE TITLE
Call .NET async method from python

### ISSUE THREAD

**Issue by angelacalborean** [pythonnet/pythonnet#1039]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.7.4
-   Operating System: Windows 10

### Details

I have a .NET project and I want to call it from python.
I have loaded the dll in python and was able to call some methods from it but it failed when I wanted to call an async method.

`
import clr
import asyncio
from System import *

clr.AddReference('Test.Net.Upload.Client.dll')

from Test.Net.Upload.Client import *

async def main():  
    initialize_repositories()

    print('Create auth_params')
    auth_params = create_authentication_params()

    print('Create upload session:')
    upload_factory = UploadFactory()
    upload_factory = upload_factory.WithAuthenticationParameters(auth_params)
   
    #upload_session = upload_factory.BuildNewSession().Result   
    upload_session = upload_factory.BuildNewSession().Wait

asyncio.run(main())`

Now I get an error: it seems that my .net call gets called but is unable to execute it:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at System.Net.Http.WinHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Test.Net.Upload.Client.Infrastructure.HttpClientWrapper.<>c__DisplayClass9_0.<<SendRequest>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Policy.<>c__DisplayClass241_0`1.<<ExecuteAsyncInternal>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.RetrySyntaxAsync.<>c__DisplayClass21_1.<<WaitAndRetryAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Retry.RetryEngine.<ImplementationAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.Policy.<ExecuteAsyncInternal>d__241`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.Net.Upload.Client.Upload.UploadSession.<GetServerTime>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Test.Net.Upload.Client.Upload.UploadSession.<StartNewSession>d__35.MoveNext()

The above exception was the direct cause of the following exception:

Test.Net.Upload.Client.ApplicationException: Error on StartNewSession.
   at Test.Net.Upload.Client.Upload.UploadSession.<StartNewSession>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Test.Net.Upload.Client.Upload.UploadFactory.<BuildNewSession>d__60.MoveNext()

The above exception was the direct cause of the following exception:

System.AggregateException: One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()

Process finished with exit code 1

**Comment by sarkreth** [comment]
I don't think calling async methods is directly supported. I've just accepted this, since the concept of asynchronously completing Tasks appears at odds with the concept of a script.

The workaround I use is to add a non-async version of every method I want to be able to call from Python. It's straightforward with Task.Run:

```
using System.Threading.Tasks;

public async Task<int> MyAsyncMethod(int arg)
{
   ...
}

public int MySyncMethod(int arg)
{
   return Task.Run( async () => { return await MyAsyncMethod(arg); }).Result;
}
```

**Comment by MarouaneZhani** [comment]
@angelacalborean  Did you find any solution to this issue ? I'm having actually the same problem as you...

**Comment by AngelaCalboreanVisma** [comment]
> @angelacalborean Did you find any solution to this issue ? I'm having actually the same problem as you...

sorry, no.

**Comment by thatguyaknow** [comment]
I had a very similar issue to this and had to change on the library side how I was getting the path for an appsettings file to: 

`Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location) + \'\appsettings.json`

**Comment by blackcatpolice** [comment]
![image](https://github.com/pythonnet/pythonnet/assets/4312114/e0e4f9df-42a1-4258-8522-202d5e2fa95b)

You can use like this. C# Method is a async await method, python method get Task type result. You can get truely value from return.Result

**Comment by dbischof90** [comment]
A technical (not very performant but better than nothing) workaround is to have a threadpool in your python object and run it there. You'd spawn a python thread, let than wait and get the result back once it's done:

```python
async def my_wrapper():
    with concurrent.futures.ThreadPoolExecutor() as pool:
        result = await loop.run_in_executor(
            pool, blocking_pythonnet_func)
        print('Result is', result)

    return result
```

That threadpool can be "stored" somewhere, you can have it as a singleton and always spawn new threads to it if you make a call but that's arguably only worth it for the "bigger" functions.
