### ISSUE TITLE
Problem using pip to install pythonnet

### ISSUE THREAD

**Issue by ItaliannCheater** [pythonnet/pythonnet#1065]
### Environment

-   Pythonnet version: NOT INSTALLED (trying to install 2.4.0)
-   Python version: 3.8.0
-   Operating System: Windows 10

### Details

-   I'm trying to install pythonnet using pip because pywebview needs it. I already updated pip, wheel and setuptools but nothing changes.

    `pip install pythonnet`

-   This is what happens when I try to install it:

    C:\Users\Matteo\Desktop\pythonnet-2.4.0>pip install pythonnet
Collecting pythonnet
  Using cached pythonnet-2.4.0.tar.gz (1.8 MB)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\matteo\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Matteo\\AppData\\Local\\Temp\\pip-install-3pkbiyrd\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Matteo\\AppData\\Local\\Temp\\pip-install-3pkbiyrd\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Matteo\AppData\Local\Temp\pip-wheel-wznxsd38'
       cwd: C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\
  Complete output (85 lines):
  running bdist_wheel
  running build
  running build_ext
  Controllando aggiornamenti da https://www.nuget.org/api/v2/.
   NuGet.exe 4.1.0 avviato.
  Aggiornando NuGet.exe a 5.4.0.
  Aggiornamento riuscito
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '16.4.0.56107' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\packages'
  Adding package 'NUnit.3.7.1' to folder 'C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\packages'

  NuGet Config files used:
      C:\Users\Matteo\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      C:\Users\Matteo\.nuget\packages\
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "tools\geninterop\geninterop.py", line 293, in <module>
      sys.exit(main())
    File "tools\geninterop\geninterop.py", line 273, in main
      python_h = preprocess_python_headers()
    File "tools\geninterop\geninterop.py", line 193, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] Impossibile trovare il file specificato
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\setup.py", line 623, in <module>
      setup(
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\setup.py", line 298, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "c:\users\matteo\appdata\local\programs\python\python38-32\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\users\\matteo\\appdata\\local\\programs\\python\\python38-32\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\matteo\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Matteo\\AppData\\Local\\Temp\\pip-install-3pkbiyrd\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Matteo\\AppData\\Local\\Temp\\pip-install-3pkbiyrd\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Matteo\AppData\Local\Temp\pip-record-ndhl6qb6\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\matteo\appdata\local\programs\python\python38-32\Include\pythonnet'
         cwd: C:\Users\Matteo\AppData\Local\Temp\pip-install-3pkbiyrd\pythonnet\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\matteo\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Matteo\\AppData\\Local\\Temp\\pip-install-3pkbiyrd\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\Matteo\\AppData\\Local\\Temp\\pip-install-3pkbiyrd\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Matteo\AppData\Local\Temp\pip-record-ndhl6qb6\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\matteo\appdata\local\programs\python\python38-32\Include\pythonnet' Check the logs for full command output.

**Comment by jh-wu** [comment]
I have the same issue on Ubuntu 18.04.

I believe this is duplicated to #731, which is closed. But there is only a workaround (i.e. using --egg option) provided there. Since the option has gone in the latest pip,  that workaround doesn't work anymore.

**Comment by filmor** [comment]
Python 3.8 is not supported on Python.NET 2.4.0.
