### ISSUE TITLE
WIndows10 Ubuntu WSL installation fail

### ISSUE THREAD

**Issue by WilliamTian0987** [pythonnet/pythonnet#1081]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6.10
-   Operating System: Windows10 Ubuntu WSL

### Details

-   I was trying install pythonnet in my Windows10 Ubuntu WSL. I've already installed mono,clang,libglib2.0-dev and pycparser. But it always reports an same error:
`ERROR: Command errored out with exit status 1:
   command: '/mnt/d/SyncDrive/我的/ecommerce/env/bin/python' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0wlujat8/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0wlujat8/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3jbv3i7_
       cwd: /tmp/pip-install-0wlujat8/pythonnet/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.4.0.
  Update successful.
  Could not resolve type with token 01000249
  System.TypeLoadException: Could not resolve type with token 01000249
    at (wrapper managed-to-native) System.Reflection.MonoMethodInfo:get_method_info (intptr,System.Reflection.MonoMethodInfo&)
    at System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.GetPseudoCustomAttributes () [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) [0x0000d] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x0003b] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at Microsoft.Internal.AttributeServices.IsAttributeDefined[T] (System.Reflection.ICustomAttributeProvider attributeProvider, System.Boolean inherit) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsExport (System.Reflection.ICustomAttributeProvider attributeProvider) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo+<GetExportMembers>c__Iterator0.MoveNext () [0x001cd] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <63992662b765477a898ef49cdcc99ee2>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports () [0x0000c] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable () [0x0001d] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable (System.Type type, System.ComponentModel.Composition.Primitives.ICompositionElement origin) [0x0000a] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal () [0x00052] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex () [0x0000b] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0
  Could not resolve type with token 01000249
  System.TypeLoadException: Could not resolve type with token 01000249
    at (wrapper managed-to-native) System.Reflection.MonoMethodInfo:get_method_info (intptr,System.Reflection.MonoMethodInfo&)
    at System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.GetPseudoCustomAttributes () [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) [0x0000d] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x0003b] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at Microsoft.Internal.AttributeServices.IsAttributeDefined[T] (System.Reflection.ICustomAttributeProvider attributeProvider, System.Boolean inherit) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsExport (System.Reflection.ICustomAttributeProvider attributeProvider) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo+<GetExportMembers>c__Iterator0.MoveNext () [0x001cd] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <63992662b765477a898ef49cdcc99ee2>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports () [0x0000c] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable () [0x0001d] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable (System.Type type, System.ComponentModel.Composition.Primitives.ICompositionElement origin) [0x0000a] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal () [0x00052] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex () [0x0000b] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0
  Traceback (most recent call last):
    File "/tmp/pip-install-0wlujat8/pythonnet/setup.py", line 432, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/home/william/python3.610/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -MSBuildVersion 14 -o packages' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-0wlujat8/pythonnet/setup.py", line 658, in <module>
      zip_safe=False,
    File "/mnt/d/SyncDrive/我的/ecommerce/env/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/william/python3.610/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-0wlujat8/pythonnet/setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/mnt/d/SyncDrive/我的/ecommerce/env/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/william/python3.610/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/william/python3.610/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/william/python3.610/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/william/python3.610/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/william/python3.610/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/home/william/python3.610/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-0wlujat8/pythonnet/setup.py", line 245, in build_extension
      self._install_packages()
    File "/tmp/pip-install-0wlujat8/pythonnet/setup.py", line 437, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/home/william/python3.610/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -o packages' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet`

I was trying installed it offline, and I got:
`running install
running build
running build_ext
Could not resolve type with token 01000249
System.TypeLoadException: Could not resolve type with token 01000249
  at (wrapper managed-to-native) System.Reflection.MonoMethodInfo:get_method_info (intptr,System.Reflection.MonoMethodInfo&)
  at System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Reflection.MonoMethod.GetPseudoCustomAttributes () [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) [0x0000d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x0003b] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at Microsoft.Internal.AttributeServices.IsAttributeDefined[T] (System.Reflection.ICustomAttributeProvider attributeProvider, System.Boolean inherit) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsExport (System.Reflection.ICustomAttributeProvider attributeProvider) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo+<GetExportMembers>c__Iterator0.MoveNext () [0x001cd] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <63992662b765477a898ef49cdcc99ee2>:0 
  at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports () [0x0000c] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable () [0x0001d] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable (System.Type type, System.ComponentModel.Composition.Primitives.ICompositionElement origin) [0x0000a] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal () [0x00052] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex () [0x0000b] in <0007e672dd7f4959adc6f8103d9c843f>:0 
  at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0 
Traceback (most recent call last):
  File "/mnt/d/django安装包/pythonnet-2.4.0/setup.py", line 658, in <module>
    zip_safe=False,
  File "/mnt/d/SyncDrive/我的/ecommerce/env/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/william/python3.610/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/mnt/d/django安装包/pythonnet-2.4.0/setup.py", line 594, in run
    return install.install.run(self)
  File "/home/william/python3.610/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/home/william/python3.610/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/william/python3.610/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/william/python3.610/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/william/python3.610/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/william/python3.610/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/william/python3.610/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/william/python3.610/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/mnt/d/django安装包/pythonnet-2.4.0/setup.py", line 245, in build_extension
    self._install_packages()
  File "/mnt/d/django安装包/pythonnet-2.4.0/setup.py", line 424, in _install_packages
    subprocess.check_call(cmd, shell=use_shell)
  File "/home/william/python3.610/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.`

 don't know what else to try. Thanks.

**Comment by lostmsu** [comment]
You appear to be having problem with your NuGet installation. Check if this is relevant: https://www.area51.gr.jp/~rin/diary/?date=20200131

**Comment by WilliamTian0987** [comment]
Thank you for your approach. I changed my project path , but the error is still there

**Comment by WilliamTian0987** [comment]
> You appear to be having problem with your NuGet installation. Check if this is relevant: https://www.area51.gr.jp/~rin/diary/?date=20200131
> 
> Might be a locale-specific bug in NuGet. Try setting English or neutral locale before doing this. This might help: `LANG=en_US.utf8`

Thank you for your approach. I changed my project path , but the error is still there

**Comment by WilliamTian0987** [comment]
I tried reinstall mono and successful
