### ISSUE TITLE
installation error when setup.py prints help info and exits with exit code 1

### ISSUE THREAD

**Issue by Backup-eric645** [pythonnet/pythonnet#1091]
### Environment

-   Pythonnet version: INSTALLATION ERROR
-   Python version: Python - 3.8.1
-   Operating System: Microsoft Windows [Version 10.0.18362.719]

#### WHAT TO GET DONE

PIP (I think it's **P**ython **I**nstall **P**ackage) errors out on setup.py install.

The error is on [Cixon Uniax](https://cixon-556.github.io/uniax).

The Uniax stack code is `a:000000`.

#### COMMAND

```batch
PIP install pythonnet
```

#### TRACEBACK (subprocess.CalledProcessError)

```
1 warning generated.
  Traceback (most recent call last):
    File "tools\geninterop\geninterop.py", line 293, in <module>
      sys.exit(main())
    File "tools\geninterop\geninterop.py", line 275, in main
      ast = parser.parse(python_h)
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\pycparser\c_parser.py", line 143, in parse
      return self.cparser.parse(
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\pycparser\ply\yacc.py", line 265, in parse
      return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\pycparser\ply\yacc.py", line 1047, in parseopt_notrack
      tok = self.errorfunc(errtoken)
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\pycparser\c_parser.py", line 1677, in p_error
      self._parse_error(
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\pycparser\plyparser.py", line 55, in _parse_error
      raise ParseError("%s: %s" % (coord, msg))
  pycparser.plyparser.ParseError: C://Program Files (x86)//Windows Kits//10//include//10.0.18362.0//shared//basetsd.h:166:1: before: {
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\EricAS\AppData\Local\Temp\pip-install-ieg700ks\pythonnet\setup.py", line 623, in <module>
      setup(
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\EricAS\AppData\Local\Temp\pip-install-ieg700ks\pythonnet\setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\publicprog\38481952\python_3_8_1\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "c:\publicprog\38481952\python_3_8_1\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\EricAS\AppData\Local\Temp\pip-install-ieg700ks\pythonnet\setup.py", line 298, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "c:\publicprog\38481952\python_3_8_1\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\publicprog\\38481952\\python_3_8_1\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
```

**Comment by lostmsu** [comment]
@Backup-eric645 Python 3.8 is not yet supported.

**Comment by chenxijun** [comment]
> @Backup-eric645 Python 3.8 is not yet supported. Use Python 3.7 or 3.6.

Hope it will be supported soon. I'm trying to upgrade my program from python 3.7 to 3.8. :-)
