### ISSUE TITLE
Unhandled Exception: System.Reflection.TargetInvocationException (Attempted to read or write protected memory)

### ISSUE THREAD

**Issue by juavid** [pythonnet/pythonnet#1104]
### Environment

-   Pythonnet version: 2.4
-   Python version: 3.7.7 (64bit)
-   Operating System: Windows 10 64bit

### Details

-   Describe what you were trying to get done.

    I was connecting with a dotnet library that works fine if I call it from python 32 bit, but whenever I tried to call it from python 64 bit it works fine until I call a method that throws the exception below. The dll is compiled for Anycpu option so I am not sure what could i do to figure out how to solve this problem. As I mentioned the same code works fine with Python 32 bit. Any suggestions?

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

sys.path.append(r'C:\Program Files (x86)\Lib\bin\dotnet')
clr.AddReference("app.dotnet")

app = clr.Lib.tool.App()
print(app.get_VersionString())
sim = app.Sinit('input1.fen','case1.fen')

-   If there was a crash, please include the traceback here.
  ```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at tool.DllBindings.sinit(String inp_file, String cas_file, Int32& ierr)
   at Lib.tool.App.Sinit(String inpFile, String casFile)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Python.Runtime.MethodBinder.Invoke(IntPtr inst, IntPtr args, IntPtr kw, MethodBase info, MethodInfo[] methodinfo)
   at Python.Runtime.MethodObject.Invoke(IntPtr target, IntPtr args, IntPtr kw, MethodBase info)
   at Python.Runtime.MethodBinding.tp_call(IntPtr ob, IntPtr args, IntPtr kw)

```

**Comment by filmor** [comment]
Please try to reproduce this in pure C# first (compile an application as x32 and x64 and run it). The error looks like the .NET DLL you are using is a wrapper of a non-.NET DLL that crashes here. Reopen if things work in pure C# and provide the problematic DLL.
