### ISSUE TITLE
Using the Linux .NET Core Runtime instead of Mono

### ISSUE THREAD

**Issue by acarrau** [pythonnet/pythonnet#1157]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6.10
-   Operating System: Ubuntu 20.04

### Details

-   Tried running Python.Net using the .NET Core Runtime 3.1 instead of Mono on Linux.

In a 

-   Linux environment without any Mono installation.

```Docker
FROM python:3.6.10-stretch
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Install .NET Core
RUN dotnet_version=3.1.4 \
    && curl -SL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Runtime/$dotnet_version/dotnet-runtime-$dotnet_version-linux-x64.tar.gz \
    && dotnet_sha512='1869565558e5a85b6a898e792d7b5dece611b25f7f6fd8f015ffb16dccc7485f1412e04809da2e3f56744d24c75e1d3addbd2856c45ae7e66a2c7b71ea23e827' \
    && echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -ozxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install  --no-cache-dir -U setuptools wheel pycparser \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./test_components.py" ]

```

```python
import clr
clr.AddReference("my.Components")
from System import DateTime
from my.Component import HelloWorld

hello_world = HelloWorld()
```

-   Output from Docker console

```python
ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-33weh4lj/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-33weh4lj/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vikr8ffc
       cwd: /tmp/pip-install-33weh4lj/pythonnet/
  Complete output (43 lines):
  running bdist_wheel
  running build
  running build_ext
  /bin/sh: 1: mono: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-33weh4lj/pythonnet/setup.py", line 658, in <module>
      zip_safe=False,
    File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-33weh4lj/pythonnet/setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-33weh4lj/pythonnet/setup.py", line 245, in build_extension
      self._install_packages()
    File "/tmp/pip-install-33weh4lj/pythonnet/setup.py", line 424, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 127.
```

**Comment by filmor** [comment]
There are plenty of issues on this. Python.NET does not yet support .NET Core when embedding into Python.

**Comment by acarrau** [comment]
Thanks for clarifying.

**Comment by vyshkant** [comment]
@filmor is this still true for new versions of Python.NET?
