### ISSUE TITLE
Cannot install. Get Error: SecureChannelFailure (The authentication or decryption has failed.)

### ISSUE THREAD

**Issue by Dave-0-0** [pythonnet/pythonnet#1184]
### Environment

-   Pythonnet version: Latest
-   Python version: 3.6.3
-   Operating System: Ubuntu 18.04

### Details

-   Install pythonnet

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

python setup.py build_ext --inplace

-   If there was a crash, please include the traceback here.

running build_ext
Checking for updates from https://www.nuget.org/api/v2/.
Error: SecureChannelFailure (The authentication or decryption has failed.)
  The authentication or decryption has failed.
  Error while sending TLS Alert (Fatal:InternalError): System.IO.IOException: The authentication or decryption has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
    at System.Net.Sockets.Socket.EndReceive (System.IAsyncResult result) [0x00033] in <bd46d4d4f7964dfa9beea098499ab597>:0 
    at System.Net.Sockets.NetworkStream.EndRead (System.IAsyncResult asyncResult) [0x0005f] in <bd46d4d4f7964dfa9beea098499ab597>:0 
     --- End of inner exception stack trace ---
    at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (System.IAsyncResult asyncResult) [0x00040] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
    at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (System.IAsyncResult ar, System.Boolean ignoreEmpty) [0x00000] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
    at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (System.IAsyncResult result) [0x00071] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
     --- End of inner exception stack trace ---
    at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (System.IAsyncResult result) [0x0003b] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
    at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (System.IAsyncResult asyncResult) [0x0000c] in <1d0bb82c94e7435eb09324cf5ef20e36>:0 
  Unable to write data to the transport connection: The socket is not connected.
  The socket is not connected
Traceback (most recent call last):
  File "setup.py", line 659, in <module>
    zip_safe=False,
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 249, in build_extension
    self._install_packages()
  File "setup.py", line 438, in _install_packages
    subprocess.check_call(cmd, shell=use_shell)
  File "/home/davenagel/.pyenv/versions/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.

```python
    print('TODO')
```

**Comment by filmor** [comment]
This has nothing to do with Python.NET.

**Comment by Dave-0-0** [comment]
Can you give me some context? Is a dependency failing, or am I getting this confused with a different project?

**Comment by lostmsu** [comment]
@Dave-0-0 my guess would be that your machine is missing some root certificates in Mono certificate store.

**Comment by Dave-0-0** [comment]
@lostmsu Thank you. I think that was the problem. That error is no longer present after running "sudo apt-get install ca-certificates-mono"
