### ISSUE TITLE
Problem timeout error Updating NuGet.exe to 5.6.0. when execute "python setup.py bdist_wheel" in installation

### ISSUE THREAD

**Issue by dualxu** [pythonnet/pythonnet#1201]
### Environment

-   Pythonnet version:2.5.0
-   Python version: 3.7.0
-   Operating System: CentOS 7.8.2003（Core）

### Details

-   Describe what you were trying to get done.

timeout error Updating NuGet.exe to 5.6.0. when execute "python setup.py bdist_wheel" in installation

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

 python setup.py bdist_wheel  [After pip install git+https://github.com/pythonnet/pythonnet  and then  cd pythonnet   ]

-   If there was a crash, please include the traceback here.
[root@nodel pythonnet]# python setup.py bdist_wheel
/usr/local/lib/python3.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '3.0.0dev1' to '3.0.0.dev1'
  normalized_version,
running bdist_wheel
running build
running build_ext
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.1.0.
Updating NuGet.exe to 5.6.0.
The operation has timed out.
Traceback (most recent call last):
  File "setup.py", line 648, in <module>
    zip_safe=False,
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 603, in run
    return bdist_wheel.bdist_wheel.run(self)
  File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 247, in build_extension
    self._install_packages()
  File "setup.py", line 432, in _install_packages
    subprocess.check_call(cmd, shell=use_shell)
  File "/usr/local/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.

**Comment by lostmsu** [comment]
Try again. Most of the Microsoft services were down about the time when you reported this issue: https://news.ycombinator.com/item?id=24152655 😂

**Comment by filmor** [comment]
This doesn't apply anymore on master as we don't use the `nuget.exe` anymore.
