### ISSUE TITLE
Installation on macOS Mojave stymied by "pkg-config --libs mono-2"

### ISSUE THREAD

**Issue by clorton** [pythonnet/pythonnet#1204]
### Environment

-   Pythonnet version: 3.0.0dev1
-   Python version: 3.7.2
-   Operating System: macOS Mojave 10.14.6

### Details

-   Describe what you were trying to get done.

    Install pythonnet.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

    _Both of the following fail:_
```bash
    pip3 install pythonnet
    pip3 install git+https://github.com/pythonnet/pythonnet
```

-   If there was a crash, please include the traceback here.

    _Note: the first 4 lines are the output from pkg-config, the problem seems to bubble up from [setup.py _build_monoclr()](https://github.com/pythonnet/pythonnet/blob/master/setup.py#L393) when pkg-config fails and DEVTOOLS == "Mono"_

```text
  Package mono-2 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `mono-2.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'mono-2' found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/bt/15lsj66n1mnd9t5_ztjbqyg40000gn/T/pip-req-build-0sgsjo7y/setup.py", line 648, in <module>
      zip_safe=False,
    File "/Users/christopher/Coding/venvs/pycms/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/bt/15lsj66n1mnd9t5_ztjbqyg40000gn/T/pip-req-build-0sgsjo7y/setup.py", line 603, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/Users/christopher/Coding/venvs/pycms/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/bt/15lsj66n1mnd9t5_ztjbqyg40000gn/T/pip-req-build-0sgsjo7y/setup.py", line 370, in build_extension
      self._build_monoclr()
    File "/private/var/folders/bt/15lsj66n1mnd9t5_ztjbqyg40000gn/T/pip-req-build-0sgsjo7y/setup.py", line 388, in _build_monoclr
      mono_libs = _check_output("pkg-config --libs mono-2", shell=True)
    File "/private/var/folders/bt/15lsj66n1mnd9t5_ztjbqyg40000gn/T/pip-req-build-0sgsjo7y/setup.py", line 152, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command 'pkg-config --libs mono-2' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
```

**Comment by clorton** [comment]
Determined that `mono-2.pc` is on the system (from mono install), but not in a place `pkg-config` expects to find it. Adding the path to `mono-2.pc` via the `PKG_CONFIG_PATH` environment variable allowed for installation.

**Comment by christabella** [comment]
I also received the same error message, but following the environment variable setting instructions from https://github.com/pythonnet/pythonnet/issues/977#issuecomment-617463697 resolved it:

```
export PATH=$PATH:/Library/Frameworks/Mono.framework/Versions/Current/bin
export PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig
```

**Comment by filmor** [comment]
Current master doesn't require linking at build-time anymore, so this is "fixed".
