### ISSUE TITLE
Failed to use gensim. ImportError : cannot import name 'ssl' from 'urllib3.util.ssl_'

### ISSUE THREAD

**Issue by IvanAntipov** [pythonnet/pythonnet#1214]
### Environment

-   Pythonnet version:"Python.Runtime.NETStandard" Version="3.7.1" (it is different repository, but the same code base Python.Runtime and dotnetcore support)
-   Python version: python=3.7 (anaconda)
-   Operating System: Windows
-  .Net version: dotnet core Version = 3.1.3 (with F# 4.7)

### Details

-   Create python environment
```
conda create -n testenv python=3.7
conda activate testenv
pip install gensim
pip uninstall numpy  # in other case numpy is located in  c:\users\<username>\appdata\roaming\python\python37\site-packages and not found by Py.Import
pip install numpy  
```
-   Build repro project

from [PythonNetGensimIssue.zip](https://github.com/henon/pythonnet_netstandard/files/5150445/PythonNetGensimIssue.zip)

```
dotnet publish
```

-  Run repro script
```
dotnet fsi Experiment.fsx
```
 

StackTrace:
```stack
Python.Runtime.PythonException: ImportError : cannot import name 'ssl' from 'urllib3.util.ssl_' (c:/programdata/anaconda3/envs/testenv/Lib/site-packages\urllib3\util\ssl_.py)
['  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\gensim\\__init__.py", line 5, in <module>\n    from gensim import parsing, corpora, matutils, interfaces, models, similarities, summarization, utils  # noqa:F401\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\gensim\\parsing\\__init__.py", line 4, in <module>\n    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\gensim\\parsing\\preprocessing.py", line 42, in <module>\n    from gensim import utils\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\gensim\\utils.py", line 45, in <module>\n    from smart_open import open\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\smart_open\\__init__.py", line 33, in <module>\n    from .smart_open_lib import open, parse_uri, smart_open, register_compressor  # noqa: E402\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\smart_open\\smart_open_lib.py", line 28, in <module>\n    import boto3\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\boto3\\__init__.py", line 16, in <module>\n    from boto3.session import Session\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\boto3\\session.py", line 17, in <module>\n    import botocore.session\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\session.py", line 30, in <module>\n    import botocore.credentials\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\credentials.py", line 34, in <module>\n    from botocore.config import Config\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\config.py", line 16, in <module>\n    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\endpoint.py", line 22, in <module>\n    from botocore.awsrequest import create_request_object\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\awsrequest.py", line 25, in <module>\n    import botocore.utils\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\utils.py", line 32, in <module>\n    import botocore.httpsession\n', '  File "c:/programdata/anaconda3/envs/testenv/Lib/site-packages\\botocore\\httpsession.py", line 8, in <module>\n    from urllib3.util.ssl_ import (\n']   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Python.Runtime.Py.Import(String name)
   at <StartupCode$FSI_0009>.$FSI_0009.main@()
```
### Remarks
python ```import gensim``` works without problems

Original Issue was created in Python.Runtime.NETStandard repository (https://github.com/henon/pythonnet_netstandard/issues/12)

**Comment by lostmsu** [comment]
We only support installing Python.NET from pip: https://pypi.org/project/pythonnet/
If your problem reproduces with Python.NET installed that way, we can try to figure it out.

You might want to manually set `PythonHome`.
