### ISSUE TITLE
failing tests from PTVS GUI

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#122]
Test Name:  testImportModule
Test FullName:  test_engine.py::EngineTests::testImportModule
Test Source:    pythonnet\src\tests\test_engine.py : line 24

```
Python 2.7.9 |Continuum Analytics, Inc.| (default, Dec 12 2014, 14:56:54) [MSC v
.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import clr
>>> from Python.Runtime import PythonEngine
>>> m = PythonEngine.ImportModule("sys")

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has
been thrown by the target of an invocation. ---> System.AccessViolationException
: Attempted to read or write protected memory. This is often an indication that
other memory is corrupt.
   at Python.Runtime.Runtime.PyImport_ImportModule(String name)
   at Python.Runtime.PythonEngine.ImportModule(String name)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec
t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at Python.Runtime.MethodBinder.Invoke(IntPtr inst, IntPtr args, IntPtr kw, Me
thodBase info, MethodInfo[] methodinfo)
   at Python.Runtime.MethodObject.Invoke(IntPtr target, IntPtr args, IntPtr kw,
MethodBase info)
   at Python.Runtime.MethodBinding.tp_call(IntPtr ob, IntPtr args, IntPtr kw)
```

**Comment by denfromufa** [comment]
```
def testArrayContains(self): ##FAILING
        """Test array support for __contains__."""

        object = Test.Int32ArrayTest()
        items = object.items

        self.assertTrue(0 in items)
        self.assertTrue(1 in items)
        self.assertTrue(2 in items)
        self.assertTrue(3 in items)
        self.assertTrue(4 in items)

        self.assertFalse(5 in items)    # "H:\Python27\Lib\unittest\case.py", line 592, in deprecated_func,
        self.assertFalse(-1 in items)   #TypeError: int() argument must be a string or a number, not 'NoneType'
        self.assertFalse(None in items) # which threw ^ here which is a little odd.
        # But when run from runtests.py. Not when this module ran by itself.
```
```
Test Name:	testArrayContains
Test Outcome:	Failed
Result StandardOutput:	
Attempting to load Python.Runtime using standard binding rules... 
Attempting to load Python.Runtime from: 'C:\Python\Python27\lib\site-packages\Python.Runtime.dll'...
Result StandardError:	
Traceback (most recent call last):
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 69, in <module>
    main()
  File "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON TOOLS FOR VISUAL STUDIO\2.2\visualstudio_py_testlauncher.py", line 65, in main
    result = runner.run(test)
  File "C:\Python\Python27\lib\unittest\runner.py", line 151, in run
    test(result)
  File "C:\Python\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python\Python27\lib\unittest\suite.py", line 108, in run
    test(result)
  File "C:\Python\Python27\lib\unittest\suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "C:\Python\Python27\lib\unittest\suite.py", line 93, in run
    for test in self:
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by filmor** [comment]
Since there have not been any updates in quite a while, I'll close this issue. Feel free to reopen and provide a information on the current state.
