### ISSUE TITLE
.Net core 3.1 using netstandard polyfill causes error.

### ISSUE THREAD

**Issue by shadowbane1000** [pythonnet/pythonnet#1228]
### Environment

-   Pythonnet version: NuGet v 2.5.1  (pythonnet_netstandard_py37_linux)
-   Python version: 3.7
-   Operating System: Linux (ubuntu 18.04)

### Details

-   Trying to embed python in a c# core 3.1 console app.  Within python I wanted to attach a delegate to an event on a c# object.  The creation of the delegate type in DelegateManager.cs GetDispatcher calls TypeBuilder.CreateType.  In .net standard, this calls the polyfill.  Under core 3.1 a polyfill shouldn't be necessary.  However, this polyfill appears to be defined incorrectly.  It's defined as: 
```
public static Type CreateType(this TypeBuilder typeBuilder)
{
    return typeBuilder.GetTypeInfo().GetType();
}
```
However, the actual method in 3.1 is this:
```public Type CreateType() => (Type) this.CreateTypeInfo();```

The difference being that the extra GetType() results in us returning the equivalent of typeof(System.Reflection.Emit.TypeBuilder).  Which then fails to create with the arguments of a delegate.  

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

I don't have one offhand, but I will work on a pull reqeust unless someone has some advise for how to avoid the issue.  For a pull request, my plan is to #if the polyfill for !NETCOREAPP3_1

-   If there was a crash, please include the traceback here.

Not quite as useful as what I have above, but here is the traceback:
```
Unhandled exception. System.MissingMethodException: Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Python.Runtime.DelegateManager.GetDelegate(Type dtype, IntPtr callable)
   at Python.Runtime.EventObject.AddEventHandler(IntPtr target, IntPtr handler)
   at Python.Runtime.EventBinding.nb_inplace_add(IntPtr ob, IntPtr arg)
   at Python.Runtime.Runtime.PyRun_String(String code, IntPtr st, IntPtr globals, IntPtr locals)
   at Python.Runtime.PyScope.Exec(String code, IntPtr _globals, IntPtr _locals)
   at Python.Runtime.PyScope.Exec(String code, PyDict locals)
   at Oreo.Middleware.Calibration.Program.Main(String[] args) in /home/user/dev/Oreo/Oreo/src/Oreo.Middleware.Calibration/Program.cs:line 24
```
Note that I'm trying to create a delegate, and it's having a hard time finding the appropriate constructor on System.Reflection.Emit.TypeBuilder.

**Comment by shadowbane1000** [comment]
Looks like .net standard 2.1 defines CreateType(), so that would be the #if..    Are the _netstandard_ nuget packages 2.1?  I guess I could answer that question myself.

**Comment by filmor** [comment]
Thank you for the detailed report :)

1. The nuget packages are currently not provided by this project but by a fork
2. When we provide them, they will be for .NET Standard 2.0, 2.1 is not really an option because it's not compatible with .NET 4
3. It would be good if we could find a solution that detects this at runtime, we are trying to reach a state where a single build works on all supported .NET runtimes and Python versions

**Comment by shadowbane1000** [comment]
I see. Okay.  So what do you think the chances are that the polyfill is wrong in all cases?  When I use the .NET Standard 2.0 version of the library embedded in a .NET CoreApp 3.1  application, it fails as detailed above.  Is it possible that changing the polyfill to match the .NET Standard 2.1 method won't break anyone?  I guess we would need someone who has a verified use case of a .NET Standard 2.0 build that constructs delegates to verify if it works currently in any circumstances.  My guess is that it doesn't, but I don't know how widespread the use of the library is.

(Without some action being taken, there isn't much point to target .NET Standard at all since it won't be compatible with .NET Core 3.1 and presumably other versions of .NET Core)

**Comment by shadowbane1000** [comment]
I have verified that removing the polyfill and updating to 2.1 works in my use case.  But I didn't try just modifying the polyfill.  I could try that.

**Comment by lostmsu** [comment]
This should now be fixed in master.
