### ISSUE TITLE
Failed Assertion when Subclassing System.Exception in Python on .NET core

### ISSUE THREAD

**Issue by jmlidbetter** [pythonnet/pythonnet#1229]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.6.5
-   Operating System: Centos x64

### Details

-   Describe what you were trying to get done.

Subclassing System.Exception in python will cause a failed assertion when calling the constructor on the subclass in .NET core.

-   What commands did you run to trigger this issue?

```python
class Sub(System.Exception):
        pass
Sub()
```

-   If there was a crash, please include the traceback here.

```python
Process terminated. Assertion failed.
   at Python.Runtime.ManagedDataOffsets.BaseOffset(IntPtr type)
   at Python.Runtime.ManagedDataOffsets.DictOffset(IntPtr type)
   at Python.Runtime.ObjectOffset.TypeDictOffset(IntPtr type)
   at Python.Runtime.CLRObject..ctor(Object ob, IntPtr tp)
   at Python.Runtime.CLRObject.GetInstance(Object ob, IntPtr pyType)
   at Python.Runtime.CLRObject.GetInstHandle(Object ob, IntPtr pyType)
   at Python.Runtime.ClassObject.tp_new(IntPtr tp, IntPtr args, IntPtr kw)
   at Python.Runtime.NativeCall.Call_3(IntPtr fp, IntPtr a1, IntPtr a2, IntPtr a3)
   at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw)
Aborted (core dumped)
```

The problem comes from the `typeSize <= ExceptionOffset.Size()`  check [here](https://github.com/pythonnet/pythonnet/blob/master/src/runtime/interop.cs#L92) failing. When we have a subclass of `System.Exception` the `typeSize` is 88 but `ExceptionOffset.Size()` is 80.

I have found that removing the failing check allows all the tests to pass so I am wondering:

1. Why is that check there?
2. Is it safe to remove the check? (I assume not)
3. Perhaps someone knows why we might have an extra Int64 in the object

**Comment by jmlidbetter** [comment]
Duplicate

**Comment by lostmsu** [comment]
@jmlidbetter FYI you can skip the assertion by building a release configuration, or commenting it out. There's a bug associated with it, but you might be unaffected.

**Comment by jmlidbetter** [comment]
Yeah I have read the other issue. Think commenting out will be sufficient in our case.
