### ISSUE TITLE
pythonnet installation issues on python 3.6.8 for CentOS/RHEL

### ISSUE THREAD

**Issue by rsachdeva0106** [pythonnet/pythonnet#1232]
### Environment

-   Pythonnet version:
-   Python version: 3.6.8
-   Operating System: CentOS/RHEL

### Details

-   Describe what you were trying to get done.

    Trying to install pythonnet on python 3.6.8 which is on a linux RHEL server. Please can someone help with this error below while installing on LINUX. 
**subprocess.CalledProcessError: Command '['/bin/python3', 'tools/geninterop/geninterop.py', 'src/runtime/interop36m.cs']' returned non-zero exit status 1.**

-   What commands did you run to trigger this issue? If you can provide a
sudo yum -y install git
sudo pip3 install -U wheel --user
sudo pip3 install -U setuptools --user
sudo yum -y install glib
sudo yum -y install clang
sudo yum -y install mono-complete
Install nuget (this installs mono as well)

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

sudo python3  setup.py bdist_wheel
/root/.local/lib/python3.6/site-packages/setuptools/dist.py:452: UserWarning: Normalizing '3.0.0dev1' to '3.0.0.dev1'
  warnings.warn(tmpl.format(**locals()))
running bdist_wheel
running build
running build_ext
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.1.0.
Updating NuGet.exe to 5.7.0.
Update successful.
MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.

 

>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

 

MSBUILD: error MSBUILD0004: Too many project files specified

 

WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
Restoring NuGet package NUnit.3.12.0.
Adding package 'NUnit.ConsoleRunner.3.11.1' to folder '/home/ec2-user/pythonnet/packages'
Adding package 'NUnit.3.12.0' to folder '/home/ec2-user/pythonnet/packages'
Added package 'NUnit.ConsoleRunner.3.11.1' to folder '/home/ec2-user/pythonnet/packages'
Restoring NuGet package System.ValueTuple.4.5.0.
Adding package 'System.ValueTuple.4.5.0' to folder '/home/ec2-user/pythonnet/packages'
Added package 'System.ValueTuple.4.5.0' to folder '/home/ec2-user/pythonnet/packages'
Restoring NuGet package UnmanagedExports.1.2.7.
Adding package 'UnmanagedExports.1.2.7' to folder '/home/ec2-user/pythonnet/packages'
Added package 'UnmanagedExports.1.2.7' to folder '/home/ec2-user/pythonnet/packages'
Added package 'NUnit.3.12.0' to folder '/home/ec2-user/pythonnet/packages'

 

NuGet Config files used:
    /home/ec2-user/pythonnet/NuGet.config
    /root/.config/NuGet/NuGet.Config

 

Feeds used:
    /root/.nuget/packages/
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json

 

Installed:
    4 package(s) to packages.config projects
clang: error: no such file or directory: '/usr/include/python3.6m/Python.h'
clang: error: no input files
Traceback (most recent call last):
  File "tools/geninterop/geninterop.py", line 307, in <module>
    sys.exit(main())
  File "tools/geninterop/geninterop.py", line 287, in main
    python_h = preprocess_python_headers()
  File "tools/geninterop/geninterop.py", line 207, in preprocess_python_headers
    for line in _check_output(cmd).splitlines():
  File "tools/geninterop/geninterop.py", line 41, in _check_output
    output = subprocess.check_output(*args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['clang', '-pthread', '-I', 'tools/geninterop/fake_libc_include', '-I', '/usr/include/python3.6m', '-D', '__attribute__(x)=', '-D', '__inline__=inline', '-D', '__asm__=;#pragma asm', '-D', '__int64=long long', '-D', '_POSIX_THREADS', '-D', 'PYTHON_WITH_PYMALLOC', '-E', '/usr/include/python3.6m/Python.h']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "setup.py", line 647, in <module>
    zip_safe=False,
  File "/root/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 603, in run
    return bdist_wheel.bdist_wheel.run(self)
  File "/root/.local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 290, in run
    self.run_command('build')
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 296, in build_extension
    subprocess.check_call([sys.executable, geninterop, interop_file])
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
**subprocess.CalledProcessError: Command '['/bin/python3', 'tools/geninterop/geninterop.py', 'src/runtime/interop36m.cs']' returned non-zero exit status 1.**

**Comment by filmor** [comment]
This is not a support forum. On your system, the interop has to be created at build time, so we require the Python headers (usually the package is named something like `python3-dev`). The actual error is

    clang: error: no such file or directory: '/usr/include/python3.6m/Python.h'
