### ISSUE TITLE
unable to install with "pip install pythonnet" when whl file for version of python is not yet published to pypi.org

### ISSUE THREAD

**Issue by kasajian** [pythonnet/pythonnet#1280]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8 and 3.9 64-bit
-   Operating System: Windows 10 64-bit

### Details

-   When I install version 3.9 of Python (latest version as of this writing) and attempt to do `pip install pythonnet`, I get the error `option --single-version-externally-managed not recognized.`
    The reason this happens is because there's no wheel file published to pypi.org for Python 3.9, causing pip to attempt to install via the source.  Pip install will say `Collecting pythonnet. Using cached pythonnet-2.5.1.tar.gz (1.9 MB)` instead of something like `Collecting pythonnet. Downloading pythonnet-2.5.1-cp39-cp39-win32.whl`
    If you to go to https://pypi.org/project/pythonnet/#files you will see (as of this writing) that the last version of wheel file, pythonnet-2.5.1-cp38-cp38-win32.whl, is for Python 3.8.   **There is no pythonnet-2.5.1-cp39-cp39-win32.whl** because one has not been published for Python 3.9 (released more than a month ago)

The solution is to go back to Python 3.8 for which there *is* a wheel file.

Things tried that did not help:
-    Make sure Python is in the path
-    Select the "Disable path length limit" option in the install
-    Using cmd, powershell or the bash (the one that comes with git)
-    Downloading the .whl file for 3.8 and attempting to run that with 3.9

The fix would be to allow pip to install via the source when there's no wheel file published.

**Comment by kasajian** [comment]
Reference #731

**Comment by filmor** [comment]
If it's not published you can't install it. A new maintenance release is on the way.

**Comment by kasajian** [comment]
Once you publish it, it will work.
However, when it is not published, pip doesn't say "Cannot install because it does not exist / it is not published"
Pip will attempt to install it via the source .file.   Why do you publish the .source:
![image](https://user-images.githubusercontent.com/2384797/99181783-a276e800-26e5-11eb-8daa-42d36ca01ddf.png)

If you can never install via the source.  Might as well not publish it.

Or better yet, fix the problem so that Pythonnet can be installed from source, if that's possible.
If not, there should be a better error message.
At a minimum, there should be some note somewhere about it.  I didn't see any notes in this issue log, (see reference), nothing on stackoverflow, and nothing on the readme on the github site.

So for about a month, if someone installs Python and then attempts to do `pip install pythonnet` they will get an error that they cannot figure out..   They should at least get a better error message.

**Comment by filmor** [comment]
You can install from source just fine. Just read the actual logs, not just the top-most error. You are probably missing some build dependency. Work on the build system is ongoing, contributions are welcome, your demanding tone is not.

I'll have a closer look into the issue with the 64bit build you reported, maybe I messed something up during the release. No one else has reported this, though.

**Comment by kasajian** [comment]
Demanding tone?
I feel like I'm doing you a favor by spending the time figuring out the problem and reporting this to you.
This took a lot of my time and I did it to improve your product.
If it's not appreciated, I won't report anything in the future.

**Comment by 0xabu** [comment]
Just FWIW on the "no one else has reported this": I hit the same issue with `pip install pythonnet` failing with non-obvious build errors in Python 3.9 on Windows. This issue gave me the clue to try Python 3.8.

```
Collecting pythonnet
  Using cached pythonnet-2.5.1.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in c:\users\me\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pythonnet) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\me\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tjv7d6au\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tjv7d6au\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\me\AppData\Local\Temp\pip-wheel-y38r2z21'
       cwd: C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\
  Complete output (93 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.8.0.
  Update successful.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
  C:\Users\me\AppData\Local\Temp\NuGetScratch\t4bt0plz.bpl.nugetrestore.targets(455,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\src\runtime\Python.Runtime.csproj]
  C:\Users\me\AppData\Local\Temp\NuGetScratch\t4bt0plz.bpl.nugetrestore.targets(455,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\src\testing\Python.Test.csproj]
  C:\Users\me\AppData\Local\Temp\NuGetScratch\t4bt0plz.bpl.nugetrestore.targets(455,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\src\embed_tests\Python.EmbeddingTest.csproj]
  C:\Users\me\AppData\Local\Temp\NuGetScratch\t4bt0plz.bpl.nugetrestore.targets(455,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\src\console\Console.csproj]
  C:\Users\me\AppData\Local\Temp\NuGetScratch\t4bt0plz.bpl.nugetrestore.targets(455,20): error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\src\clrmodule\clrmodule.csproj]

  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package NUnit.3.12.0.
  Adding package 'NUnit.3.12.0' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'
  Added package 'NUnit.3.12.0' to folder 'C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\packages'

  NuGet Config files used:
      C:\Users\me\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\me\.nuget\packages\
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  Traceback (most recent call last):
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\tools\geninterop\geninterop.py", line 307, in <module>
      sys.exit(main())
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\tools\geninterop\geninterop.py", line 287, in main
      python_h = preprocess_python_headers()
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\tools\geninterop\geninterop.py", line 207, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\setup.py", line 630, in <module>
      setup(
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\setup.py", line 302, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop39.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\me\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tjv7d6au\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tjv7d6au\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\me\AppData\Local\Temp\pip-record-fkp8wedp\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\pythonnet'
         cwd: C:\Users\me\AppData\Local\Temp\pip-install-tjv7d6au\pythonnet\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\me\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tjv7d6au\\pythonnet\\setup.py'"'"'; __file__='"'"'C:\\Users\\me\\AppData\\Local\\Temp\\pip-install-tjv7d6au\\pythonnet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\me\AppData\Local\Temp\pip-record-fkp8wedp\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\me\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\pythonnet' Check the logs for full command output.
```
