### ISSUE TITLE
Adding DataRow to DataTable type mismatch

### ISSUE THREAD

**Issue by kasra-keshavarz** [pythonnet/pythonnet#1289]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
-   Operating System: Windows 10 64bit

### Details

-   I am simply making a DataTable and trying to add a 2-column row data into it.

```python
import clr

from System.Data import DataTable, DataColumn, DataRow
from System import DateTime, TimeSpan
import System

link = DataTable()

Date = DataColumn("Date")
Date.DataType = System.Type.GetType("System.DateTime")
HS0  = DataColumn("HS0")
HS0.DataType = System.Type.GetType("System.Double")

link.Columns.Add(Date)
link.Columns.Add(HS0)

start_date = DateTime(1998, 10, 10, 0, 0, 0)
one_week   = TimeSpan(7, 0, 0, 0)
now = start_date

for i in list(range(len([1,2,3,5]))):
    row = link.NewRow()
    row["Date"] = now # DateTime
    row["HS0"]  = System.Double((5) * 1e4)
    link.Rows.Add(row)
    now         = now.Add(one_week)
```

```python
---------------------------------------------------------------------------
InvalidCastException                      Traceback (most recent call last)
InvalidCastException: Unable to cast object of type 'System.Data.DataRow' to type 'System.IConvertible'.
   at System.Data.Common.DateTimeStorage.Set(Int32 record, Object value)
   at System.Data.DataColumn.set_Item(Int32 record, Object value)

The above exception was the direct cause of the following exception:

ArgumentException                         Traceback (most recent call last)
<ipython-input-6-82b4c2cb5553> in <module>
     19     row["Date"] = now # DateTime
     20     row["HS0"]  = System.Double((5) * 1e4) # data values should be in cms
---> 21     link.Rows.Add(row)
     22     now         = now.Add(one_week)

ArgumentException: Unable to cast object of type 'System.Data.DataRow' to type 'System.IConvertible'.Couldn't store <System.Data.DataRow> in Date Column.  Expected type is DateTime.
   at System.Data.DataColumn.set_Item(Int32 record, Object value)
   at System.Data.DataTable.NewRecordFromArray(Object[] value)
   at System.Data.DataRowCollection.Add(Object[] values)
```
What is the solution?

**Comment by filmor** [comment]
I can't reproduce this issue on Linux at least, will try on Windows as well.

**Comment by lostmsu** [comment]
Seems to work with 3.0.0-rc4
