### ISSUE TITLE
Failed to install pythonnet on a Raspberry Pi 4

### ISSUE THREAD

**Issue by lm-olano** [pythonnet/pythonnet#1290]
### Environment

-   Pythonnet version: Latest
-   Python version: 3.7
-   Operating System: Raspbian GNU/Linux 10

### Details

-   Describe what you were trying to get done.

    I was trying to install pythonnet in a fresh environment on a Raspberry Pi 4. This is my first issue, any help is appreciated. Thanks in advance.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

    _pipenv install pythonnet_

-   If there was a crash, please include the traceback here.

```
  ERROR: Command errored out with exit status 1:
   command: /home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vdhia1ra/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vdhia1ra/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-26wm3ai_
       cwd: /tmp/pip-install-vdhia1ra/pythonnet/
  Complete output (85 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.8.0.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.3.12.0.
  Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Adding package 'System.ValueTuple.4.5.0' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Adding package 'NUnit.3.12.0' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Added package 'System.ValueTuple.4.5.0' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'
  Added package 'NUnit.3.12.0' to folder '/tmp/pip-install-vdhia1ra/pythonnet/packages'

  NuGet Config files used:
      /home/pi/.config/NuGet/NuGet.Config

  Feeds used:
      /home/pi/.nuget/packages/
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  Traceback (most recent call last):
    File "tools/geninterop/geninterop.py", line 307, in <module>
      sys.exit(main())
    File "tools/geninterop/geninterop.py", line 287, in main
      python_h = preprocess_python_headers()
    File "tools/geninterop/geninterop.py", line 207, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "tools/geninterop/geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.7/subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'clang': 'clang'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-vdhia1ra/pythonnet/setup.py", line 659, in <module>
      zip_safe=False,
    File "/home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-vdhia1ra/pythonnet/setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-vdhia1ra/pythonnet/setup.py", line 302, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/bin/python', 'tools/geninterop/geninterop.py', 'src/runtime/interop37m.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
    ERROR: Command errored out with exit status 1:
     command: /home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vdhia1ra/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vdhia1ra/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4_japqu7/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/include/site/python3.7/pythonnet
         cwd: /tmp/pip-install-vdhia1ra/pythonnet/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vdhia1ra/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vdhia1ra/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4_japqu7/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/.local/share/virtualenvs/Recorder-z78jDcmO/include/site/python3.7/pythonnet Check the logs for full command output.
```

**Comment by filmor** [comment]
It tells you what the problem is (albeit somewhere in between):

      FileNotFoundError: [Errno 2] No such file or directory: 'clang': 'clang'
