### ISSUE TITLE
Cannot `import clr` from Python due to DllNotFoundException after setting paths

### ISSUE THREAD

**Issue by christabella** [pythonnet/pythonnet#1297]
### Environment

-   Pythonnet version: 3.0 (ongoing, latest master branch)
-   Python version: 3.7.9
-   Operating System: Windows 10, 64bit, WinPE

### Details

I've gone through https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX#common-errors and the issues listed there, https://github.com/pythonnet/pythonnet/issues/259 https://github.com/pythonnet/pythonnet/issues/463 https://github.com/pythonnet/pythonnet/issues/467

However, they are for embedding CPython within a .NET application whereas I would like to get the `import clr` statement working. Furthermore, I have installed CPython 3.8.6 and got its location with `import sys; sys.executable` and set that to PATH, PYTHONHOME, and PYTHONPATH environment variables.

![image](https://user-images.githubusercontent.com/2038751/100336974-b7e5ef00-2fce-11eb-9ee4-a6f33308ee61.png)

Also my VS configuration is:
![image](https://user-images.githubusercontent.com/2038751/100337705-a6511700-2fcf-11eb-8046-7263816b40a3.png)

However, 

```python
>>> import clr
Attempting to load 'Python.Runtime' using standard binding rules.
'Python.Runtime' not found using standard binding rules.
Attempting to load Python.Runtime from: 'C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\Python.Runtime.dll'.
Success loading 'Python.Runtime' from: 'C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\Python.Runtime.dll'.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DllNotFoundException: Unable to load DLL 'python3.8': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs, ShutdownMode mode)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.PyInit_clr()
```

**Comment by christabella** [comment]
Seems like this can be resolved by adding the `WINDOWS` flag to the conditional compilation symbols when building the Python.NET project in Visual Studio.

For posterity, the full instructions are ![image](https://user-images.githubusercontent.com/2038751/100354195-ab21c500-2fe7-11eb-93dc-457da1d4de41.png)
