### ISSUE TITLE
Trouble with pythonnet on docker/linux

### ISSUE THREAD

**Issue by PhilipEvans-Brightest** [pythonnet/pythonnet#1346]
### Environment

-   Pythonnet version: 3.0.0-dev1 & 2.5.1
-   Python version: 3.8
-   Operating System: Ubuntu 20.04
-   .NET Runtime: 5

### Details

-   Describe what you were trying to get done.

I am trying to run pythonnet via docker. The only requirements is executing a set of pytest tests from C# as well as possibly other python functions directly from C# code. 

-   What commands did you run to trigger this issue? If you can provide a

**Dockerfile:**
```docker
FROM mcr.microsoft.com/dotnet/sdk:5.0-focal-amd64 AS build

ENV DEBIAN_FRONTEND noninteractive

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3 python3-pip python3-dev python3-venv

RUN git clone https://github.com/pythonnet/pythonnet
WORKDIR /pythonnet
RUN python3 setup.py build_dotnet --inplace

RUN python3 -m pip install pytest

WORKDIR /source
COPY ./PyTestSelenium/ /pythonCode/

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet run 
```

**C# code**

```C#
PythonEngine.Initialize();
         
var pyLock = PythonEngine.AcquireLock();
PythonEngine.ImportModule("pytest");
PythonEngine.ReleaseLock(pyLock);
```

**.csproj**

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <PropertyGroup>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <!--<PackageReference Include="pythonnet_netstandard_py38_linux" Version="2.5.1" />-->

    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.3" />
    <PackageReference Include="Selenium.WebDriver" Version="3.141.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="87.0.4280.8800" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Python.Runtime">
      <HintPath>/pythonnet/pythonnet/runtime/Python.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

-   If there was a crash, please include the traceback here.

```python
#16 [12/12] RUN dotnet run
#16 sha256:a55eb81183e53ed9529fc7015660b655097ddfaed37913105f34459c0d54941e
#16 4.371 Unhandled exception. Python.Runtime.PythonException: ImportError : /usr/lib/python3.8/lib-dynload/_contextvars.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyContextVar_Type
#16 4.398 ['  File "/usr/local/lib/python3.8/dist-packages/pytest/__init__.py", line 42, in <module>\n    from _pytest.python_api import approx\n', '  File "/usr/local/lib/python3.8/dist-packages/_pytest/python_api.py", line 6, in <module>\n    from decimal import Decimal\n', '  File "/usr/lib/python3.8/decimal.py", line 8, in <module>\n    from _pydecimal import *\n', '  File "/usr/lib/python3.8/_pydecimal.py", line 440, in <module>\n    import contextvars\n', '  File "/usr/lib/python3.8/contextvars.py", line 1, in <module>\n    from _contextvars import Context, ContextVar, Token, copy_context\n']   at Python.Runtime.PythonException.ThrowIfIsNull(IntPtr ob) in /pythonnet/src/runtime/pythonexception.cs:line 261
#16 4.398    at Python.Runtime.PythonEngine.ImportModule(String name) in /pythonnet/src/runtime/pythonengine.cs:line 493
#16 4.398    at PythonNetIntegration.Program.Main(String[] args) in /source/PythonXunitTests.cs:line 119
#16 ERROR: executor failed running [/bin/sh -c dotnet run]: exit code: 134
```

**Comment by PhilipEvans-Brightest** [comment]
Additional info:

I also tried to install pythonnet via pip, this time in a python debian docker:

```dockerfile
FROM python:3.8-buster

RUN apt update \
    && apt install -y dirmngr gnupg apt-transport-https ca-certificates \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    && sh -c 'echo "deb https://download.mono-project.com/repo/debian stable-buster main" > /etc/apt/sources.list.d/mono-official-stable.list' \
    && apt update \
    && apt install -y mono-complete

RUN pip install pytest
RUN pip install pythonnet
```

which resulted in:

```python
#8 8.293   error: command 'dotnet' failed with exit status 1
#8 8.293   ----------------------------------------
#8 8.294   ERROR: Failed building wheel for pythonnet
#8 8.294 Failed to build pythonnet
#8 8.294 ERROR: Could not build wheels for pythonnet which use PEP 517 and cannot be installed directly
```

I got that result also if I tried /usr/bin/python3 -m pip install git+https://github.com/pythonnet/pythonnet --user (this time outside of docker and on Ubuntu 20.04)

**Comment by JG145** [comment]
Hey,

I am also running into issues getting this working:

Pythonnet version: 2.5.0
Python version: 3.7.7-buster
mono: 5.20

```
FROM python:3.7.7-buster

# Mono: 5.20

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
&& echo "deb http://download.mono-project.com/repo/debian stretch/snapshots/5.20 main" > /etc/apt/sources.list.d/mono-official.list \
&& apt-get update \
&& apt-get install -y clang \
&& apt-get install -y mono-devel=5.20\* \
&& rm -rf /var/lib/apt/lists/* /tmp/*


# Pythonnet: 2.5.0 (from PyPI)
# Note: pycparser must be installed before pythonnet can be built
RUN pip install pip --upgrade \
&& echo pip --version \
&& pip install setuptools --upgrade \
&& pip install wheel --upgrade \
&& pip install pycparser \
&& git clone https://github.com/pythonnet/pythonnet \
&& python pythonnet/setup.py bdist_wheel \
&& pip install --no-index --find-links=./pythonnet/dist/ pythonnet

```

Running into this error message:

`Cloning into 'pythonnet'...
Traceback (most recent call last):
  File "pythonnet/setup.py", line 196, in <module>
    with open("README.rst", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'`

**Comment by filmor** [comment]
@JG145 That's an entirely different case. The problem with your case is that you are running the `setup.py` from a different working directory. Not sure whether that is supported in general, but it's not supported in our `setup.py`, so you first need to `cd` into the `pythonnet` directory before running `python setup.py bdist_wheel`. Doing `pip install ./pythonnet` or even directly `pip install git+https://github.com/pythonnet/pythonn` should do the trick as well, you also should not need to install anything else anymore. Note, though, that `master` requires the `dotnet` SDK.

@PhilipEvans-Brightest Could you make the pip install more verbose? Would be interesting to know why `dotnet` failed.

**Comment by PhilipEvans-Brightest** [comment]
The last few lines of running: pip install --verbose git+https://github.com/pythonnet/pythonnet --user

```
#8 7.661 Building wheels for collected packages: pythonnet
#8 7.662   Created temporary directory: /tmp/pip-wheel-vbuob038
#8 7.662   Destination directory: /tmp/pip-wheel-vbuob038
#8 7.663   Building wheel for pythonnet (PEP 517): started
#8 7.663   Running command /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmph7sczizc
#8 7.852   running bdist_wheel
#8 7.852   running build
#8 7.852   running build_py
#8 7.864   creating build
#8 7.864   creating build/lib.linux-x86_64-3.8
#8 7.864   copying clr.py -> build/lib.linux-x86_64-3.8
#8 7.865   creating build/lib.linux-x86_64-3.8/pythonnet
#8 7.865   copying pythonnet/__init__.py -> build/lib.linux-x86_64-3.8/pythonnet
#8 7.865   running build_ext
#8 7.868   building 'pythonnet.mono.clr' extension
#8 7.868   creating build/temp.linux-x86_64-3.8
#8 7.868   creating build/temp.linux-x86_64-3.8/src
#8 7.869   creating build/temp.linux-x86_64-3.8/src/monoclr
#8 7.869   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.8 -c src/monoclr/clrmod.c -o build/temp.linux-x86_64-3.8/src/monoclr/clrmod.o -D_REENTRANT -I/usr/lib/pkgconfig/../../include/mono-2.0        
#8 7.952   creating build/lib.linux-x86_64-3.8/pythonnet/mono
#8 7.952   g++ -pthread -shared build/temp.linux-x86_64-3.8/src/monoclr/clrmod.o -L/usr/local/lib -o build/lib.linux-x86_64-3.8/pythonnet/mono/clr.cpython-38-x86_64-linux-gnu.so -L/usr/lib/pkgconfig/../../lib -lmono-2.0 -lm -lrt -ldl -lpthread
#8 8.007   running build_dotnet
#8 8.007   running configure
#8 8.007   Writing configured.props...
#8 8.010   Running dotnet build...
#8 8.010   dotnet build src/runtime/Python.Runtime.csproj --configuration release --output /tmp/pip-req-build-h8vn7b9x/build/lib.linux-x86_64-3.8/pythonnet/runtime
#8 8.012   error: command 'dotnet' failed with exit status 1
#8 8.033   Building wheel for pythonnet (PEP 517): finished with status 'error'
#8 8.033   ERROR: Failed building wheel for pythonnet
#8 8.034 Failed to build pythonnet
#8 8.034 ERROR: Could not build wheels for pythonnet which use PEP 517 and cannot be installed directly
#8 8.034 Exception information:
#8 8.034 Traceback (most recent call last):
#8 8.034   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
#8 8.034     status = self.run(options, args)
#8 8.034   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
#8 8.034     return func(self, options, args)
#8 8.034   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 361, in run
#8 8.034     raise InstallationError(
#8 8.034 pip._internal.exceptions.InstallationError: Could not build wheels for pythonnet which use PEP 517 and cannot be installed directly
#8 8.042 Removed build tracker: '/tmp/pip-req-tracker-gam8pwqv'
------
executor failed running [/bin/sh -c pip install --verbose git+https://github.com/pythonnet/pythonnet --user]: exit code: 1
```

**Comment by JG145** [comment]
Thanks! I am now hitting the same error as @PhilipEvans-Brightest with 
`
RUN pip install pip --upgrade \
&& pip install setuptools --upgrade \
&& pip install wheel --upgrade \
&& pip install pycparser \
&& git clone https://github.com/pythonnet/pythonnet \
&& pip install ./pythonnet
`

**Comment by kem1** [comment]
Hi. Is there any update in this issue. I am experiencing similar problem when installing pythonnet on Docker / Linux

```
21-May-2021 12:31:46 | Traceback (most recent call last):
-- | --
21-May-2021 12:31:46 | File "tools/geninterop/geninterop.py", line 396, in &lt;module&gt;
21-May-2021 12:31:46 | sys.exit(main())
21-May-2021 12:31:46 | File "tools/geninterop/geninterop.py", line 357, in main
21-May-2021 12:31:46 | python_h = preprocess_python_headers()
21-May-2021 12:31:46 | File "tools/geninterop/geninterop.py", line 238, in preprocess_python_headers
21-May-2021 12:31:46 | for line in _check_output(cmd).splitlines():
21-May-2021 12:31:46 | File "tools/geninterop/geninterop.py", line 46, in _check_output
21-May-2021 12:31:46 | output = subprocess.check_output(*args, **kwargs)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
21-May-2021 12:31:46 | **kwargs).stdout
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/subprocess.py", line 472, in run
21-May-2021 12:31:46 | with Popen(*popenargs, **kwargs) as process:
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
21-May-2021 12:31:46 | restore_signals, start_new_session)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
21-May-2021 12:31:46 | raise child_exception_type(errno_num, err_msg, err_filename)
21-May-2021 12:31:46 | FileNotFoundError: [Errno 2] No such file or directory: 'clang': 'clang'
21-May-2021 12:31:46 | Traceback (most recent call last):
21-May-2021 12:31:46 | File "&lt;string&gt;", line 1, in &lt;module&gt;
21-May-2021 12:31:46 | File "/tmp/pip-install-mzu1knlx/pythonnet/setup.py", line 659, in &lt;module&gt;
21-May-2021 12:31:46 | zip_safe=False,
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
21-May-2021 12:31:46 | return distutils.core.setup(**attrs)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
21-May-2021 12:31:46 | dist.run_commands()
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
21-May-2021 12:31:46 | self.run_command(cmd)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
21-May-2021 12:31:46 | cmd_obj.run()
21-May-2021 12:31:46 | File "/tmp/pip-install-mzu1knlx/pythonnet/setup.py", line 612, in run
21-May-2021 12:31:46 | return bdist_wheel.bdist_wheel.run(self)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
21-May-2021 12:31:46 | self.run_command('build')
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
21-May-2021 12:31:46 | self.distribution.run_command(command)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
21-May-2021 12:31:46 | cmd_obj.run()
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
21-May-2021 12:31:46 | self.run_command(cmd_name)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
21-May-2021 12:31:46 | self.distribution.run_command(command)
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
21-May-2021 12:31:46 | cmd_obj.run()
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
21-May-2021 12:31:46 | self.build_extensions()
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
21-May-2021 12:31:46 | self._build_extensions_serial()
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
21-May-2021 12:31:46 | self.build_extension(ext)
21-May-2021 12:31:46 | File "/tmp/pip-install-mzu1knlx/pythonnet/setup.py", line 302, in build_extension
21-May-2021 12:31:46 | subprocess.check_call([sys.executable, geninterop, interop_file])
21-May-2021 12:31:46 | File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
21-May-2021 12:31:46 | raise CalledProcessError(retcode, cmd)
21-May-2021 12:31:46 | subprocess.CalledProcessError: Command '['/usr/local/bin/python', 'tools/geninterop/geninterop.py', 'src/runtime/interop37m.cs']' returned non-zero exit status 1.
21-May-2021 12:31:46 | &nbsp;
21-May-2021 12:31:46 | ----------------------------------------
21-May-2021 12:31:46 | Failed building wheel for pythonnet
```

**Comment by filmor** [comment]
@kem1 This is not the same issue:
```
21-May-2021 12:31:46 | FileNotFoundError: [Errno 2] No such file or directory: 'clang': 'clang'
```

@everyone Please only comment if your issue with Docker is the exact same one that was reported initially. And please ensure that your build environment is properly set up.

**Comment by fractus** [comment]
This works - starting from python-3.9:slim though, not 3.8 as above, but I expect to make no difference.

.NET 5 should also work.

```docker
# .NET Core sources
RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb

# Mono and .NET
RUN apt update \
    && apt install -y apt-transport-https dirmngr gnupg \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
    && echo "deb https://download.mono-project.com/repo/debian stable-buster main" \
    | tee /etc/apt/sources.list.d/mono-official-stable.list \
    && apt update \
    && apt-get install -y clang mono-complete \
        dotnet-sdk-6.0 \
        libglib2.0 g++ \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# Install any Python requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
```

The `requirements.txt` should contain at least the following:
```
# Required for build
setuptools==58.0.4
pythonnet==2.5.2
```

See also those based on Anaconda - but almost double the size of the above;

https://hub.docker.com/r/fractus17/dotnet-pythonnet
