### ISSUE TITLE
option --single-version-externally-managed not recognized

### ISSUE THREAD

**Issue by jsotogaviard** [pythonnet/pythonnet#1352]
### Environment

python          3.9.1
boto3           1.16.51
botocore        1.19.53
jmespath        0.10.0
pip             20.3.3
pycparser       2.20
python-dateutil 2.8.1
s3transfer      0.3.4
sdist           0.0.0
setuptools      51.1.2
six             1.15.0
urllib3         1.26.2
wheel           0.36.2
windows         10
OS              64bits
processeur      x64
pythonnet       2.5.1
.NET Runtime: v4.0.30319

### Details

-   Describe what you were trying to get done.

Install pythonnet

-   What commands did you run to trigger this issue? 

pip install pythonnet

### Stacktrace

```python
Collecting pythonnet
  Using cached pythonnet-2.5.1.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in c:\work\code\thermometre\venv\lib\site-packages (from pythonnet) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\work\code\thermometre\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jsoto_adm\\AppData\\Local\\Temp\\pip-install-355cq43t\\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\\se
tup.py'"'"'; __file__='"'"'C:\\Users\\jsoto_adm\\AppData\\Local\\Temp\\pip-install-355cq43t\\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'
"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-wheel-gqsc5fu8'
       cwd: C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\
  Complete output (86 lines):
  running bdist_wheel
  running build
  running build_ext
  Recherche de mises … jour depuis https://www.nuget.org/api/v2/.
  NuGet.exe 4.1.0 en cours d'ex‚cution.
  Mise … jour de NuGet.exe vers 5.8.0.
  Mise … jour r‚ussie.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '16.200.19.32702' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
  Restoring NuGet package NUnit.3.12.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Adding package 'NUnit.3.12.0' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  Added package 'NUnit.3.12.0' to folder 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\packages'
  
  NuGet Config files used:
      C:\Users\jsoto_adm\AppData\Roaming\NuGet\NuGet.Config
  
  Feeds used:
      C:\Users\jsoto_adm\.nuget\packages\
      https://api.nuget.org/v3/index.json
  
  Installed:
      4 package(s) to packages.config projects
  Traceback (most recent call last):
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\tools\geninterop\geninterop.py", line 307, in <module>
      sys.exit(main())
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\tools\geninterop\geninterop.py", line 287, in main
      python_h = preprocess_python_headers()
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\tools\geninterop\geninterop.py", line 207, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "C:\work\lib\lib\subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\work\lib\lib\subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\work\lib\lib\subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\work\lib\lib\subprocess.py", line 1416, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\setup.py", line 630, in <module>
      setup(
    File "c:\work\code\thermometre\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\work\lib\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\work\lib\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\work\lib\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\work\code\thermometre\venv\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\work\lib\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\work\lib\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\work\lib\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\work\lib\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\work\lib\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\work\lib\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\work\lib\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\work\lib\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\setup.py", line 302, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "C:\work\lib\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\work\\code\\thermometre\\venv\\scripts\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop39.cs']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\work\code\thermometre\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jsoto_adm\\AppData\\Local\\Temp\\pip-install-355cq43t\\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\\
setup.py'"'"'; __file__='"'"'C:\\Users\\jsoto_adm\\AppData\\Local\\Temp\\pip-install-355cq43t\\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\
n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-record-p4ad83nn\install-record.txt' --single-version-externally-managed --compile --install-head
ers 'c:\work\code\thermometre\venv\include\site\python3.9\pythonnet'
         cwd: C:\Users\jsoto_adm\AppData\Local\Temp\pip-install-355cq43t\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\work\code\thermometre\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jsoto_adm\\AppData\\Local\\Temp\\pip-install-355cq43t\\pythonnet_e
be05c6c1a0a4ce68b90216ce0d2d122\\setup.py'"'"'; __file__='"'"'C:\\Users\\jsoto_adm\\AppData\\Local\\Temp\\pip-install-355cq43t\\pythonnet_ebe05c6c1a0a4ce68b90216ce0d2d122\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file_
_);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jsoto_adm\AppData\Local\Temp\pip-record-p4ad83nn\install-record.txt' --single-version-externally
-managed --compile --install-headers 'c:\work\code\thermometre\venv\include\site\python3.9\pythonnet' Check the logs for full command output.
```

**Comment by filmor** [comment]
This is not a support forum. You have a nice error in the middle of this one: "  FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable".
