### ISSUE TITLE
.NET 5 compatibility issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by Dave3991** [pythonnet/pythonnet#1353]
### Environment

-   Pythonnet version: pythonnet_py38_linux: 2.5.1.1
-   Python version: 3.8
-   Operating System: Ubuntu 20.04
-   .NET Runtime: 5

### Details

-   I try to run this code in Jetbrains Rider IDE.

```c#
namespace PythonExecutor
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            using (Py.GIL())
            {
            }
        }
    }
}
```

-   This is what I get

```c#
Unhandled exception. System.MissingMethodException: Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.
   at Python.Runtime.CodeGenerator..ctor()
   at Python.Runtime.DelegateManager..ctor()
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Python.Runtime.Py.GIL()
   at PythonExecutor.Program.Main(String[] args) in /home/david/Documents/personal/gitlab/inventory-management/InventoryManagement/app/PythonExecutor/Program.cs:line 11

Process finished with exit code 134.

```

**Comment by filmor** [comment]
This nuget package is not created by us, instead it's created from the fork https://github.com/henon/pythonnet_netstandard. The current master branch from here should work fine with .NET 5, 2.5 is untested in this regard.

@henon Please adjust the "Project Site" on nuget.org accordingly.
