### ISSUE TITLE
Linux unable to load libpython3.8m

### ISSUE THREAD

**Issue by NateKomodo** [pythonnet/pythonnet#1405]
### Environment

-   Pythonnet version: 2.5.1
-   Python version: 3.8
-   Operating System: Ubuntu 20.04.2
-   .NET Runtime: 5.0

### Details

-   Describe what you were trying to get done.

I am using Keras.NET which makes use of pythonnet 2.5.1. An exception is thrown when running `PythonEngine.Initialize()` in my C# application

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

`PythonEngine.Initialize()`

-   If there was a crash, please include the traceback here.

```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'python3.8m' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython3.8m: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
```
I have libpython3.8.so in /usr/lib/x86_64-linux-gnu and have set LD_LIBRARY_PATH to reflect that, however there is no difference with this variable unset.

**Comment by NateKomodo** [comment]
Just made a symlink from libpython3.8m.so -> libpython3.8.so.1.0 and it seems to be working now?
