### ISSUE TITLE
.Net 5.0 not loaded successfully (according to issue 984)

### ISSUE THREAD

**Issue by ingted** [pythonnet/pythonnet#1423]
### Environment

-   Pythonnet version: master (3.0.0 dev?)
-   Python version: 3.8.7
-   Operating System: windows server 2019
-   .NET Runtime: .net 5.0.4

### Details

```
import os
import sys
from clr_loader import get_coreclr
from pythonnet import set_runtime

runtime_config = os.path.join(r"Z:\SharFTrade\pythonnettest\pythonnettest\bin\Release\net5.0", "pythonnettest.runtimeconfig.json")
rt = get_coreclr(runtime_config)
set_runtime(rt)

import clr
import System
System.Environment.Version.ToString()
```

The result is still
'4.0.30319.42000'

However it should be 
5.0.4

**Comment by ingted** [comment]
Content of pythonnettest.runtimeconfig.json:

```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "5.0.0"
    }
  }
}
```

**Comment by filmor** [comment]
And you are absolutely certain that you don't have an older `clr.pyd` from a previous installation flying around? Please test this in a completely fresh environment.

**Comment by ingted** [comment]
Hi @filmor ,
Thank you for this hint.
However after I delete old clr.pyd,
Another issue appear:
```
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import os
>>> import sys
>>> from clr_loader import get_coreclr
>>> from pythonnet import set_runtime
>>>
>>> runtime_config = os.path.join(r"Z:\SharFTrade\pythonnettest\pythonnettest\bin\Release\net5.0", "pythonnettest.runtimeconfig.json")
>>> rt = get_coreclr(runtime_config)
>>> set_runtime(rt)
>>>
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\pythonnet-3.0.0.dev1-py3.8.egg\clr.py", line 6, in <module>
    load()
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\pythonnet\__init__.py", line 54, in load
    func = _LOADER_ASSEMBLY["Python.Runtime.Loader.Initialize"]
  File "Z:\SharFTrade\clr-loader\clr_loader\wrappers.py", line 38, in __getitem__
    return self.get_function(name)
  File "Z:\SharFTrade\clr-loader\clr_loader\wrappers.py", line 35, in get_function
    return ClrFunction(self._runtime, self._path, name, func)
  File "Z:\SharFTrade\clr-loader\clr_loader\wrappers.py", line 16, in __init__
    self._callable = runtime.get_callable(assembly, typename, func_name)
  File "Z:\SharFTrade\clr-loader\clr_loader\hostfxr.py", line 79, in get_callable
    check_result(res)
  File "Z:\SharFTrade\clr-loader\clr_loader\util\__init__.py", line 26, in check_result
    raise error
clr_loader.util.clr_error.ClrError: 0x80131509: COR_E_INVALIDOPERATION => An operation is not legal in the current state.
>>> quit()
PS Z:\SharFTrade\clr-loader>
```
Even I clone clr-loader and python.exe .\setup.py install_lib doesn't work.

PS. python.exe .\setup.py install would result error:
```
PS Z:\SharFTrade\clr-loader> python.exe .\setup.py install
running install
running bdist_egg
running egg_info
writing clr_loader.egg-info\PKG-INFO
writing dependency_links to clr_loader.egg-info\dependency_links.txt
writing requirements to clr_loader.egg-info\requires.txt
writing top-level names to clr_loader.egg-info\top_level.txt
reading manifest file 'clr_loader.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'clr_loader.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
C:\Program Files\dotnet\dotnet.exe build netfx_loader/ClrLoader.csproj --runtime win-x64 --output clr_loader/ffi/dlls/amd64 --configuration release
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ClrLoader -> Z:\SharFTrade\clr-loader\clr_loader\ffi\dlls\amd64\ClrLoader.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.97
C:\Program Files\dotnet\dotnet.exe build netfx_loader/ClrLoader.csproj --runtime win-x86 --output clr_loader/ffi/dlls/x86 --configuration release
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ClrLoader -> Z:\SharFTrade\clr-loader\clr_loader\ffi\dlls\x86\ClrLoader.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.00
Traceback (most recent call last):
  File ".\setup.py", line 56, in <module>
    setup(
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 177, in run
    all_outputs, ext_outputs = self.get_ext_outputs()
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 351, in get_ext_outputs
    for ext in build_cmd.extensions:
  File "C:\Users\anibal\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: extensions
PS Z:\SharFTrade\clr-loader>
```

**Comment by ingted** [comment]
I removed manually copied pythonnet folder, everything are fine now. Thank you!!! @filmor
