### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Evangelink** [pythonnet/pythonnet#1453]
### Environment

-   Pythonnet version: 2.5.1.1
-   Python version: 3.7.3
-   Operating System: Windows 10
-   .NET Runtime: .NET 4.8

### Details

First of all, I am not sure this is specifically linked to Python.Net or if that's more of a machine configuration problem. All sources with a similar problem points to a MAC OS issue with Python being installed on the machine which is a different scenario/problem than mine.

I have installed my Wix bundle installer on a fresh Windows 10 VM. The installer contains both my .net 4.8 application and the python directory (`python-3.7.3-embed-amd64`) with all the required dependencies. Everything is installed in the `Program Files\CompanyName\ProductName` folder, and on my application startup I update the `Path` environment variable to add the path to the python directory, then call `PythonEngine.Initialize()` and finally run my python code.

Application logs:

```
Python.Runtime.PythonException: URLError : <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
```

**Comment by filmor** [comment]
This is not a support forum and this issue is indeed unrelated to Python.NET. You might want to set `PYTHON_HOME` additionally to adding things to `PATH`.

**Comment by Evangelink** [comment]
@filmor Thanks and sorry about the ticket! I am pretty new to python and pythonnet so I wasn't sure where was the boundary. Regarding `PYTHON_HOME`, is the idea to prevent conflict if some python is already installed? Shall I also set the `PythonEngine.PythonHome` property?

**Comment by lostmsu** [comment]
@Evangelink

I faced a similar problem on my product with portable conda environment and the fix for me was adding this code (you will certainly have to modify it for your needs):

```csharp
        static readonly string[] CondaEnvWinBinaryPaths = {
            "",
            @"Library\mingw-w64\bin",
            @"Library\usr\bin",
            @"Library\bin",
            @"Scripts",
            @"bin",
        };
        static void ActivateCondaWindowsEnvironment(PythonEnvironment environment) {
            ActivateCondaEnvCommon(environment);

            if (environment.Home is null) return;

            var newPath = new System.Text.StringBuilder();
            foreach(string prefix in CondaEnvWinBinaryPaths) {
                newPath.Append(Path.Combine(environment.Home.FullName, prefix));
                newPath.Append(';');
            }
            newPath.Append(Environment.GetEnvironmentVariable("PATH"));
            Environment.SetEnvironmentVariable("PATH", newPath.ToString());
        }
```

**Comment by Evangelink** [comment]
Thanks @lostmsu! So far I haven't fixed the issue but I have realized that I had some missing configuration on my call to easyocr anyways (I don't want to allow the web request).
