### ISSUE TITLE
Ubuntu installation: System.TypeLoadException: Could not resolve type with token 01000196

### ISSUE THREAD

**Issue by rbngz** [pythonnet/pythonnet#1475]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.6.9
-   Operating System: Ubuntu 18.04/Docker
-   .NET Runtime:

### Details

I am facing an issue when trying to install pythonnet 2.5.2 on Ubuntu 18.04.
In my Dockerfile I do install the following packages:

```
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    git \
    clang \
    libglib2.0-dev \
    mono-complete \
    python3-dev 
```
I then install `pycparser` with `pip install pycparser`
When calling `pip install pythonnet` afterwards, I get the following error:
```
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from pythonnet) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-l_jo6qjh
       cwd: /tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/
  Complete output (91 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.9.1.
  Update successful.
  Could not resolve type with token 01000196
  System.TypeLoadException: Could not resolve type with token 01000196
    at (wrapper managed-to-native) System.Reflection.MonoMethodInfo:get_method_info (intptr,System.Reflection.MonoMethodInfo&)
    at System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.GetPseudoCustomAttributes () [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) [0x0000d] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x0003b] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at Microsoft.Internal.AttributeServices.IsAttributeDefined[T] (System.Reflection.ICustomAttributeProvider attributeProvider, System.Boolean inherit) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsExport (System.Reflection.ICustomAttributeProvider attributeProvider) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo+<GetExportMembers>c__Iterator0.MoveNext () [0x001cd] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <63992662b765477a898ef49cdcc99ee2>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports () [0x0000c] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable () [0x0001d] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable (System.Type type, System.ComponentModel.Composition.Primitives.ICompositionElement origin) [0x0000a] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal () [0x00052] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex () [0x0000b] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0
  Could not resolve type with token 01000196
  System.TypeLoadException: Could not resolve type with token 01000196
    at (wrapper managed-to-native) System.Reflection.MonoMethodInfo:get_method_info (intptr,System.Reflection.MonoMethodInfo&)
    at System.Reflection.MonoMethodInfo.GetMethodInfo (System.IntPtr handle) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.GetPseudoCustomAttributes () [0x00002] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.GetPseudoCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType) [0x0000d] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.MonoCustomAttrs.IsDefined (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x0003b] in <8f2c484307284b51944a1a13a14c0266>:0
    at System.Reflection.MonoMethod.IsDefined (System.Type attributeType, System.Boolean inherit) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0
    at Microsoft.Internal.AttributeServices.IsAttributeDefined[T] (System.Reflection.ICustomAttributeProvider attributeProvider, System.Boolean inherit) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsExport (System.Reflection.ICustomAttributeProvider attributeProvider) [0x00000] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo+<GetExportMembers>c__Iterator0.MoveNext () [0x001cd] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <63992662b765477a898ef49cdcc99ee2>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.HasExports () [0x0000c] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.IsPartDiscoverable () [0x0001d] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.AttributedModel.AttributedModelDiscovery.CreatePartDefinitionIfDiscoverable (System.Type type, System.ComponentModel.Composition.Primitives.ICompositionElement origin) [0x0000a] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.get_PartsInternal () [0x00052] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex () [0x0000b] in <0007e672dd7f4959adc6f8103d9c843f>:0
    at System.Lazy`1[T].CreateValue () [0x00075] in <8f2c484307284b51944a1a13a14c0266>:0
  Traceback (most recent call last):
    File "/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py", line 446, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -MSBuildVersion 14 -o packages' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py", line 659, in <module>
      zip_safe=False,
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py", line 249, in build_extension
      self._install_packages()
    File "/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py", line 451, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -o packages' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xrz4wxsf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pythonnet
         cwd: /tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3xh59sg4/pythonnet_51cf6e1969e04f0ea8a08bfe25d55460/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xrz4wxsf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/pythonnet Check the logs for full command output.
```

This is the output from `mono --version`:
```
Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

Thanks!

**Comment by rbngz** [comment]
Solved the issue just now!

I needed to upgrade to the newest mono version which I could get by adding the following code to my Dockerfile:
```
RUN apt install -y curl
RUN apt install gnupg ca-certificates
RUN curl https://download.mono-project.com/repo/xamarin.gpg | apt-key add -
RUN echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt update
```
The [original installation steps from mono](https://www.mono-project.com/download/stable/#download-lin-ubuntu) did not work for me because I was not able to retrieve the public key due to [this issue ](https://github.com/mono/mono/issues/9891)

Retrieving the key with `curl https://download.mono-project.com/repo/xamarin.gpg | apt-key add -` did solve the mono installation issue and I was able to successfully install pythonnet.

mono version 6.12.0.122.
