### ISSUE TITLE
pythonnet fails when upgrade to framework 4.6.1

### ISSUE THREAD

**Issue by ahmadshobake** [pythonnet/pythonnet#1479]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.7.6
-   Operating System: windows 10
-   .NET Runtime:

### Details

-   try get Get Authenticated Context for sharepoint using attached ClaimAuth.dll after upgrading to 4.6.1 framework 

    _TODO_

import clr
full_filename = r'C:\Users\Desktop\test\ClaimAuth.dll'
clr.AddReference(full_filename)
from ClaimAuth import ClaimClientContext
_contextURL="https://petrofaconline.sharepoint.com/sites/oec/ES00013"
context = ClaimClientContext.GetAuthenticatedContext(_contextURL)

error as below:

System.ApplicationException: The requested site does not appear to have claims enabled or the Login Url has not been set.
   at ClaimAuth.ClaimsWebAuth.Show()
   at ClaimAuth.ClaimClientContext.GetAuthenticatedCookies(String targetSiteUrl, Int32 popUpWidth, Int32 popUpHeight)
   at ClaimAuth.ClaimClientContext.GetAuthenticatedContext(String targetSiteUrl, Int32 popUpWidth, Int32 popUpHeight)
   at ClaimAuth.ClaimClientContext.GetAuthenticatedContext(String targetSiteUrl)

[dll_files.zip](https://github.com/pythonnet/pythonnet/files/6722176/dll_files.zip)

**Comment by filmor** [comment]
This is not a support forum.
