### ISSUE TITLE
Could not load  "\<path>\python36.dll", using pythonnet under ASP.net Web API call on IIS

### ISSUE THREAD

**Issue by teckdj** [pythonnet/pythonnet#1491]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.6
-   Operating System: VM , windows server 2019
-   .NET Runtime: Dotnet core 3.1
-    IIS:10

### Details
 The type initializer for 'Delegates' threw an exception: Could not load  "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python36\\python36.dll"

-   Describe what you were trying to get done.

-  I am trying to call python function by importing a my custom python package, using python runtime (pythonnet) 
-  I can successfully call the function if I am running it through a dotnet console application 
-  I am getting error, couldn't load <path>python36.dll.  when I call the function by hosting it though a web API.
-  I have manually build and deployed Python.Runtime.
-  I have set all the required environment variable.  python36.dll does exist in the location. 
-  However API call is successful if it is executed on the local environment under IIS Express (ASP.Net) running though VS 2019

if I refer the to the older Python.Runtime dll the one that gets installed using ( pip install Pythonet)  i get error - Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'

Exception 
 at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized() in ..\\runtime.cs:line 2597
 at Python.Runtime.Runtime.Py_IsInitialized() in ..\\runtime.cs:line 803
 at Python.Runtime.Runtime.Initialize(Boolean initSigs, ShutdownMode mode) in ..\\runtime.cs:line 116
 at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs, ShutdownMode mode) in ..\\runtime\\pythonengine.cs:line 189
 at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs, ShutdownMode mode) in ..\\pythonengine.cs:line 164
 at Python.Runtime.PythonEngine.Initialize() in ..\\pythonengine.cs:line 159\
 at Python.Runtime.Py.GIL() in ..\\pythonengine.cs:line 644

Inner Exception 
Message:The type initializer for 'Delegates' threw an exception.Inner excpetion:Could not load ..\\python36.dll
 at Python.Runtime.Platform.WindowsLoader.Load(String dllToLoad) in ..\\LibraryLoader.cs:line 115
 at Python.Runtime.Runtime.Delegates.GetUnmanagedDll(String libraryName) in ..\\runtime.cs:line 2574
 at Python.Runtime.Runtime.Delegates..cctor() in ..\\runtime.cs:line 2289"

**Comment by SoftwareDudeNo1** [comment]
Hi teckdj, i have the same problem with python.net and IIS as you have. I use python37, but this is no issue. I guess the problem is a combination of IIS permissions and user permissions to the python installation folder. Do you found a solution?

**Comment by teckdj** [comment]
No luck. your are correct with respect to the IIS permission,  if you run the Application pool with a custom account identity like administrator it works for few call after that it hangs and no response then you restart the App pool it works.

**Comment by funcelot** [comment]
IIS is usuall a havity threaded, moreover, IIS tries to keep wheels rolling, so it does not shutdowns thread in HTTP pipline worked with HTTP request, it keeping it in memory for some time, so this particular dll is owned by another thread, and also worth to mention that normally, using GIL it would probably setup a lock for a threads to run on global shared object, so, in short, this is expected behavior. Better use other tools like IronPython cause they CLR based and share the same aparment model and can coordinate with IIS properly

**Comment by filmor** [comment]
`Py.GIL` doesn't perform initialization anymore (must now be called once explicitly, guarded with a lock in your case). This should remove this particular race condition.
