### ISSUE TITLE
Failed to install on Raspberry Pi

### ISSUE THREAD

**Issue by TehseenHasan** [pythonnet/pythonnet#1555]
### Environment

-   Pythonnet version (trying to install): latest
-   Python version: 3.7.3
-   Operating System: Raspbian OS 10 (buster)
-   Mono version: 5.18.0.240

**`dotnet --info` results this:**

.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [/home/pi/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/home/pi/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/home/pi/dotnet/shared/Microsoft.NETCore.App]

### Details

- I am trying to install Pythonnet on my Raspberry Pi 4. 

**`pip3 install pythonnet` giving this error:**

```
pi@raspberrypi:~ $ pip3 install pythonnet
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in ./.local/lib/python3.7/site-packages (from pythonnet) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k7734blv
       cwd: /tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/
  Complete output (71 lines):
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.11.0.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  MSBUILD: error MSBUILD0004: Too many project files specified
  
  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Index was outside the bounds of the array.
  MSBuild auto-detection: using msbuild version '' from '/usr/bin'.
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  MSBUILD: error MSBUILD0004: Too many project files specified
  
  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Index was outside the bounds of the array.
  Traceback (most recent call last):
    File "/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py", line 446, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -MSBuildVersion 14 -o packages' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py", line 659, in <module>
      zip_safe=False,
    File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/local/lib/python3.7/dist-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py", line 249, in build_extension
      self._install_packages()
    File "/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py", line 451, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -o packages' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9tmzy_vu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/pythonnet
         cwd: /tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a552bmbk/pythonnet_f519fbb9483543159c30b64933462b63/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9tmzy_vu/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.7m/pythonnet Check the logs for full command output.
```

**Comment by filmor** [comment]
There is already an open issue for this.

**Comment by TehseenHasan** [comment]
> There is already an open issue for this.

any solution?
