### ISSUE TITLE
How to enable reflection permission in pythonnet

### ISSUE THREAD

**Issue by mlzxy** [pythonnet/pythonnet#1571]
### Environment

-   Pythonnet version: 3.0.0.dev1
-   Python version: 3.7
-   Operating System: Win10
-   .NET Runtime: 5.0

### Details

 I am trying to use Newtonsoft.Json to encode some csharp objects. 

```python
from clr_loader import get_coreclr
from pythonnet import set_runtime
rt = get_coreclr("./config.json")
# content in config.json
# {
#   "runtimeOptions": {
#     "tfm": "net5.0",
#     "framework": {
#       "name": "Microsoft.NETCore.App",
#       "version": "5.0.0"
#     }
#   }
# }
set_runtime(rt)
import os
import sys
sys.path.append(r"C:\Users" + f"\{os.environ['CURRENT_USER_NAME'].strip()}" + r"\.nuget\packages\newtonsoft.json\13.0.1\lib\net45")
sys.path.append(r"C:\Users" + f"\{os.environ['CURRENT_USER_NAME'].strip()}" + r"\.nuget\packages\system.security.permissions\4.5.0\lib\net461")
import clr
clr.AddReference("Newtonsoft.Json")
clr.AddReference("System.Security.Permissions")
from Newtonsoft.Json import JsonConvert
JsonConvert.SerializeObject(1)
```

I expect this will run fine, but I get an error like this. 

```python
TypeLoadException: Could not load type 'System.Security.Permissions.ReflectionPermission' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration()
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreatePrimitiveContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContract(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
```

It seems come from https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonTypeReflector.cs#L453, where Newtonsoft.Json actually tries to prob whether dynamic code generation is authorized in the runtime. Apparently, this permission is not granted in the default setting for pythonnet. I think the `config.json` may be the place shall be changed, but I am not sure how. Do you have any ideas how to enable the reflection permission? 

Thanks in advance for your time!

**Comment by filmor** [comment]
You are trying to load .NET Framework DLLs into a .NET Core VM, which will (usually) not work.

Don't write the `config.json` yourself but instead create a small "bundling" project that `PackageReference`s the dependencies you are interested in and `dotnet publish` it. That way, the correct DLLs and their dependencies will be selected, along with correct `.deps.json` files.

**Comment by niander** [comment]
@filmor Would pythonnet "clr.AddReference" use ".deps.json"?
