### ISSUE TITLE
Python.Runtime.dll not setup.py install-ed

### ISSUE THREAD

**Issue by jdcole** [pythonnet/pythonnet#1608]
### Environment

-   Pythonnet version: 3.0.0.dev1
-   Python version: 3.9.7
-   Operating System: OSX 11.6
-   .NET Runtime: net standard 2.0

### Details

-   Describe what you were trying to get done.

Install pythonnet from source.

-   What commands did you run to trigger this issue? If you can provide a

The runtime is built but not copied over with `python setup.py install`. Everything seems fine when manually placing it.

```bash
python3 -m venv clr.venv
source clr.venv/bin/activate
pip install --upgrade pip
pip install wheel
git clone -b master --depth 1 https://github.com/pythonnet/pythonnet
cd pythonnet
python setup.py install
python -c 'import clr'
```

-   If there was a crash, please include the traceback here.

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/pythonnet/clr.py", line 6, in <module>
    load()
  File "/private/tmp/pythonnet/pythonnet/__init__.py", line 42, in load
    func = _LOADER_ASSEMBLY["Python.Runtime.Loader.Initialize"]
  File "/private/tmp/clr.venv/lib/python3.9/site-packages/clr_loader-0.1.6-py3.9.egg/clr_loader/wrappers.py", line 38, in __getitem__
    return self.get_function(name)
  File "/private/tmp/clr.venv/lib/python3.9/site-packages/clr_loader-0.1.6-py3.9.egg/clr_loader/wrappers.py", line 35, in get_function
    return ClrFunction(self._runtime, self._path, name, func)
  File "/private/tmp/clr.venv/lib/python3.9/site-packages/clr_loader-0.1.6-py3.9.egg/clr_loader/wrappers.py", line 16, in __init__
    self._callable = runtime.get_callable(assembly, typename, func_name)
  File "/private/tmp/clr.venv/lib/python3.9/site-packages/clr_loader-0.1.6-py3.9.egg/clr_loader/mono.py", line 42, in get_callable
    _check_result(assembly, f"Unable to load assembly {assembly_path}")
  File "/private/tmp/clr.venv/lib/python3.9/site-packages/clr_loader-0.1.6-py3.9.egg/clr_loader/mono.py", line 132, in _check_result
    raise RuntimeError(msg)
RuntimeError: Unable to load assembly /private/tmp/pythonnet/pythonnet/runtime/Python.Runtime.dll
```

**Comment by jdcole** [comment]
As of `58df35bdeb61ed3d39846346e15a6ddf6594b279`
wiki does suggest `pip install -e .` or `python setup.py develop`.
