### ISSUE TITLE
Python calling .NET fails when run from the Downloads directory

### ISSUE THREAD

**Issue by DareDevilDenis** [pythonnet/pythonnet#1707]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.9.7 64 bit
-   Operating System: Windows 10
-   .NET Runtime: Microsoft.NETCore.App 5.0.14

### Details

-   I have a Python script that loads a couple of .NET assemblies. If the Python script and the .NET assemblies directory live in the Windows Downloads folder then it fails with the following exception:

```
C:\Users\daredevildenis\Downloads>py my_python.py
Traceback (most recent call last):
  File "C:\Users\daredevildenis\Downloads\my_python.py", line 14, in <module>
    clr.AddReference("NetworkSimulatorRemoteControllerCommon")
System.IO.FileLoadException: Could not load file or assembly 'NetworkSimulatorRemoteControllerCommon, Version=10.51.1.0, Culture=neutral, PublicKeyToken=3c4875e2ebbfc055'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Python.Runtime.CLRModule.AddReference(String name) in /home/benedikt/git/pythonnet/src/runtime/moduleobject.cs:line 484
```

If the files are placed in **any other directory** then it works fine.

#### To reproduce:
- Unzip [does_not_work_from_Downloads.zip](https://github.com/pythonnet/pythonnet/files/8154703/does_not_work_from_Downloads.zip) to the Downloads directory (so that 'my_python.py and directory 'MyDotnetApp' are in Downloads).
- Run my_python.py

**Comment by DareDevilDenis** [comment]
Ok, I figured it out. This was my fault.

The problem was that in Downloads directory I had a a DLL with the same name name as the assembly that the Python script was calling 'clr.AddReference' for.

So to avoid this type of problem, rather than having:

```python
sys.path.append(r"C:\MyApp\out_path")
clr.FindAssembly("MyAssembly")
clr.AddReference("MyAssembly")
```

I think it's safer to have:

```python
clr.FindAssembly("C:\MyApp\out_path\MyAssembly")
clr.AddReference("C:\MyApp\out_path\MyAssembly")

```
