### ISSUE TITLE
Unable to import crl with python 3.10/ 3.9

### ISSUE THREAD

**Issue by joybwang** [pythonnet/pythonnet#1730]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.10/3.9
-   Operating System: Windows Server 2016

### Details

Failed to `import clr` on python 3.10 and python 3.9

```sh
# python 3.10 32bit

>py -3.10-32 -m pip show pythonnet
Name: pythonnet
Version: 3.0.0a2
Summary: .Net and Mono integration for Python
Home-page: https://pythonnet.github.io/
Author: The Contributors of the Python.NET Project
Author-email: pythonnet@python.org
License: MIT
Location: c:\python3\3.10-32\lib\site-packages
Requires: clr-loader
Required-by:

>py -3.10-32
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 13:59:55) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\3.10-32\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Python3\3.10-32\lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "C:\Python3\3.10-32\lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

```sh
# python 3.10 64bit

>py -3.10 -m pip show pythonnet
Name: pythonnet
Version: 3.0.0a2
Summary: .Net and Mono integration for Python
Home-page: https://pythonnet.github.io/
Author: The Contributors of the Python.NET Project
Author-email: pythonnet@python.org
License: MIT
Location: c:\python3\3.10\lib\site-packages
Requires: clr-loader
Required-by:

>py -3.10
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\3.10\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Python3\3.10\lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "C:\Python3\3.10\lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

```sh
# python 3.9 32bit

>py -3.9-32 -m pip show pythonnet
Name: pythonnet
Version: 3.0.0a2
Summary: .Net and Mono integration for Python
Home-page: https://pythonnet.github.io/
Author: The Contributors of the Python.NET Project
Author-email: pythonnet@python.org
License: MIT
Location: c:\python3\3.9-32\lib\site-packages
Requires: clr-loader
Required-by:

>py -3.9-32
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:01:48) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\3.9-32\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Python3\3.9-32\lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "C:\Python3\3.9-32\lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

```sh
# python 3.9 64bit

>py -3.9 -m pip show pythonnet
Name: pythonnet
Version: 3.0.0a2
Summary: .Net and Mono integration for Python
Home-page: https://pythonnet.github.io/
Author: The Contributors of the Python.NET Project
Author-email: pythonnet@python.org
License: MIT
Location: c:\python3\3.9\lib\site-packages
Requires: clr-loader
Required-by:

>py -3.9
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3\3.9\lib\site-packages\clr.py", line 6, in <module>
    load()
  File "C:\Python3\3.9\lib\site-packages\pythonnet\__init__.py", line 43, in load
    if func(''.encode("utf8")) != 0:
  File "C:\Python3\3.9\lib\site-packages\clr_loader\wrappers.py", line 20, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'
```

**Comment by Yuangang0101** [comment]
i have the same issue, still try to find the way to address this issue.
`  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\clr_loader\types.py", line 64, in __call__
    return self._callable(ffi.cast("void*", buf_arr), len(buf_arr))
RuntimeError: cannot call null pointer pointer from cdata 'int(*)(void *, int)'`

**Comment by joybwang** [comment]
@Yuangang0101 Install at least .NET framework 4.7.2 and give it a try.

**Comment by joybwang** [comment]
Closing along with https://github.com/pythonnet/pythonnet/issues/1731

**Comment by joybwang** [comment]
> Loading a Runtime
> All runtimes supported by clr-loader can be used, which are
> 
> Mono (mono)
> Default on Linux and macOS, supported on all platforms.
> 
> .NET Framework (netfx)
> Default on Windows and also only supported there. Must be at least version 4.7.2.
> 
> .NET Core (coreclr)
> Self-contained is not supported, must be at least version 3.1.

https://pythonnet.github.io/pythonnet/python.html
