### ISSUE TITLE
System.TypeLoadException caught when import clr with 32 bit python 3.10/3.9 installed on 32 bit machine

### ISSUE THREAD

**Issue by joybwang** [pythonnet/pythonnet#1731]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.10/3.9
-   Operating System: Windows 10 x86

### Details

Failed to `import clr` on python 3.10 and python 3.9

```sh
# python 3.10 32bit

>>py -3.10-32 -m pip show pythonnet
Name: pythonnet
Version: 3.0.0a1
Summary: .Net and Mono integration for Python
Home-page: https://pythonnet.github.io/
Author: The Contributors of the Python.NET Project
Author-email: pythonnet@python.org
License: MIT
Location: c:\python3\3.10\lib\site-packages
Requires: clr-loader
Required-by:

>py -3.10-32
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 13:59:55) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr

Unhandled Exception: System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at ClrLoader.DomainData..ctor(AppDomain domain)
   at ClrLoader.ClrLoader.Initialize()
```

```sh
# python 3.9 32bit

>py -3.9 -m pip show pythonnet
Name: pythonnet
Version: 3.0.0a1
Summary: .Net and Mono integration for Python
Home-page: https://pythonnet.github.io/
Author: The Contributors of the Python.NET Project
Author-email: pythonnet@python.org
License: MIT
Location: c:\python3\3.9\lib\site-packages
Requires: clr-loader
Required-by:

>py -3.9
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:01:48) [MSC v.1929 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr

Unhandled Exception: System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at ClrLoader.DomainData..ctor(AppDomain domain)
   at ClrLoader.ClrLoader.Initialize()
```

**Comment by filmor** [comment]
You need at least .NET 4.7.2. I will close your other issue as well, I assume they are related.

Please do *not* edit the issue template. The .NET Runtime you are using and its version are relevant.

**Comment by joybwang** [comment]
It works with .NET 4.7.2 installed, thank you @filmor
