### ISSUE TITLE
v3.0.0a2 Crashed when bundled used `pyinstaller`

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [pythonnet/pythonnet#1767]
### Environment

-   Pythonnet version: v3.0.0-alpha2 
-   Python version: 3.10.4
-   Operating System: Win10
-   .NET Runtime: 6.0.201

### Details

-   Describe what you were trying to get done.

    I'm using `pywebview` deps on `pythonnet`, since `pythonnet 2.5.x` not works with Python 3.9+, I tried the alpha release version. It works well on the develop environment, however, when I bundled the project used `pyinstaller`, the output executable could not works.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

``` python title="main.py"
# main.py

import webview

webview.create_window('Woah dude!', html='<h1>Woah dude!<h1>')
webview.start()

```
``` shell title="bundle command"
# bundle command
.\.env\Scripts\pyinstaller.exe -wF --hidden-import clr .\main.py
````

-   If there was a crash, please include the traceback here.
``` log title="Unhandled exception in script"
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "webview\__init__.py", line 122, in start
  File "webview\guilib.py", line 101, in initialize
  File "webview\guilib.py", line 62, in try_import
  File "webview\guilib.py", line 52, in import_winforms
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "webview\platforms\winforms.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 36, in load
  File "pythonnet\__init__.py", line 20, in set_default_runtime
  File "clr_loader\__init__.py", line 55, in get_netfx
  File "clr_loader\netfx.py", line 10, in __init__
  File "clr_loader\netfx.py", line 35, in initialize
  File "clr_loader\ffi\__init__.py", line 51, in load_netfx
  File "cffi\api.py", line 150, in dlopen
  File "cffi\api.py", line 832, in _make_ffi_library
  File "cffi\api.py", line 827, in _load_backend_lib
OSError: cannot load library 'C:\Users\Administrator\AppData\Local\Temp\_MEI178122\clr_loader\ffi\dlls\amd64\ClrLoader.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\_MEI178122\\clr_loader\\ffi\\dlls\\amd64\\ClrLoader.dll'

```

**Comment by filmor** [comment]
This is not a supported use case. We are open to PRs and documentation updates, but we are very unlikely to invest time ourselves in making this work.
