### ISSUE TITLE
Cannot implement an interface that extends another interface

### ISSUE THREAD

**Issue by phxnsharp** [pythonnet/pythonnet#1783]
### Environment

-   Pythonnet version: 3.0.0a2
-   Python version: 3.8.10
-   Operating System: Ubuntu 20.04.4 LTS (docker run --rm -it ubuntu:20.04)
-   .NET Runtime: .NET Core 6.0.202

### Details

-   Describe what you were trying to get done.

    Attempting to implement interfaces defined in .NET. Works fine for simple interfaces but I receive a weird error when the interface extends IDisposable

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
from clr_loader import get_coreclr
rt = get_coreclr("conf.json")
from pythonnet import set_runtime
set_runtime(rt)
import clr

import System
import System.Buffers


class MyDisposable(System.IDisposable):
    __namespace__ = "MyNamespace"

    def Dispose(self) -> None:
        print("Dispose")

md = MyDisposable()
md.Dispose()


class MyBuffer(System.Buffers.IMemoryOwner):
    __namespace__ = "MyNamespace"


    def Dispose(self) -> None:
        print("Dispose")


mb = MyBuffer()
mb.Dispose()    
```

conf.json:
```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.4"
    }
  }
}
```

-   If there was a crash, please include the traceback here.

```
(venv) root@ca20f043eef5:/t# python demo.py
Dispose
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    class MyBuffer(System.Buffers.IMemoryOwner):
TypeError: Method 'Dispose' in type 'MyNamespace.MyBuffer' from assembly 'Python.Runtime.Dynamic, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by phxnsharp** [comment]
```python
class MyBuffer(System.Buffers.IMemoryOwner, System.IDisposable):
```

```bash
(venv) root@ca20f043eef5:/t# python demo.py
Dispose
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    class MyBuffer(System.Buffers.IMemoryOwner):
TypeError: Method 'Dispose' in type 'MyNamespace.MyBuffer' from assembly 'Python.Runtime.Dynamic, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Thanks for the thought. Doesn't seem to be supported?

**Comment by phxnsharp** [comment]
Tested this on Windows 10, Python 3.8.10, Pythonnet 3.0.0a2 using .NET Framework (removed the set_runtime() stuff, merely used `import clr`). Had to switch to System.ComponentModel.IComponent as System.Buffers.IMemoryOwner is not available there. I get the exact same error:

```python
>>> import clr
>>> import System
>>> import System.ComponentModel
>>> class Bla(System.ComponentModel.IComponent):
...   __namespace__ = "MyNamespace"
...
...   def Dispose(self) -> None:
...     print("Dispose")
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Method 'Dispose' in type 'MyNamespace.Bla' from assembly 'Python.Runtime.Dynamic, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by phxnsharp** [comment]
The error has nothing specifically to do with IDisposable. Any interface that extends a second interface shows this problem: 

```python
>>> import clr
>>> import System.Collections
>>> class Bla(System.Collections.IDictionary):
...   __namespace__ = "MyNamespace"
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Method 'CopyTo' in type 'MyNamespace.Bla' from assembly 'Python.Runtime.Dynamic, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by lostmsu** [comment]
I do not believe this bug is a 3.0.0 blocker, as this probably never worked in 2.5 either. For 3.0.0 we should focus on regressions and breaking changes.

**Comment by ari62** [comment]
I'm seeing the same error with this for example:

```
from enum import Enum
class SourceKey(str, Enum):
    A = "a"
    B = "b"

```



```
cannot use multiple inheritance with managed classes
 During the algorithm initialization, the following exception has occurred: Loader.TryCreatePythonAlgorithm(): Unable to import python module /somemodule/somepython.py. 
AlgorithmPythonWrapper(): cannot use multiple inheritance with managed classes
  at <module>
```
