### ISSUE TITLE
Python calling .NET Standard 2.0 fails, works with .NET6

### ISSUE THREAD

**Issue by DareDevilDenis** [pythonnet/pythonnet#1803]
### Environment

-   Pythonnet version: 3.0.0a2 (same issue with pip install git+https://github.com/pythonnet/pythonnet)
-   Python version: 3.10.4
-   Operating System: Windows 10
-   .NET Runtime: .NET Standard 2.0

### Details

-   Calling from Python to .NET Standard fails with the following exception. The same code works fine when calling .NET6.

```
I n i t i a l i z a t i o n   f o r   s e l f - c o n t a i n e d   c o m p o n e n t s   i s   n o t   s u p p o r t e d
 Traceback (most recent call last):
  File "C:\Example\call_netstandard2.0.py", line 6, in <module>
    runtime_config_path = get_coreclr(os.path.join(binaries_path, 'NETStandard2ClassLibaryProj.runtimeconfig.json'))
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\__init__.py", line 44, in get_coreclr
    impl = DotnetCoreRuntime(runtime_config=runtime_config, dotnet_root=dotnet_root)
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\hostfxr.py", line 15, in __init__
    self._handle = _get_handle(self._dll, self._dotnet_root, runtime_config)
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\hostfxr.py", line 104, in _get_handle
    check_result(res)
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\util\__init__.py", line 26, in check_result
    raise error
clr_loader.util.clr_error.ClrError: 0x80008093: InvalidConfigFile
Exception ignored in: <function DotnetCoreRuntime.__del__ at 0x0000027B3B9FD000>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\hostfxr.py", line 88, in __del__
  File "C:\Program Files\Python310\lib\site-packages\clr_loader\hostfxr.py", line 83, in shutdown
AttributeError: 'DotnetCoreRuntime' object has no attribute '_handle'
```

Python code:
```python
import os
from clr_loader import get_coreclr
from pythonnet import set_runtime
my_path = os.path.abspath(os.path.dirname(__file__))
binaries_path = os.path.join(my_path, 'NETStandard2ClassLibarySolution/NETStandard2ClassLibaryProj/publish')
runtime_config_path = get_coreclr(os.path.join(binaries_path, 'NETStandard2ClassLibaryProj.runtimeconfig.json'))
set_runtime(runtime_config_path)
import clr

clr.FindAssembly(os.path.join(binaries_path, 'NETStandard2ClassLibaryProj'))
clr.AddReference(os.path.join(binaries_path, 'NETStandard2ClassLibaryProj'))
from NETStandard2ClassLibaryProj import MyAPI

api = MyAPI()
result = api.TestMethod()
print('Result:', result)
```

.NET code:
```c#
namespace NETStandard2ClassLibaryProj
{
    public class MyAPI
    {
        public string TestMethod()
        {
            return "Hello from .NET Standard";
        }
    }
}
```

The .csproj has <GenerateRuntimeConfigurationFiles> set to true, and I publish the files using: `dotnet publish -o publish`

Here's the full code with the .NET Standard and .NET Core projects: [cannot_call_dotnet_standard.zip](https://github.com/pythonnet/pythonnet/files/8799736/cannot_call_dotnet_standard.zip)

**Comment by filmor** [comment]
.NET Standard is not a runtime on its own, you can only use .NET Standard libraries within one of .NET Framework, .NET Core or Mono. Additionally, self-contained components are not supported at all, the error message that you see there is not from us but from .NET itself.
