### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Martmists-GH** [pythonnet/pythonnet#1852]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.9.7/3.10.5
-   Operating System: Arch Linux
-   .NET Runtime: ?

### Details

-   Describe what you were trying to get done.

    Install pythonnet

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

    pip install pythonnet

-   If there was a crash, please include the traceback here.

3.10:

```
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [165 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Checking for updates from https://www.nuget.org/api/v2/.
      Currently running NuGet.exe 4.1.0.
      Updating NuGet.exe to 6.2.1.
      Update successful.
      MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
      
      >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
      
      MSBUILD: error MSBUILD0004: Too many project files specified
      
      WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
      Restoring NuGet package UnmanagedExports.1.2.7.
      Restoring NuGet package System.ValueTuple.4.5.0.
      Restoring NuGet package NUnit.3.12.0.
      Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
      Adding package 'System.ValueTuple.4.5.0' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      Added package 'System.ValueTuple.4.5.0' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
        GET https://api.nuget.org/v3-flatcontainer/unmanagedexports/1.2.7/unmanagedexports.1.2.7.nupkg
        GET https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/3.11.1/nunit.consolerunner.3.11.1.nupkg
        GET https://api.nuget.org/v3-flatcontainer/nunit/3.12.0/nunit.3.12.0.nupkg
        OK https://api.nuget.org/v3-flatcontainer/nunit/3.12.0/nunit.3.12.0.nupkg 204ms
        OK https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/3.11.1/nunit.consolerunner.3.11.1.nupkg 204ms
        OK https://api.nuget.org/v3-flatcontainer/unmanagedexports/1.2.7/unmanagedexports.1.2.7.nupkg 399ms
      Installed NUnit.ConsoleRunner 3.11.1 from https://api.nuget.org/v3/index.json with content hash JONNeR6DlUMup+s9qTFxzdncsDlAtLbq45Cj6NiJJ8r3PzxOf93AviJ7jc0kFNQK9m7oSV5C/uR29KnePhm0BQ==.
      Adding package 'NUnit.ConsoleRunner.3.11.1' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      Added package 'NUnit.ConsoleRunner.3.11.1' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      Installed UnmanagedExports 1.2.7 from https://api.nuget.org/v3/index.json with content hash bPIbzFaAj4AFxjHGFGPrYnUSCyIWJMkT/LFuiphWdpUbO2L9fP68W/1SP9cHCAxgiekV+kFNbybA2VvRo8PYIQ==.
      Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      Installed NUnit 3.12.0 from https://api.nuget.org/v3/index.json with content hash 3oJTrcUcT9wmweBUwgUf0f1XIYy6RZq2ziV+RM95HMKAJGsHPN2i3MKK1dAPvDPMRLz799Llj4eyu/STB9Q7OA==.
      Adding package 'NUnit.3.12.0' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      Added package 'NUnit.3.12.0' to folder '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/packages'
      
      NuGet Config files used:
          /home/mart/.config/NuGet/NuGet.Config
      
      Feeds used:
          /home/mart/.nuget/packages/
          https://api.nuget.org/v3/index.json
      
      Installed:
          4 package(s) to packages.config projects
      
      >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
      
      XBuild Engine Version 14.0
      Mono, Version 6.12.0.0
      Copyright (C) 2005-2013 Various Mono authors
      
      Build started 7/4/2022 12:01:44 AM.
      __________________________________________________
      Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/pythonnet.sln" (Clean target(s)):
          Target ValidateSolutionConfiguration:
                  Building solution configuration "ReleaseMono|x64".
          Target Clean:
                  Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/Python.Runtime.csproj" (Clean target(s)):
                          Target CoreClean:
                                  Deleting file '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                  Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/Python.Runtime.csproj".
                  The project 'clrmodule' is disabled for solution configuration 'ReleaseMono|x64'.
                  Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/testing/Python.Test.csproj" (Clean target(s)):
                          Target CoreClean:
                                  Deleting file '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/testing/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                  Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/testing/Python.Test.csproj".
                  Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/embed_tests/Python.EmbeddingTest.csproj" (Clean target(s)):
                          Target CoreClean:
                                  Deleting file '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/embed_tests/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                  Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/embed_tests/Python.EmbeddingTest.csproj".
                  Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/console/Console.csproj" (Clean target(s)):
                          Target CoreClean:
                                  Deleting file '/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/console/obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs'
                  Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/console/Console.csproj".
      Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/pythonnet.sln".
      
      Build succeeded.
           0 Warning(s)
           0 Error(s)
      
      Time Elapsed 00:00:01.8950710
      
      >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
      
      XBuild Engine Version 14.0
      Mono, Version 6.12.0.0
      Copyright (C) 2005-2013 Various Mono authors
      
      Build started 7/4/2022 12:01:46 AM.
      __________________________________________________
      Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/pythonnet.sln" (Build target(s)):
          Target ValidateSolutionConfiguration:
                  Building solution configuration "ReleaseMono|x64".
          Target Build:
                  Project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/Python.Runtime.csproj" (default target(s)):
                          Target PrepareForBuild:
                                  Configuration: ReleaseMono Platform: x64
                                  Created directory "bin/"
                          Target GenerateSatelliteAssemblies:
                          No input files were specified for target GenerateSatelliteAssemblies, skipping.
                          Target CoreCompile:
                                  Tool /usr/lib/mono/4.5/csc.exe execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/x64/ReleaseMono/Python.Runtime.dll /resource:obj/x64/ReleaseMono/Python.Runtime.resources.clr.py,clr.py Codecs/EncoderGroup.cs Codecs/DecoderGroup.cs Codecs/RawProxyEncoder.cs Codecs/TupleCodecs.cs converterextensions.cs finalizer.cs Properties/AssemblyInfo.cs ../SharedAssemblyInfo.cs arrayobject.cs assemblymanager.cs BorrowedReference.cs classderived.cs classbase.cs classmanager.cs classobject.cs clrobject.cs codegenerator.cs constructorbinder.cs constructorbinding.cs converter.cs CustomMarshaler.cs debughelper.cs delegatemanager.cs delegateobject.cs eventbinding.cs eventobject.cs exceptions.cs extensiontype.cs fieldobject.cs generictype.cs genericutil.cs importhook.cs indexer.cs interfaceobject.cs interfaces.cs interop.cs iterator.cs managedtype.cs metatype.cs methodbinder.cs methodbinding.cs methodobject.cs methodwrapper.cs modulefunctionobject.cs moduleobject.cs modulepropertyobject.cs nativecall.cs NewReference.cs NonCopyableAttribute.cs overload.cs propertyobject.cs pyansistring.cs pydict.cs PyExportAttribute.cs pyfloat.cs pyint.cs pyiter.cs pylist.cs pylong.cs pynumber.cs pyobject.cs pyscope.cs pysequence.cs pystring.cs pythonengine.cs pythonexception.cs pytuple.cs ReferenceExtensions.cs runtime.cs typemanager.cs typemethod.cs Util.cs platform/Types.cs platform/LibraryLoader.cs polyfill/ReflectionPolifills.cs slots/mp_length.cs interop310.cs obj/x64/ReleaseMono/.NETFramework,Version=v4.0.AssemblyAttribute.cs /target:library /unsafe+ /define:"PYTHON310;PYTHON3;UCS4;MONO_LINUX;PYTHON_WITHOUT_ENABLE_SHARED" /nowarn:1591 /doc:bin/Python.Runtime.xml /langversion:7.3 /nostdlib /reference:/usr/lib/mono/4.0-api/System.dll /reference:/usr/lib/mono/4.0-api/System.Core.dll /reference:/usr/lib/mono/4.0-api//mscorlib.dll
                                  Microsoft (R) Visual C# Compiler version 3.9.0-6.21124.20 (db94f4cc)
                                  Copyright (C) Microsoft Corporation. All rights reserved.
      runtime.cs(75,8): error CS1029: #error: 'You must define one of PYTHON34 to PYTHON39 or PYTHON27'
                          Task "Csc" execution -- FAILED
                          Done building target "CoreCompile" in project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/Python.Runtime.csproj".-- FAILED
                  Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/Python.Runtime.csproj".-- FAILED
          Task "MSBuild" execution -- FAILED
          Done building target "Build" in project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/pythonnet.sln".-- FAILED
      Done building project "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/pythonnet.sln".-- FAILED
      
      Build FAILED.
      Errors:
      
      /tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/pythonnet.sln (Build) ->
      (Build target) ->
      /tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/src/runtime/Python.Runtime.csproj (default targets) ->
      /usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
      
          runtime.cs(75,8): error CS1029: #error: 'You must define one of PYTHON34 to PYTHON39 or PYTHON27'
      
           0 Warning(s)
           1 Error(s)
      
      Time Elapsed 00:00:01.5108410
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/setup.py", line 630, in <module>
          setup(
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/setup.py", line 612, in run
          return bdist_wheel.bdist_wheel.run(self)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 449, in build_extensions
          self._build_extensions_serial()
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/distutils/command/build_ext.py", line 474, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/setup.py", line 353, in build_extension
          subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
        File "/home/mart/.pyenv/versions/3.10.5/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON310%3BPYTHON3%3BUCS4%3BMONO_LINUX%3BPYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/tmp/pip-install-tuz3w366/pythonnet_73fee7e3eac141dba84606caf9220193/build/lib.linux-x86_64-3.10" /p:PythonInteropFile="interop310.cs" /p:PackageId=pythonnet_py310_x64 /verbosity:normal /t:Build' returned non-zero exit status 1.
      [end of output]
```

3.9:

```
Installing collected packages: pythonnet, cffi, clr_loader
  Running setup.py install for pythonnet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pythonnet did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: option --single-version-externally-managed not recognized
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pythonnet
```

**Comment by filmor** [comment]
Neither Python 3.9 nor 3.10 is supported with pythonnet 2.5.
