### ISSUE TITLE
System.AccessViolationException when using the wrong runtime

### ISSUE THREAD

**Issue by TTSPhilipp** [pythonnet/pythonnet#1886]
### Environment

-   Pythonnet version: 3.0.0rc4
-   Python version: 3.9.7
-   Operating System: Win10
-   .NET Runtime: .NET6

### Details

I am developing an application where the user can select a assembly to be loaded. Unfortunately, it is not possible to reliably determine for which target framework version the assembly was built. Therefore it can happen that pythonnet is executed with the wrong runtime.

If you try to instantiate a class in the assembly several times in a row, you will get a **System.AccessViolationException**

-   Minimal example

```python
import sys
from pythonnet import unload

for _ in range(10):
    try:
        unload()
        import clr
        from System import Type

        sys.path.append(r'<path to assembly file with .NET 6 as target framework version>')
        assembly = clr.AddReference('<assembly name>')
        testbenchClass = assembly.GetType('<c# class name>')
        testbenchConstructor = testbenchClass.GetConstructor(Type.EmptyTypes)
        testbenchConstructor.Invoke([])
    except Exception as e:
        print(e)
```

-   Most of the time the error happens on the third run

```python
System.TypeLoadException: Could not load type "System.IO.Path" from assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
   at A.B.C.D.Logging.SetupLogging()
   at A.B.C.D.E..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
System.TypeLoadException: Could not load type "System.IO.Path" from assembly "System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
   at A.B.C.D.Logging.SetupLogging()
   at A.B.C.D.E..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at Python.Runtime.ManagedType.TryFreeGCHandle(BorrowedReference reflectedClrObject, BorrowedReference type)
   at Python.Runtime.Runtime.NullGCHandles(IEnumerable`1 objects)
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.PythonEngine.Shutdown()
   at Python.Runtime.Loader.Shutdown(IntPtr data, Int32 size)
```

**Comment by filmor** [comment]
Repeated loading and unloading is not supported and should probably lead to an exception. What you are doing here is effectively running everything once, taking down the runtime (implicitly, there is no `close` there yet, it relies on the reference count going to zero) and then shutting down the pythonnet mechanisms. The subsequent `import clr` is a no-op, so you are in an invalid state here anyhow.

As to your actual problem, I'm not sure how you'd deal with it even if you could detect the necessary runtime from the DLL. It's impossible to run multiple .NET runtimes (in particular Framework and Core) within the same process, and it's also impossible to restart the Core CLR.

**Comment by TTSPhilipp** [comment]
Okay too bad. Then I have to do the whole thing in a process and restart it in case of an error.

Thanks for the quick feedback. And thanks for the great work on release 3.0!
