### ISSUE TITLE
ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by jperezmedina** [pythonnet/pythonnet#1894]
### Environment

-   Pythonnet version: pythonnet 3.0.0rc4
-   Python version: Python 3.10.5
-   Operating System: Ubuntu 22.04
-   .NET Runtime: SDK 6.0.302

### Details

-   When I try to import clr on my program I have the following error:

Program:

1   import sys
2   import time
3
4   # The CLR module provide functions for interacting with the underlying .NET runtime
5   import clr
......

------------------------------

Error:

Traceback (most recent call last):
  File "/home/jperezmedina/Documents/test/myapp.py", line 5, in <module>
    import clr
  File "/home/jperezmedina/.local/lib/python3.10/site-packages/clr.py", line 6, in <module>
    load()
  File "/home/jperezmedina/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 103, in load
    set_runtime_from_env()
  File "/home/jperezmedina/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 84, in set_runtime_from_env
    runtime = _create_runtime_from_spec(spec)
  File "/home/jperezmedina/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 59, in _create_runtime_from_spec
    return clr_loader.get_mono(**params)
  File "/home/jperezmedina/.local/lib/python3.10/site-packages/clr_loader/__init__.py", line 21, in get_mono
    libmono = find_libmono(sgen)
  File "/home/jperezmedina/.local/lib/python3.10/site-packages/clr_loader/util/find.py", line 62, in find_libmono
    from ctypes.util import find_library
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

**Comment by filmor** [comment]
This means that your Python installation is messed up and that you didn't actually configure it to use .NET6 but Mono instead.

**Comment by jperezmedina** [comment]
The manner I installed pythonned was with the command:

pip install pythonnet [--pre] -U (--pre gets the latest development build uploaded to PyPI) documented at https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

How I can solve my situation ?
