### ISSUE TITLE
Could not load file or assembly 'System.Windows.Forms' 

### ISSUE THREAD

**Issue by jperezmedina** [pythonnet/pythonnet#1895]
### Environment

-   Pythonnet version: pythonnet 3.0.0rc4
-   Python version: Python 3.10.4
-   Operating System: Ubuntu 22.04
-   .NET Runtime: SDK 6.0.302

### Details

-   When I try to use the reference to System.Windows.Forms I get the error:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

The runtime configuration file is:

```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.7"
    }
  }
}

```

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

-   If there was a crash, please include the traceback here.

```python
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythonnet
>>> from clr_loader import get_coreclr
>>> from pythonnet import set_runtime
>>> rt = get_coreclr("runtimeconfig.json")
>>> set_runtime(rt)
>>> import clr
>>> clr.AddReference("System.Drawing")
<System.Reflection.RuntimeAssembly object at 0x7fd6a9684cc0>
>>> clr.AddReference("System.ComponentModel")
<System.Reflection.RuntimeAssembly object at 0x7fd6a9b6a340>
>>> clr.AddReference("System.Windows.Forms")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Python.Runtime.AssemblyManager.LoadAssembly(AssemblyName name) in /tmp/build-via-sdist-sstjjspf/pythonnet-3.0.0rc4/src/runtime/AssemblyManager.cs:line 227
   at Python.Runtime.CLRModule.AddReference(String name) in /tmp/build-via-sdist-sstjjspf/pythonnet-3.0.0rc4/src/runtime/Types/ModuleObject.cs:line 507

```

**Comment by sschukat** [comment]
Even if an assembly is available in .NET 6 it does not mean, that you can use it platform overarching.  The System.Windows.Forms depends on the win32 native subsystem. This subsystem is not available under Linux and hence the full functionality could not be used under Linux, i.e. this use case will not work due to limitation of .NET 6. 
If you want overarching UI you should used wxWindows or Qt or HTML with CSS. Microsoft does not offer a UI framework for Linux.

**Comment by sschukat** [comment]
In addition you could try [avalonia](https://github.com/AvaloniaUI/Avalonia) as OSS alternative.
