### ISSUE TITLE
I encountered a type conversion error

### ISSUE THREAD

**Issue by Chris0William** [pythonnet/pythonnet#1910]
### Environment

-   Pythonnet version:3.0.0.0
-   Python version:3.8.8
-   Operating System:Windows 11
-   .NET Runtime: .NET 6

### Details

-   I am trying to convert Numpy array type to double[] an exception occurred "Cannot implicitly convert type 'Python.Runtime.PyObject' to 'double[]'"

```C#
       
        public static  double[] TestByPythonNet(List<double> list)
        {
            double[] results;
            using ( Py.GIL() )
            {
                dynamic sampleModule = Py.Import("PySpectrum");
                dynamic results_py = sampleModule.sample_func(listSource, 12800);
                double[] results=results_py ;
            }
            return results;
        }
    
```

- Exception

```Exception
    Unhandled exception. System.InvalidCastException: cannot convert object to target type
 ---> Python.Runtime.PythonException: 'numpy.ndarray' value cannot be converted to System.Double
   --- End of inner exception stack trace ---
   at Python.Runtime.PyObject.AsManagedObject(Type t) in C:\Users\10597\OneDrive\桌面\pythonnet-master\src\runtime\PythonTypes\PyObject.cs:line 168
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at NET6TEST.Utils.TestByPythonNet(List`1 listSource) in D:\workspace-net\NET6TEST\Utils.cs:line 23
   at Program.<>c__DisplayClass0_1.<<Main>$>b__0() in D:\workspace-net\NET6TEST\Program.cs:line 22
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in D:\workspace-net\NET6TEST\Program.cs:line 19
   at Program.<Main>(String[] args)
```

- or
```C#
public static  double[] TestByPythonNet(List<double> list)
        {
            double[] results;
            using ( Py.GIL() )
            {
                dynamic sampleModule = Py.Import("PySpectrum");
                PyObject results_py = sampleModule.sample_func(listSource, 12800);
                double[] results=results_py.AsManagedObject(typeof(double[]));
            }
            return results;
        }
```

- Exception

```Exception
    Unhandled exception. System.InvalidCastException: cannot convert object to target type
 ---> Python.Runtime.PythonException: Cannot convert <module 'PySpectrum' from 'D:\\Anacounda\\envs\\py3.8\\PySpectrum.py'> to System.Double[]
 ---> Python.Runtime.PythonException: 'module' object is not iterable
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Python.Runtime.PyObject.AsManagedObject(Type t) in C:\Users\10597\OneDrive\桌面\pythonnet-master\src\runtime\PythonTypes\PyObject.cs:line 168
   at NET6TEST.Utils.TestByPythonNet(List`1 listSource) in D:\workspace-net\NET6TEST\Utils.cs:line 21
   at Program.<>c__DisplayClass0_1.<<Main>$>b__0() in D:\workspace-net\NET6TEST\Program.cs:line 22
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Program.<Main>$(String[] args) in D:\workspace-net\NET6TEST\Program.cs:line 19
   at Program.<Main>(String[] args)
```

-But when I use the PythonNet 3.0.0.0 preview 2021-08-03, this issue will not occur

**Comment by ksrangarajan** [comment]
We are facing similar issue with Pythonnet 3.0. Can you help us with solution you used?

**Comment by ArpanM30** [comment]
@Chris0William 
I am facing same issue with user defined type. Can you help with the workaround you used?
