### ISSUE TITLE
Error when installing from source on Windows

### ISSUE THREAD

**Issue by qysnn** [pythonnet/pythonnet#1933]
### Environment

-   Pythonnet version: master branch
-   Python version: 3.8.5
-   Operating System: Windows 10

### Details
I am trying to install from source on Windows. Yet I got 2 errors.
```
(base) PS C:\WINDOWS\system32> pip install git+https://github.com/yagweb/pythonnet
Collecting git+https://github.com/yagweb/pythonnet
  Cloning https://github.com/yagweb/pythonnet to c:\users\user\appdata\local\temp\pip-req-build-2e0boeyi
  Running command git clone --filter=blob:none --quiet https://github.com/yagweb/pythonnet 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi'
  Resolved https://github.com/yagweb/pythonnet to commit 3ffde8116d913bf393ad8a48282c73592d1e4b26
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [98 lines of output]
      C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py:530: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
        warnings.warn(tmpl.format(**locals()))
      running bdist_wheel
      running build
      running build_ext
      ?????? https://www.nuget.org/api/v2/ ????
      ?????? NuGet.exe 4.1.0?
      ??? NuGet.exe ??? 6.2.1?
      ?????
      Cannot find the specified version of msbuild: '14'
      MSBuild auto-detection: using msbuild version '17.0.0.52104' from 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin'.
      Restoring NuGet package UnmanagedExports.1.2.7.
      Restoring NuGet package NUnit.3.7.1.
      Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
      Adding package 'NUnit.3.7.1' to folder 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\packages'
      Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\packages'
      Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\packages'
      Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\packages'
      Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\packages'
      Added package 'NUnit.3.7.1' to folder 'C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\packages'

      NuGet Config files used:
          C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\NuGet.Config
          C:\Users\User\AppData\Roaming\NuGet\NuGet.Config
          C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

      Feeds used:
          C:\Users\User\.nuget\packages\
          https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
          https://api.nuget.org/v3/index.json
          C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

      Installed:
          3 package(s) to packages.config projects
      Traceback (most recent call last):
        File "tools\geninterop\geninterop.py", line 293, in <module>
          sys.exit(main())
        File "tools\geninterop\geninterop.py", line 273, in main
          python_h = preprocess_python_headers()
        File "tools\geninterop\geninterop.py", line 193, in preprocess_python_headers
          for line in _check_output(cmd).splitlines():
        File "tools\geninterop\geninterop.py", line 41, in _check_output
          output = subprocess.check_output(*args, **kwargs)
        File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 411, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 489, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] \u7cfb\u7edf\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6587\u4ef6\u3002
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\setup.py", line 637, in <module>
          setup(
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\setup.py", line 615, in run
          return bdist_wheel.bdist_wheel.run(self)
        File "C:\ProgramData\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\User\AppData\Local\Temp\pip-req-build-2e0boeyi\setup.py", line 302, in build_extension
          subprocess.check_call([sys.executable, geninterop, interop_file])
        File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\ProgramData\\Anaconda3\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop38.cs']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Attempting uninstall: pythonnet
    Found existing installation: pythonnet 2.5.2
    Uninstalling pythonnet-2.5.2:
      Successfully uninstalled pythonnet-2.5.2
  Running setup.py install for pythonnet ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pythonnet did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      C:\ProgramData\Anaconda3\lib\site-packages\setuptools\dist.py:530: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
        warnings.warn(tmpl.format(**locals()))
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: option --single-version-externally-managed not recognized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\programdata\anaconda3\lib\site-packages
  Rolling back uninstall of pythonnet
  Moving to c:\programdata\anaconda3\lib\site-packages\clr.pyd
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\clr.pyd
  Moving to c:\programdata\anaconda3\lib\site-packages\python.runtime.dll
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\python.runtime.dll
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\direct_url.json
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\direct_url.json
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\installer
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\installer
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\metadata
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\metadata
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\record
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\record
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\requested
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\requested
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\top_level.txt
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\top_level.txt
  Moving to c:\programdata\anaconda3\lib\site-packages\pythonnet-2.5.2.dist-info\wheel
   from C:\Users\User\AppData\Local\Temp\pip-uninstall-drh2vkxy\pythonnet-2.5.2.dist-info\wheel
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pythonnet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
I googled for `--single-version-externally-managed` error and updated `pip, setuptools, wheel` as suggested. The error is still here. Any suggestions? Thanks!

**Comment by filmor** [comment]
You are installing from a fork.

**Comment by qysnn** [comment]
@filmor Oh I see. Thanks! The wiki lists it as an example of installing from pull requests but I mistake it for the command to install from master. After switching to `pip install git+https://github.com/pythonnet/pythonnet` the installation works smoothly :)
