### ISSUE TITLE
Unable to run example code (Embedding Python in .NET)

### ISSUE THREAD

**Issue by SirSahelanthropus-TheWise** [pythonnet/pythonnet#1935]
### Environment

-   Pythonnet version: 3.0.0-rc4
-   Python version: 3.5
-   Operating System: Windows 10
-   .NET Runtime: .NET 6

### Details

-   I was trying to run the example code in a console application.

```C#
using Python.Runtime;

namespace PythonNet_Experiment
{
    public static class Program
    {
        public static void Main()
        {
            Runtime.PythonDLL = @"C:\Users\<My Username>\AppData\Local\Programs\Python\Python35\python35.dll";
            PythonEngine.Initialize(); // This is the line throwing the error
            using (Py.GIL())
            {
                dynamic np = Py.Import("numpy");
                Console.WriteLine(np.cos(np.pi * 2));
            }
        }
    }
}
```

-   If there was a crash, please include the traceback here.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Delegates' threw an exception.
 ---> System.MissingMethodException: Failed to load symbol _PyThreadState_UncheckedGet.
 ---> System.ComponentModel.Win32Exception (127): The specified procedure could not be found.
   --- End of inner exception stack trace ---
   at Python.Runtime.Platform.WindowsLoader.GetFunction(IntPtr hModule, String procedureName)
   at Python.Runtime.Runtime.Delegates.GetFunctionByName(String functionName, IntPtr libraryHandle)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at PythonNet_Experiment.Program.Main() in C:\Users\<My Username>\Desktop\PythonInterop\Program.cs:line 11
```

**Comment by filmor** [comment]
Python 3.5 is not supported anymore.
