### ISSUE TITLE
Facing exception: Python ABI v3.6.0 is not supported: Searching for Python.Runtime.TypeOffset36 

### ISSUE THREAD

**Issue by rohitpungliya** [pythonnet/pythonnet#1975]
### Environment

-   Pythonnet version: 3.1.0
-   Python version: 3.6.0
-   Operating System: Windows 10
-   .NET Runtime: <TargetFramework>net6.0-windows</TargetFramework>

### Details
I am trying to initialize Python.Runtime in my C# project. It works for Python 3.9.0. But I get following exception for Python 3.6.0:

**System.NotSupportedException
  HResult=0x80131515
  Message=Python ABI v3.6.0 is not supported: Searching for Python.Runtime.TypeOffset36, found TypeOffset,TypeOffset310,TypeOffset37,TypeOffset38,TypeOffset39.
  Source=Python.Runtime
  StackTrace:
   at Python.Runtime.Native.ABI.Initialize(Version version) in C:\WORK\GitRepos\Python.Net\src\runtime\Native\ABI.cs:line 33
   at Python.Runtime.Runtime.Initialize(Boolean initSigs) in C:\WORK\GitRepos\Python.Net\src\runtime\Runtime.cs:line 147
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs) in C:\WORK\GitRepos\Python.Net\src\runtime\PythonEngine.cs:line 206
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs) in C:\WORK\GitRepos\Python.Net\src\runtime\PythonEngine.cs:line 181
   at Python.Runtime.PythonEngine.Initialize() in C:\WORK\GitRepos\Python.Net\src\runtime\PythonEngine.cs:line 176**

 StackTrace:
   at Python.Runtime.Native.ABI.Initialize(Version version) in C:\WORK\GitRepos\Python.Net\src\runtime\Native\ABI.cs:line 33
   at Python.Runtime.Runtime.Initialize(Boolean initSigs) in C:\WORK\GitRepos\Python.Net\src\runtime\Runtime.cs:line 147
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs) in C:\WORK\GitRepos\Python.Net\src\runtime\PythonEngine.cs:line 206
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs) in C:\WORK\GitRepos\Python.Net\src\runtime\PythonEngine.cs:line 181
   at Python.Runtime.PythonEngine.Initialize() in C:\WORK\GitRepos\Python.Net\src\runtime\PythonEngine.cs:line 176

**Comment by filmor** [comment]
Python 3.6 is not supported anymore.

**Comment by rohitpungliya** [comment]
Thanks Benedikt,
Thanks for responding. Will it be possible for me to use older version of pythonnet which supports Python 3.6?
If yes then from where can I get it?

Please let me know.

Thanks & regards,
Rohit
