### ISSUE TITLE
Tried the fix posted, still doesnt work

### ISSUE THREAD

**Issue by Awire9966** [pythonnet/pythonnet#1992]
*After trying again it still failed.*
Tried out the following: https://github.com/pythonnet/pythonnet/issues/1989#issuecomment-1294910917
### Environment

-   Pythonnet version: 3.0
-   Python version: 3.11
-   Operating System: Windows 10
-   .NET Runtime: Net Framework 4.7.1

### Details

-   Describe what you were trying to get done.

    I was trying to test the features of pythonnet because I was really hopeful for this api.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

I tried setting the DLL location with the variable and it straight up crashes. I tried using the python38 dll but that gives the same error.
```
 Unhandled Exception: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception. ---> System.DllNotFoundException: Could not load C:\Users\Awire\source\repos\pythonnettest\pythonnettest\bin\Debug\python311.dll. ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   --- End of inner exception stack trace ---
   at Python.Runtime.Platform.WindowsLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates.GetUnmanagedDll(String libraryName)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at pythonnettest.Program.Main(String[] args) in C:\Users\Awire\source\repos\pythonnettest\pythonnettest\Program.cs:line 17C:\Users\Awire\source\repos\pythonnettest\pythonnettest\bin\Debug\python311.dll. ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   --- End of inner exception stack trace ---
   at Python.Runtime.Platform.WindowsLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates.GetUnmanagedDll(String libraryName)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at pythonnettest.Program.Main(String[] args) in C:\Users\Awire\source\repos\pythonnettest\pythonnettest\Program.cs:line 17
```
My C# code
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Python.Runtime;
using Python;
using System.IO;

namespace pythonnettest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Runtime.PythonDLL = System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location) + @"\python310.dll";
            PythonEngine.Initialize();
            PythonEngine.Exec("print('Hello')");
            

        }
    }
}

```
-   If there was a crash, please include the traceback here.

N/A

**Comment by lostmsu** [comment]
This is not a bug. The error contains the relevant hint for the resolution.

**Comment by Awire9966** [comment]
It says the DLL is not a vaild app

**Comment by chaojian-zhang** [comment]
I am getting the same error. The exact same setup works in .Net 6 but doesn't work in .Net Framework 4.8 - @Awire9966 did you find a resolution?

![image](https://user-images.githubusercontent.com/7077098/201747967-6331f497-c478-4677-a64d-f10c81ae6758.png)

Python embeddable is downloaded from [official website](https://www.python.org/ftp/python/3.10.8/python-3.10.8-embed-amd64.zip).

**Comment by chaojian-zhang** [comment]
> I am getting the same error. The exact same setup works in .Net 6 but doesn't work in .Net Framework 4.8 - @Awire9966 did you find a resolution?
> 
> ![image](https://user-images.githubusercontent.com/7077098/201747967-6331f497-c478-4677-a64d-f10c81ae6758.png)
> 
> Python embeddable is downloaded from [official website](https://www.python.org/ftp/python/3.10.8/python-3.10.8-embed-amd64.zip).
> 
> As your original question goes, the error message indicates your setup is probably not clean, since it's mentioning `C:\Users\Awire\source\repos\pythonnettest\pythonnettest\bin\Debug\python311.dll`

Oh, problem solved - turns out by default .Net Framework 4.8 compiles to x32, I need to either point to a 32bit python or force it to compile as x64.
