### ISSUE TITLE
System.ComponentModel.Win32Exception: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by Awire9966** [pythonnet/pythonnet#2100]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.10
-   Operating System: Windows 10 Pro 64 bit
-   .NET Runtime: 4.7.1

### Details

-   Describe what you were trying to get done.
I wanted to simply try out pythonnet to see if it would be of use to me.
  

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
My C# code:
  ```
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Python.Runtime;

using Python;
using System.IO;

namespace pythonnettest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", Environment.CurrentDirectory + @"\python310.dll");
            PythonEngine.Initialize();
            PythonEngine.Exec("print('Hello')");
            

        }
    }
}
``` 

-   If there was a crash, please include the traceback here.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Delegates' threw an exception. ---> System.DllNotFoundException: Could not load C:\Users\Awire\source\repos\pythonnettest\pythonnettest\bin\Debug\python310.dll. ---> System.ComponentModel.Win32Exception: %1 is not a valid Win32 application
   --- End of inner exception stack trace ---
   at Python.Runtime.Platform.WindowsLoader.Load(String dllToLoad)
   at Python.Runtime.Runtime.Delegates.GetUnmanagedDll(String libraryName)
   at Python.Runtime.Runtime.Delegates..cctor()
   --- End of inner exception stack trace ---
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at pythonnettest.Program.Main(String[] args) in C:\Users\Awire\source\repos\pythonnettest\pythonnettest\Program.cs:line 18
```

**Comment by calebTree** [comment]
I've got that issue also.
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Delegates' threw an exception.
  Source=Python.Runtime
  StackTrace:
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\caleb\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 27

Inner Exception 1:
DllNotFoundException: Could not load C:\.venv\python38.dll.

Inner Exception 2:
Win32Exception: %1 is not a valid Win32 application
```

As you can see it also says `DllNotFoundException`. 
```
Runtime.PythonDLL = @"C:\.venv\python38.dll";
```
That one is also baffling me. Without a question the dll is there. I was originally using a `python310.dll` dll also and tried a `python38.dll` as that is what is mentioned in the GitHub [README.rst](https://github.com/pythonnet/pythonnet/blob/master/README.rst#embedding-python-in-net).
```
SHA1 hash of C:\.venv\python310.dll:
bfa3d380231166f7c2603ca89a984a5cad9752ab
SHA1 hash of C:\.venv\python38.dll:
b64fe169690557656ede3ae50d3c5a197fea6013
```

**Comment by Awire9966** [comment]
I was hoping not to use Net 6.0 for reasons, but if its a must then well

**Comment by filmor** [comment]
It's not a must. You are probably just messing up the bit ess, .NET FW apps compile as x86 applications by default.
