### ISSUE TITLE
Exception in  Python.Runtime.Py.GIL()

### ISSUE THREAD

**Issue by rvinothrajendran** [pythonnet/pythonnet#2106]
### Environment

-   Pythonnet version: 2.5.1.0
-   Python version: 3.10
-   Operating System: Windows 10
-   .NET Runtime: 

### Details

We followed the same installation steps, but an exception occurred when using PythonNET on one of the PCs. The rest of the PCs are working without any issues. The details of the exception are provided below.

   System.Exception: Initialization of PythonWorker failed. RuntimePath is: 'C:\Program Files\Python38\' ---> Python.Runtime.PythonException: SystemError : <built-in function __import__> returned a result with an error set
   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.RunString(String code, Nullable`1 globals, Nullable`1 locals, RunFlagType flag)
   at Python.Runtime.PythonEngine.Exec(String code, Nullable`1 globals, Nullable`1 locals)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.Py.GIL()
`

Kindly inform me of the solution to resolve this problem.

**Comment by rvinothrajendran** [comment]
great
