### ISSUE TITLE
`import clr` not working with mono on linux

### ISSUE THREAD

**Issue by nathan-wan** [pythonnet/pythonnet#2127]
### Discussed in https://github.com/pythonnet/pythonnet/discussions/2126

<div type='discussions-op-text'>

<sup>Originally posted by **nathan-wan** March 15, 2023</sup>
### Environment

-   Pythonnet version:  3.0.1 
-   Python version: 3.9
-   Operating System: Linux
-   .NET Runtime: mono

### Details

-   Describe what you were trying to get done.

Trying to use pythonnet and libmono as part of another package, https://github.com/MannLabs/alphapeptdeep

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```bash
$ python -c 'import clr'
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/pythonnet/__init__.py", line 75, in _create_runtime_from_spec
    return clr_loader.get_mono(**params)
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/clr_loader/__init__.py", line 73, in get_mono
    libmono = find_libmono(sgen=sgen)
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/clr_loader/util/find.py", line 145, in find_libmono
    raise RuntimeError("Could not find libmono")
RuntimeError: Could not find libmono

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/clr.py", line 6, in <module>
    load()
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/pythonnet/__init__.py", line 131, in load
    set_runtime_from_env()
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/pythonnet/__init__.py", line 114, in set_runtime_from_env
    runtime = _create_runtime_from_spec(spec)
  File "/home/ec2-user/miniconda3/envs/peptdeeptest/lib/python3.9/site-packages/pythonnet/__init__.py", line 82, in _create_runtime_from_spec
    raise RuntimeError(
RuntimeError: Failed to create a default .NET runtime, which would
                    have been "mono" on this system. Either install a
                    compatible runtime or configure it explicitly via
                    `set_runtime` or the `PYTHONNET_*` environment variables
                    (see set_runtime_from_env).
```

I've verified that mono is installed corrected with this: https://www.mono-project.com/docs/getting-started/mono-basics/

</div>

**Comment by filmor** [comment]
I'm not quite sure how you would come to think that this is acceptable behaviour.

I intentionally moved the issue to a discussion as the issues are meant for bugs, not to give you unpaid support. You didn't even supply the most basic information (distribution, install method, versions). Add that information and what you were attempting via the given parameters (check the clr_loader docs) to the discussion and see whether someone helps you out.
