### ISSUE TITLE
Improvement: Avoid error when loading 'coreclr' multiple times

### ISSUE THREAD

**Issue by Essoz** [pythonnet/pythonnet#2130]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: Python 3.10.6
-   Operating System: Ubuntu 22.04.1 LTS x86_64 
-   .NET Runtime: 6.0.406

### Details

-   Describe what you were trying to get done.

    I have written multiple custom python modules that call c# from python. For some purposes, all these modules uses the .NET coreclr runtime other than the default mono runtime. So each of these modules has `load('coreclr')` in their `__init__.py`.   

    In my use case where `load('coreclr')` is executed multiple times, an failed-to-load python runtime exception will be thrown.  

    I suggest to somehow skip the loading of 'coreclr' if it is already loaded, just to avoid this exception.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

Loading 'coreclr' two times will reproduce the error. 
```python
from pythonnet import load
load('coreclr')
load('coreclr')    
```

-   If there was a crash, please include the traceback here.

```python
>>> from pythonnet import load
>>> load('coreclr')
>>> load('coreclr')
Failed to initialize pythonnet: System.InvalidOperationException: This property must be set before runtime is initialized
   at Python.Runtime.Runtime.set_PythonDLL(String value) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.cs:line 27
   at Python.Runtime.Loader.Initialize(IntPtr data, Int32 size) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Loader.cs:line 23
   at Python.Runtime.Runtime.set_PythonDLL(String value) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Runtime.cs:line 27
   at Python.Runtime.Loader.Initialize(IntPtr data, Int32 size) in /tmp/build-via-sdist-dq4gmg3h/pythonnet-3.0.1/src/runtime/Loader.cs:line 23Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/v-yuxujiang/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 144, in load
    raise RuntimeError("Failed to initialize Python.Runtime.dll")
RuntimeError: Failed to initialize Python.Runtime.dll
```

Update:

For your information, this issue might be similar to https://github.com/pythonnet/pythonnet/issues/2099.

**Comment by filmor** [comment]
This is already fixed on master.

**Comment by DeniseSkidmore** [comment]
Workaround until release is available:

Add a new module and import it instead of calling load('coreclr')

Module code:
```
try:
    is_loaded
except Exception:
    from pythonnet import load
    load('coreclr')
    is_loaded = True
```
