### ISSUE TITLE
Missing support for python 3.12

### ISSUE THREAD

**Issue by ItamarIn** [pythonnet/pythonnet#2160]
### Environment

-   Pythonnet version: 2.21
-   Python version: 3.12
-   Operating System: Windows
-   .NET Runtime:.NET 7.0
---------------------
SDK Version: 7.0.203

### Details

Can't install on python 3.12, maybe it's related to distutils? 
https://peps.python.org/pep-0632/

The command I ran:

```bash
    python -m pip install pythonnet
```

The crash:

```bash
    Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pycparser in c:\users\<user_name>\appdata\local\programs\python\python312\lib\site-packages (from pythonnet) (2.21)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py): started
  Building wheel for pythonnet (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [109 lines of output]
  C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\setup.py:468: SyntaxWarning: invalid escape sequence '\*'
    "MSBuild\**\Bin\MSBuild.exe",
  C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\setup.py:533: SyntaxWarning: invalid escape sequence '\*'
    "MSBuild\**\Bin\MSBuild.exe",
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 6.5.0.
  Update successful.
  Cannot find the specified version of msbuild: '14'
  MSBuild auto-detection: using msbuild version '17.4.1.60106' from 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin'.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.11.1.
  Restoring NuGet package System.ValueTuple.4.5.0.
  Restoring NuGet package NUnit.3.12.0.
  Adding package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Adding package 'NUnit.3.12.0' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Added package 'NUnit.ConsoleRunner.3.11.1' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'
  Added package 'NUnit.3.12.0' to folder 'C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\packages'

  NuGet Config files used:
      C:\Users\<user_name>\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\<user_name>\.nuget\packages\
      https://api.nuget.org/v3/index.json

  Installed:
      4 package(s) to packages.config projects
  Traceback (most recent call last):
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\tools\geninterop\geninterop.py", line 396, in <module>
      sys.exit(main())
               ^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\tools\geninterop\geninterop.py", line 357, in main
      python_h = preprocess_python_headers()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\tools\geninterop\geninterop.py", line 238, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
                  ^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\tools\geninterop\geninterop.py", line 46, in _check_output
      output = subprocess.check_output(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
      with Popen(*popenargs, **kwargs) as process:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1024, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1509, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\setup.py", line 630, in <module>
      setup(
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
      super().run_command(command)
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
      self.build_extensions()
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\<user_name>\AppData\Local\Temp\pip-install-wpa91g4r\pythonnet_815c9d0cc6b54f2bbc8c5a06eb35015c\setup.py", line 302, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\<user_name>\\AppData\\Local\\Programs\\Python\\Python312\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop312.cs']' returned non-zero exit status 1.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
ERROR: Could not build wheels for pythonnet, which is required to install pyproject.toml-based projects

```

**Comment by filmor** [comment]
We don't claim that anywhere. PRs are welcome, but I myself will work on this when the RCs are coming out.

**Comment by filmor** [comment]
Actually, Python.NET is not supported at all anymore, it doesn't even support Python 3.10 or 3.11.

**Comment by ItamarIn** [comment]
I just want to install pythonnet on python 3.12, it's doesn't matter which version.

**Comment by BinhPQ2** [comment]
Wait so how do you fix it?
