### ISSUE TITLE
ToString() on a custom Python object passed to .NET causes AccessViolationException

### ISSUE THREAD

**Issue by ZbynekZ** [pythonnet/pythonnet#2215]
### Environment

-   Pythonnet version: 2.5.2
-   Python version: 3.6.2
-   Operating System: Windows 11
-   .NET Runtime: 4.7.2

### Details

-   Describe what you were trying to get done.
My actual code was different, but resulted in calling ToString() inside my C# program on a custom Python object passed to it, and it crashed. The short program below ends up crashing as well, so I believe it would be enough to fix that. "ToString()" is called by many methods in .NET quite frequently (e.g. as part of tracing), so to me it is relatively serious problem, because one cannot prevent ToString() from being called, easily.

```python
import clr
import sys

class CustomObject(object):
    def __init__(self, name):
        self.name = name

from System import *
customObject = CustomObject('Test')
String.Format("[{0}]", customObject)
```

-   If there was a crash, please include the traceback here.

```python
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyObject_Unicode(IntPtr pointer)
   at Python.Runtime.PyObject.ToString()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Python.Runtime.MethodBinder.Invoke(IntPtr inst, IntPtr args, IntPtr kw, MethodBase info, MethodInfo[] methodinfo)
   at Python.Runtime.MethodObject.Invoke(IntPtr target, IntPtr args, IntPtr kw, MethodBase info)
   at Python.Runtime.MethodBinding.tp_call(IntPtr ob, IntPtr args, IntPtr kw)

Process finished with exit code -532462766
```

**Comment by lostmsu** [comment]
This is already fixed in 3.0.0
