### ISSUE TITLE
RGiesecke.DllExport.Metadata not found when trying to import DLL

### ISSUE THREAD

**Issue by josemariagarcia95** [pythonnet/pythonnet#2252]
### Environment

- Pythonnet version: 3.0.2
- Python version: 3.11.5
- Operating System: Windows 11
- .NET Runtime: 4.8.09032

### Details

-   I'm trying to import a DLL I was given by my company to use its functions in Python. I was also given a basic a script to import said DLL and access its functions:

```python
import clr
clr.AddReference(R'C:\Users\XXXXX\Documents\XXXXX\XXXXX.dll')
from OwnedPackage.Compression import QuickLZ

QuickLZ.compression()
```

However, after inspecting QuickLZ with dir, I discover that the imported object only contains "default" functions such as Equals, GetType, etc. 

```python
dir(QuickLZ)
['Equals',
 'Finalize',
 'GetHashCode',
 'GetType',
 'MemberwiseClone',
 'Overloads',
 'ReferenceEquals',
 'ToString',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
```

Suspecting it might have something to do with the fact that said script was done for pythonnet 2.3.0, I tweaked it a bit using the documentarion:

```python
from pythonnet import load
load('netfx')
import clr
clr.AddReference(R'C:\Users\XXXXX\Documents\XXXXX\XXXXX.dll')

from OwnedPackage.Compression import QuickLZ
```
Now the import fails, giving me an error that says that `RGiesecke.DllExport.Metadata` wasn't found **(see below).**

-   What commands did you run to trigger this issue? If you can provide a
```python
import clr
clr.AddReference(R'C:\Users\XXXXX\Documents\XXXXX\XXXXX.dll')
from OwnedPackage.Compression import QuickLZ

QuickLZ.compression()
```

-   If there was a crash, please include the traceback here.

```python
Traceback (most recent call last):
  File "C:\Users\XXXXX\Documents\XXXXXX\prueba.py", line 6, in <module>
    from OwnedPackage.Compression import QuickLZ
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'RGiesecke.DllExport.Metadata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8f52d83c1a22df51' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
Nombre de archivo: 'RGiesecke.DllExport.Metadata, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8f52d83c1a22df51'
   en System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)  
   en System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   en System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   en System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   en System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   en System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   en System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   en System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   en System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element, Boolean inherit)
   en Python.Runtime.MethodObject.AllowThreads(MethodBase[] methods)
   en Python.Runtime.ClassManager.GetClassInfo(Type type, ClassBase impl)
   en Python.Runtime.ClassManager.InitClassBase(Type type, ClassBase impl, ReflectedClrType pyType)
   en Python.Runtime.ReflectedClrType.GetOrCreate(Type type)
   en Python.Runtime.ModuleObject.GetAttribute(String name, Boolean guess)
   en Python.Runtime.ModuleObject.tp_getattro(BorrowedReference ob, BorrowedReference key)

AVS: El registro del enlace de ensamblado está desactivado.
Para habilitar el registro de errores del enlace de ensamblado, establezca el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) como 1.
Nota: existe una disminución del rendimiento asociada registro de errores del enlace de ensamblado.
Para desactivar esta característica, elimine el valor de Registro [HKLM\Software\Microsoft\Fusion!EnableLog].
```

I also run get_runtime_info() and got this:

```
Runtime: .NET Framework
=============
  Version:      <undefined>
  Initialized:  True
  Shut down:    False
  Properties:
    domain = 
    config_file = None
```

Could it be related? Maybe it's not finding my .NET Framework files, although they are in their default Windows location???

**Comment by filmor** [comment]
1. This is not a support forum. Please ask questions in the Q&A section on the Discussions pages or via the mailing list.
2. If your library relies on `RGiesecke.DllExport`, you'll need to link it directly. It's not included in Python.NET anymore as the dll-export is now performed through .NET-integrated methods. If you link `Python.Runtime` directly, you'll need to update it.

**Comment by josemariagarcia95** [comment]
Thanks @filmor, I'll repost it in the Q&A section.

How am I supposed to "link" RGiesecke.DllExport, may I ask? Is it a library I need to install? A dll I have to place in some folder? I'm still catching up on how to use these tools. Thanks in advance.
