### ISSUE TITLE
import clr throw RuntimeError

### ISSUE THREAD

**Issue by xiepu1212** [pythonnet/pythonnet#2264]
### Environment

-   Pythonnet version:  3.0.2
-   Python version:  3.9.5 AMD64
-   Operating System: windows 10 
-   .NET Runtime:

### Details

```python
    import clr
    print("ok")
```
I packaged it into exe using `pyinstaller -F test.py ` . The exe program runs normally on my local computer，but running on another PC will result in an error

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "clr.py", line 6, in <module>
  File "pythonnet\__init__.py", line 143, in load
  File "clr_loader\types.py", line 94, in get_function
  File "clr_loader\types.py", line 58, in __init__
  File "clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI470162\pythonnet\runtime\Python.Runtime.dll
[46276] Failed to execute script 'test' due to unhandled exception!

**Comment by xiepu1212** [comment]
When I use another environment, everything is normal

Pythonnet version: 2.5.2
Pythonnet version: 3.8.5

**Comment by filmor** [comment]
3.9 is not supported on pythonnet 2.5.
