### ISSUE TITLE
HELP... cannot get CLR to run on Linux server: RuntimeError: Failed to create a .NET runtime (coreclr) using the parameters {}.

### ISSUE THREAD

**Issue by Zahanh** [pythonnet/pythonnet#2328]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.10, 3.11, 3.12
-   Operating System: Linux (Ubuntu 22.04)
-   .NET Runtime: 8.0, 7.0, 6.0

### Details

-   I have a web app I am trying to deploy on AWS which uses .NET to communicate with a vendors API. I have tried a lot of different things, reordering calls, uninstalling and reinstalling, calling it separately, but I am just lost. I thought it was possibly environmental variable but it doesnt seem to be that either

    _TODO_

-  I just call pythonnet load() and use clr (which works locally on my windows 10 work PC but not on a linux server or my linux PC at home).

```python
import pandas as pd
import sqlite3 as sql
import json
from pythonnet import load
load('coreclr')
import clr

# Python .NET interface ----------------------------------------------------
sys.path.append('PLEXOS 10.0 API')
clr.AddReference('PLEXOS_NET.Core')
clr.AddReference('EEUTILITY')
clr.AddReference('EnergyExemplar.PLEXOS.Utility')


    RuntimeError: Failed to create a .NET runtime (coreclr) using the parameters {}.
```

-   If there was a crash, please include the traceback here.

```File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/home/ubuntu/Plexos-API-Test/Home.py", line 5, in <module>
    import src.getObjects
File "/home/ubuntu/Plexos-API-Test/src/getObjects.py", line 16, in <module>
    load("coreclr")
File "/home/ubuntu/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 135, in load
    set_runtime(runtime, **params)
File "/home/ubuntu/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 29, in set_runtime
    runtime = _create_runtime_from_spec(runtime, params)
File "/home/ubuntu/.local/lib/python3.10/site-packages/pythonnet/__init__.py", line 90, in _create_runtime_from_spec
    raise RuntimeError(
```

SEE UBUNTU dotnet --info
```
ubuntu@ip-172-31-29-48:~/Plexos-API-Test$ dotnet --info
You must install or update .NET to run this application.

App: /usr/share/dotnet/sdk/8.0.200/dotnet.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '8.0.2' (x64)
.NET location: /usr/share/dotnet/

No frameworks were found.

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.2&arch=x64&rid=linux-x64&os=ubuntu.22.04

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2
  RID:          linux-x64

.NET SDKs installed:
  6.0.419 [/usr/share/dotnet/sdk]
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by Zahanh** [comment]
I tried it on my linux PC, and found something interesting. the dotnet seems to be installed correctly on my personal PC but now it runs into an System.IS.FileNotFoundException....


```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'ADODB, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'ADODB, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.<get_Signature>g__LazyCreateSignature|25_0()
   at System.Reflection.RuntimeMethodInfo.ToString()
   at Python.Runtime.MaybeMethodBase`1..ctor(T mi) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/StateSerialization/MaybeMethodBase.cs:line 66
   at Python.Runtime.MaybeMethodBase`1.op_Implicit(T ob) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/StateSerialization/MaybeMethodBase.cs:line 25
   at Python.Runtime.MethodObject..ctor(MaybeType type, String name, MethodBase[] info, Boolean allow_threads) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/MethodObject.cs:line 38
   at Python.Runtime.MethodObject..ctor(MaybeType type, String name, MethodBase[] info) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/MethodObject.cs:line 49
   at Python.Runtime.ClassManager.GetClassInfo(Type type, ClassBase impl) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/ClassManager.cs:line 537
   at Python.Runtime.ClassManager.InitClassBase(Type type, ClassBase impl, ReflectedClrType pyType) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/ClassManager.cs:line 213
   at Python.Runtime.ReflectedClrType.GetOrCreate(Type type) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/ReflectedClrType.cs:line 43
   at Python.Runtime.ClassManager.GetClass(Type type) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/ClassManager.cs:line 136
   at Python.Runtime.ModuleObject.GetAttribute(String name, Boolean guess) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/ModuleObject.cs:line 130
   at Python.Runtime.ModuleObject.LoadNames() in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/ModuleObject.cs:line 193
   at Python.Runtime.ModuleObject.tp_getattro(BorrowedReference ob, BorrowedReference key) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/ModuleObject.cs:line 305
Aborted (core dumped)
```
