### ISSUE TITLE
Script not executing properly in embedded Python in .NET application

### ISSUE THREAD

**Issue by BlueprismWorld** [pythonnet/pythonnet#2352]
### Environment

-   Pythonnet version: 
-   Python version: 312
-   Operating System: Win 11
-   .NET Runtime: 4.7.2

### Details

-   Describe what you were trying to get 
I have created a WPF application, and I am calling Python code from it using the pythonnet library. When I run the application in Visual Studio in debug mode, it is executing the Python script perfectly; however, when I run my WPF .exe file, I get this error:

Error: 'NoneType' object has no attribute 'write'

This is my Python code:

import moviepy.editor
def merge_video():
 try:
  clip_1 = moviepy.editor.VideoFileClip(r"C:\Users\Naveen\Videos\20240308_225147.mp4") 
  clip_2 = moviepy.editor.VideoFileClip(r"C:\Users\Naveen\Videos\20240310_111656.mp4") 
  merged_video = moviepy.editor.concatenate_videoclips([clip_1, clip_2]) 
  output_path = r"C:\Users\Naveen\Videos\Output.mp4"
  merged_video.write_videofile(output_path, codec='mpeg4') 
  return "Done"
 except Exception as e:
  return f"Error: {str(e)}"

below is my .net code.

private void button1_Click(object sender, EventArgs e)
{
  Runtime.PythonDLL = _pythonDllPath;
  PythonEngine.Initialize();
  using (Py.GIL())
  {
   pythonScript = File.ReadAllText(pythonScript);
   using (var scope = Py.CreateScope())
   {
    var scriptCompiled = PythonEngine.Compile(pythonScript);
    scope.Execute(scriptCompiled);
    PyObject PyFunction = scope.Get(functionName);
    var res= PyFunction.Invoke();
    MessageBox.Show(res.AsManagedObject(string));
   }
  }
}
I need to use moviepy module to merge the videos into one file. The above python script is executing in my WPF app without any error through VS debug mode, but it is not executing directly from my WPF application.
![IMG_1366](https://github.com/pythonnet/pythonnet/assets/94820662/8126e2e9-cae8-4676-b188-069c814efaf1)

**Comment by BlueprismWorld** [comment]
here is traceback

Error: 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "", line 29, in merge_video
  File "<decorator-gen-55>", line 2, in write_videofile
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "<decorator-gen-54>", line 2, in write_videofile
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<decorator-gen-53>", line 2, in write_videofile
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\moviepy\video\VideoClip.py", line 291, in write_videofile
    logger(message="Moviepy - Building video %s." % filename)
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\proglog\proglog.py", line 257, in __call__
    self.callback(**kw)
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\proglog\proglog.py", line 350, in callback
    self.tqdm.write(kw['message'])
  File "C:\Users\Naveen\AppData\Roaming\Python\Python312\site-packages\tqdm\std.py", line 722, in write
    fp.write(s)
    ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by BlueprismWorld** [comment]
this is causing with progress bar after set logger to None working as expected (logger =None)

**Comment by lostmsu** [comment]
Next time be aware, that we require minimal repro's of an issue. If you can't narrow it down to a few lines of code without any external libraries or major dependencies the chances are the mistake is on your side.
