### ISSUE TITLE
Getting exception when calling PythonEngine.Initialize() second time after shutdown

### ISSUE THREAD

**Issue by BlueprismWorld** [pythonnet/pythonnet#2354]
### Environment

-   Pythonnet version: 3.1.0.0
-   Python version: 312
-   Operating System: Win11
-   .NET Runtime: 4.7.2

### Details

-   Describe what you were trying to get done.
    i am getting error while calling PythonEngine.Initialize() method after calling PythonEngine.Shutdown()

``` 
Error message : Value cannot be null. Parameter name: typeName
```

-   If there was a crash, please include the traceback here.

```
Internal : Could not execute code stage because exception thrown by code stage:    at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Python.Runtime.RuntimeData.RestoreRuntimeDataImpl()
   at Python.Runtime.RuntimeData.RestoreRuntimeData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Python_VBO_x64_v3_0.Init()
   
 Inner Exception: Value cannot be null. Parameter name: typeName
 Exception message: Exception has been thrown by the target of an invocation.
```

**Comment by filmor** [comment]
Version 3.1.0.0 doesn't exist. Which one are you using exactly? The current master branch?

**Comment by BlueprismWorld** [comment]
Yes from current master branch.

**Comment by alvahtin** [comment]
How can I solve this?

Even if I run:

PythonEngine.Initialize();
PythonEngine.Shutdown();
PythonEngine.Initialize();

The error occurs after the second call to Initialize.

**Comment by filmor** [comment]
Can you please provide a reproducible example?

**Comment by alvahtin** [comment]
This example above. You may run it, for example, in console application. I'm writing it again:

```
using Python.Runtime;

PythonEngine.Initialize();

PythonEngine.Shutdown();

PythonEngine.Initialize();

```

**Comment by nwoolls** [comment]
I'm getting the same thing. This seems to work with .NET 8. We have multiple unit tests that call `PythonEngine.Initialize();` followed by `PythonEngine.Shutdown();`. We are moving our libraries and tests to .NET 10 and 11. Changing the target framework to .NET 9 or higher now throws an exception when Initialize is called twice.

```
System.NotImplementedException
The method or operation is not implemented.
   at Python.Runtime.NoopFormatter.Deserialize(Stream s)
   at Python.Runtime.RuntimeData.RestoreRuntimeDataImpl()
   at Python.Runtime.RuntimeData.RestoreRuntimeData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
```

_**Edit**: this did not work in .NET 8, rather this seems to have been introduced in PythonNet 3.1.0. With 3.0.5, the error is instead about BinaryFormatter, which could be worked around in .NET 8._

**Comment by nwoolls** [comment]
Steps to reproduce:

```bash
mkdir spl-dotnet-pythonnet-multiple-init
cd spl-dotnet-pythonnet-multiple-init
dotnet new console
dotnet package add pythonnet
code .
```

Add the following to `Program.cs`:

```csharp
PythonEngine.Initialize();
PythonEngine.Shutdown();
PythonEngine.Initialize();
```

FInally:

```bash
dotnet run
Hello, World!
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Python.Runtime.NoopFormatter.Deserialize(Stream s)
   at Python.Runtime.RuntimeData.RestoreRuntimeDataImpl()
   at Python.Runtime.RuntimeData.RestoreRuntimeData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Program.<Main>$(String[] args) in /Users/nwoolls/src/dotnet/spl-dotnet-pythonnet-multiple-init/Program.cs:line 7
```

**Comment by nwoolls** [comment]
It seems like potentially `NoopFormatter` could be updated to implement `Deserialize()`:

```csharp
    public object Deserialize(Stream s)
    {
        return new PythonNetState();
    }
```

`PythonNetState` is currently internal so it doesn't seem we can do this with a custom formatter.

**Comment by nwoolls** [comment]
FWIW I tried the fix above and it does not work. The code to restore state assumes a lot about the `PythonNetState` payload.

That being said, if the authors do decide to tackle this, the following test case reproduces the issue:

```csharp
using NUnit.Framework;

using Python.Runtime;

namespace Python.EmbeddingTest.NeedsReinit;

internal sealed class TestNoopFormatter
{
    [System.ComponentModel.Category("NeedsReinit")]
    public class TestPyInitialize
    {
        [Test]
        public static void StartAndStopTwiceWithNoopFormatter()
        {
            RuntimeData.FormatterType = typeof(NoopFormatter);

            PythonEngine.Initialize();
            PythonEngine.Shutdown();

            PythonEngine.Initialize();
            PythonEngine.Shutdown();
        }
    }
}

```

**Comment by carlreinke** [comment]
I was able to work around this the [same way I did for `BinaryFormatter`](https://github.com/pythonnet/pythonnet/issues/2469#issuecomment-4173617697).
