### ISSUE TITLE
Signal.py error in Linux

### ISSUE THREAD

**Issue by joemaclean** [pythonnet/pythonnet#2361]
### Environment

-   Pythonnet version: 3.0.1
-   Python version: 3.11.8
-   Operating System: Rocky9, RHEL9, openSUSE
-   .NET Runtime: 8.0

### Details

-   Describe what you were trying to get done.

    While trying to interact with a third party tool through pythonnet on Linux, I encountered a signal.py error. I've been able to reproduce the error with a smaller python script in a .NET unit test. This test and the third party interaction work on Windows.

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.
    
    The basic unit test producing the same signal error is as follows:
```C#
	public void TestMethod1()
	{
		var pointer = PythonEngine.BeginAllowThreads();
		using (Py.GIL())
		{
			var pythonString = @"
import signal
import threading
if threading.current_thread() is threading.main_thread():
  original_sigint_handler = signal.getsignal(signal.SIGINT)
  signal.signal(signal.SIGINT, original_sigint_handler)";
			PythonEngine.Exec(pythonString);
		}
	}
```

NOTE: removing the `BeginAllowThreads()` call and `using` statement do not affect the result.

I'm setting the PYTHONNET_PYDLL, PYTHONHOME, and LD_LIBRARY_PATH environment variables, and all other python related testing has worked. This test throws the following error:

```text
Failed Test_Threading [61 ms]
 Error Message:
  Test method Utility.Tests.Python.PythonHelperTestCases.Test_Threading threw exception:  
Python.Runtime.PythonException: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
 Stack Trace:
    File "/opt/python-3.11.8/lib/python3.11/signal.py", line 58, in signal
   handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "<string>", line 6, in <module>
  at Python.Runtime.PythonException.ThrowLastAsClrException()
  at Python.Runtime.PythonException.ThrowIfIsNull(NewReference& ob)
  at Python.Runtime.PyModule.Exec(String code, BorrowedReference _globals, BorrowedReference _locals)
  at Python.Runtime.PyModule.Exec(String code, PyDict locals)
  at Utility.Tests.Python.PythonHelperTestCases.Test_Threading() in /home/adaptdev/dev/adapt.git/src/Utility.Tests/Utility.Tests.Python/Utility/PythonHelperTestCases.cs:line 71
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
  at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Failed!  - Failed:     1, Passed:   240, Skipped:     0, Total:   241, Duration: 10 s - Utility.Tests.dll (net8.0)
```

-   If there was a crash, please include the traceback here.

**Comment by joemaclean** [comment]
I was just informed calling signal.signal with signal.SIGINT is not valid on Linux. I will have to get more information.
