### ISSUE TITLE
Failed to load 'System.Windows.Forms.dll' on .net8

### ISSUE THREAD

**Issue by guyuanershi123** [pythonnet/pythonnet#2363]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.11
-   Operating System: windows
-   .NET Runtime: .net 8.0

### Details

```
>>> from pythonnet import load
>>> load("coreclr")
>>> import clr
>>> clr.FindAssembly('System.Windows.Forms')
'C:\\Program Files (x86)\\dotnet\\shared\\Microsoft.WindowsDesktop.App\\8.0.0\\System.Windows.Forms.dll'

>>> clr.AddReference('System.Windows.Forms')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
System.BadImageFormatException: Could not load file or assembly 'C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\System.Windows.Forms.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.0\System.Windows.Forms.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Python.Runtime.AssemblyManager.LoadAssemblyPath(String name) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/AssemblyManager.cs:line 238
   at Python.Runtime.CLRModule.AddReference(String name) in /tmp/build-via-sdist-h3j67_wc/pythonnet-3.0.3/src/runtime/Types/ClrModule.cs:line 105
   at InvokeStub_CLRModule.AddReference(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

```

**Comment by filmor** [comment]
This is not a support forum. The error is that the bitness of dotnet (32bit in your case) and Python (probably 64bit) doesn't match.
