### ISSUE TITLE
Initialization Error in .NET 8.0.4

### ISSUE THREAD

**Issue by oyindolapokomolafeTR** [pythonnet/pythonnet#2437]
### Environment

-   Pythonnet version: 3.03
-   Python version: 3.8, 3.11.4, 
-   Operating System: windows 11
-   .NET Runtime: 8.0.4

### Details
Trying to initialize python in .NET and getting errors
```
Environment.SetEnvironmentVariable("PYTHONHOME", @"C:\Program Files\Python38");
Environment.SetEnvironmentVariable("PYTHONNET_PYDLL", @"C:\Program Files\Python38\python38.dll");

PythonEngine.Initialize();
using (Py.GIL())
```
-   If there was a crash, please include the traceback here.

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Delegates' threw an exception.
  Source=Python.Runtime
  StackTrace:
   at Python.Runtime.Runtime.Delegates.get_Py_IsInitialized()
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.<>c.<Initialize>b__32_0()
   at Python.Runtime.Runtime.TryUsingDll[T](Func`1 op)
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
  

Inner Exception 1:
DllNotFoundException: Could not load C:\Program Files\Python38\python38.dll.

Inner Exception 2:
Win32Exception: %1 is not a valid Win32 application.

**Comment by filmor** [comment]
It tells you the error. Quite often this is because .NET likes to default to 32bit mode for some reason and the bitness of the runtime and the Python DLL have to fit.
