### ISSUE TITLE
Built application works on computer that built it, but not on another, possible .NET version mismatch?

### ISSUE THREAD

**Issue by tepiloxtl** [pythonnet/pythonnet#2521]
### Environment

-   Pythonnet version: 3.0.3
-   Python version: 3.11.8
-   Operating System: Windows 11/Windows Server 2016
-   .NET Runtime: 4.8

### Details

We use pythonnet in an aplication used on Windows Server. Since fairly recently (last update couple weeks ago works fine) building application on Windows 11 using nuitka and moving it to Windows Server 2016, application crashes. The same executable works fine on Windows 11. File `pythonnet\runtime\Python.Runtime.dll` exists within distributed directory. There's no Python installation on Windows Server 2016, hence I can't run script directly to test.

When running `reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full" /v version` on both machines I get slightly different results, Windows 11 seems to be newer version, but both machines are up to date with Windows Update

Windows Server 2016:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full
    version    REG_SZ    4.8.03761
```

Windows 11:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\full
    version    REG_SZ    4.8.09032
```

- Reproducible code:
```python
    import clr
```

-   If there was a crash, please include the traceback here.

```python
Traceback (most recent call last):
  File "C:\pdcom\Pliki\SCRIPT~1.DIS\script.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\pdcom\Pliki\SCRIPT~1.DIS\clr.py", line 6, in <module clr>
  File "C:\pdcom\Pliki\SCRIPT~1.DIS\pythonnet\__init__.py", line 143, in load
  File "C:\pdcom\Pliki\SCRIPT~1.DIS\clr_loader\types.py", line 94, in get_function
  File "C:\pdcom\Pliki\SCRIPT~1.DIS\clr_loader\types.py", line 58, in __init__
  File "C:\pdcom\Pliki\SCRIPT~1.DIS\clr_loader\netfx.py", line 47, in _get_callable
RuntimeError: Failed to resolve Python.Runtime.Loader.Initialize from C:\pdcom\Pliki\SCRIPT~1.DIS\pythonnet\runtime\Python.Runtime.dll
```

**Comment by filmor** [comment]
Python.NET is not compatible with Nuitka.

**Comment by tepiloxtl** [comment]
Found solution: Windows blocked the `pythonnet\runtime\Python.Runtime.dll` file from execution when moving. Go to that file, right click, go to properties, check Unlock and Apply
