### ISSUE TITLE
pythonnet 2.2.1 on linux fails in python 3.4 and 3.5 (but not 2.7) - pycparser error

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#336]
<details>
  <summary>anaconda python 3.5 (click to expand) </summary>

```
(root) dta@dta-Inspiron-N5050 ~ $ sudo /home/dta/anaconda3/bin/pip install pythonnet -U --force
The directory '/home/dta/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/dta/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pythonnet
  Downloading pythonnet-2.2.1.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 486kB/s 
Installing collected packages: pythonnet
  Found existing installation: pythonnet 2.2.0
    Uninstalling pythonnet-2.2.0:
      Successfully uninstalled pythonnet-2.2.0
  Running setup.py install for pythonnet ... error
    Complete output from command /home/dta/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2mxcht23/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xa22cnng-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 3.5.0.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
    Restoring NuGet package NUnit.2.6.2.
    Restoring NuGet package UnmanagedExports.1.2.7.
    Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-2mxcht23/pythonnet/packages'
    Adding package 'NUnit.2.6.2' to folder '/tmp/pip-build-2mxcht23/pythonnet/packages'
    Added package 'NUnit.2.6.2' to folder '/tmp/pip-build-2mxcht23/pythonnet/packages'
    Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-2mxcht23/pythonnet/packages'
    
    NuGet Config files used:
        /home/dta/.config/NuGet/NuGet.Config
    
    Feeds used:
        /home/dta/.nuget/packages/
        https://api.nuget.org/v3/index.json
    
    Installed:
        2 package(s) to packages.config projects
    clang: warning: /home/dta/anaconda3/include/python3.5m: 'linker' input unused
    Traceback (most recent call last):
      File "tools/geninterop/geninterop.py", line 296, in <module>
        sys.exit(main())
      File "tools/geninterop/geninterop.py", line 278, in main
        ast = parser.parse(python_h)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/c_parser.py", line 146, in parse
        debug=debuglevel)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 265, in parse
        return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
        tok = self.errorfunc(errtoken)
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/c_parser.py", line 1680, in p_error
        column=self.clex.find_tok_column(p)))
      File "/home/dta/anaconda3/lib/python3.5/site-packages/pycparser/plyparser.py", line 55, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: /usr/bin/../lib/clang/3.4/include/stdarg.h:30:27: before: va_list
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2mxcht23/pythonnet/setup.py", line 376, in <module>
        setup_requires=setup_requires
      File "/home/dta/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dta/anaconda3/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/home/dta/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/dta/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-2mxcht23/pythonnet/setup.py", line 182, in build_extension
        _check_output([sys.executable, geninterop, interop_file])
      File "/tmp/pip-build-2mxcht23/pythonnet/setup.py", line 299, in _check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['/home/dta/anaconda3/bin/python', 'tools/geninterop/geninterop.py', 'src/runtime/interop35m.cs']' returned non-zero exit status 1
    
    ----------------------------------------
  Rolling back uninstall of pythonnet
Command "/home/dta/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2mxcht23/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xa22cnng-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2mxcht23/pythonnet/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(root) dta@dta-Inspiron-N5050 ~ $ 
```
</details>

<details>
  <summary>system python 3.4 (click to expand) </summary>

```
dta@dta-Inspiron-N5050 ~ $ sudo pip3 install pythonnet -U --force
Downloading/unpacking pythonnet
  Downloading pythonnet-2.2.1.tar.gz (1.5MB): 1.5MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pythonnet/setup.py) egg_info for package pythonnet
    
Installing collected packages: pythonnet
  Found existing installation: pythonnet 2.2.0
    Can't uninstall 'pythonnet'. No files were found to uninstall.
  Running setup.py install for pythonnet
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 3.5.0.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
    Restoring NuGet package UnmanagedExports.1.2.7.
    Restoring NuGet package NUnit.2.6.2.
    Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip_build_root/pythonnet/packages'
    Adding package 'NUnit.2.6.2' to folder '/tmp/pip_build_root/pythonnet/packages'
    Added package 'NUnit.2.6.2' to folder '/tmp/pip_build_root/pythonnet/packages'
    Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip_build_root/pythonnet/packages'
    
    NuGet Config files used:
        /home/dta/.config/NuGet/NuGet.Config
    
    Feeds used:
        /home/dta/.nuget/packages/
        https://api.nuget.org/v3/index.json
    
    Installed:
        2 package(s) to packages.config projects
    clang: warning: /usr/include/python3.4m: 'linker' input unused
    Traceback (most recent call last):
      File "tools/geninterop/geninterop.py", line 296, in <module>
        sys.exit(main())
      File "tools/geninterop/geninterop.py", line 278, in main
        ast = parser.parse(python_h)
      File "/usr/local/lib/python3.4/dist-packages/pycparser/c_parser.py", line 151, in parse
        debug=debuglevel)
      File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 1181, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "/usr/local/lib/python3.4/dist-packages/pycparser/c_parser.py", line 1721, in p_error
        column=self.clex.find_tok_column(p)))
      File "/usr/local/lib/python3.4/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: /usr/bin/../lib/clang/3.4/include/stdarg.h:30:27: before: va_list
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/pythonnet/setup.py", line 376, in <module>
        setup_requires=setup_requires
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip_build_root/pythonnet/setup.py", line 182, in build_extension
        _check_output([sys.executable, geninterop, interop_file])
      File "/tmp/pip_build_root/pythonnet/setup.py", line 299, in _check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/geninterop/geninterop.py', 'src/runtime/interop34m.cs']' returned non-zero exit status 1
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ib7zyd1f-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

Checking for updates from https://www.nuget.org/api/v2/.

Currently running NuGet.exe 3.5.0.

NuGet.exe is up to date.

MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.

Restoring NuGet package UnmanagedExports.1.2.7.

Restoring NuGet package NUnit.2.6.2.

Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip_build_root/pythonnet/packages'

Adding package 'NUnit.2.6.2' to folder '/tmp/pip_build_root/pythonnet/packages'

Added package 'NUnit.2.6.2' to folder '/tmp/pip_build_root/pythonnet/packages'

Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip_build_root/pythonnet/packages'



NuGet Config files used:

    /home/dta/.config/NuGet/NuGet.Config



Feeds used:

    /home/dta/.nuget/packages/

    https://api.nuget.org/v3/index.json



Installed:

    2 package(s) to packages.config projects

clang: warning: /usr/include/python3.4m: 'linker' input unused

Traceback (most recent call last):

  File "tools/geninterop/geninterop.py", line 296, in <module>

    sys.exit(main())

  File "tools/geninterop/geninterop.py", line 278, in main

    ast = parser.parse(python_h)

  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_parser.py", line 151, in parse

    debug=debuglevel)

  File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 331, in parse

    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)

  File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 1181, in parseopt_notrack

    tok = call_errorfunc(self.errorfunc, errtoken, self)

  File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc

    r = errorfunc(token)

  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_parser.py", line 1721, in p_error

    column=self.clex.find_tok_column(p)))

  File "/usr/local/lib/python3.4/dist-packages/pycparser/plyparser.py", line 55, in _parse_error

    raise ParseError("%s: %s" % (coord, msg))

pycparser.plyparser.ParseError: /usr/bin/../lib/clang/3.4/include/stdarg.h:30:27: before: va_list

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/pythonnet/setup.py", line 376, in <module>

    setup_requires=setup_requires

  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/local/lib/python3.4/dist-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/lib/python3.4/distutils/command/install.py", line 583, in run

    self.run_command('build')

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/distutils/command/build.py", line 126, in run

    self.run_command(cmd_name)

  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 339, in run

    self.build_extensions()

  File "/usr/lib/python3.4/distutils/command/build_ext.py", line 448, in build_extensions

    self.build_extension(ext)

  File "/tmp/pip_build_root/pythonnet/setup.py", line 182, in build_extension

    _check_output([sys.executable, geninterop, interop_file])

  File "/tmp/pip_build_root/pythonnet/setup.py", line 299, in _check_output

    raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['/usr/bin/python3', 'tools/geninterop/geninterop.py', 'src/runtime/interop34m.cs']' returned non-zero exit status 1

----------------------------------------
  Can't roll back pythonnet; was not uninstalled
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ib7zyd1f-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pythonnet
Storing debug log for failure in /home/dta/.pip/pip.log
dta@dta-Inspiron-N5050 ~ $ 
```
</details>

**Comment by denfromufa** [comment]
Note that `sudo pip3 install pythonnet==2.1.0.dev1 --force` works.

Any idea @tonyroberts ?

**Comment by vmuriart** [comment]
I noticed that on 2.2.1 when I ran it on Travis. Python 2.7 works becoause it doesn't use the abi flags. Does Python 3 with sudo result with a different set of flags ?

**Comment by vmuriart** [comment]
Does it work if you do `pip3 install pythonnet==2.1.0.dev1 --user` ?

**Comment by denfromufa** [comment]
@vmuriart with `--user` it fails differently:
```
dta@dta-Inspiron-N5050 ~ $ pip3 install pythonnet==2.1.0.dev1 --user
Collecting pythonnet==2.1.0.dev1
  Using cached pythonnet-2.1.0.dev1.tar.gz
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /home/dta/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-by9ey_g2/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpsmptbru6pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  ﻿﻿Installing 'UnmanagedExports 1.2.6'.
  Installing 'NUnit 2.6.2'.
  Successfully installed 'NUnit 2.6.2'.
  Successfully installed 'UnmanagedExports 1.2.6'.
  XBuild Engine Version 12.0
  Mono, Version 4.2.4.0
  Copyright (C) 2005-2013 Various Mono authors
  /tmp/pip-build-by9ey_g2/pythonnet/pythonnet.sln:  warning : The project configuration for project 'clrmodule' corresponding to the solution configuration 'ReleaseMono|x64' was not found.
  XBuild Engine Version 12.0
  Mono, Version 4.2.4.0
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  runtime.cs(149): error CS1029: #error: 'You must define one of PYTHON23 to PYTHON34'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-by9ey_g2/pythonnet/setup.py", line 314, in <module>
      "install_data": PythonNET_InstallData,
    File "/home/dta/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dta/anaconda3/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/dta/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dta/anaconda3/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/dta/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 338, in run
      self.build_extensions()
    File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
      self._build_extensions_serial()
    File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-build-by9ey_g2/pythonnet/setup.py", line 162, in build_extension
      check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/home/dta/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON35,UCS4,MONO_LINUX,PYTHON_WITH_PYMALLOC" /p:PythonBuildDir=/tmp/pip-build-by9ey_g2/pythonnet/build/lib.linux-x86_64-3.5 /verbosity:minimal /t:Build' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/dta/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-by9ey_g2/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-h8e01m2p-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_ext
    ﻿﻿All packages listed in packages.config are already installed.
    XBuild Engine Version 12.0
    Mono, Version 4.2.4.0
    Copyright (C) 2005-2013 Various Mono authors
    /tmp/pip-build-by9ey_g2/pythonnet/pythonnet.sln:  warning : The project configuration for project 'clrmodule' corresponding to the solution configuration 'ReleaseMono|x64' was not found.
    XBuild Engine Version 12.0
    Mono, Version 4.2.4.0
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    runtime.cs(149): error CS1029: #error: 'You must define one of PYTHON23 to PYTHON34'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-by9ey_g2/pythonnet/setup.py", line 314, in <module>
        "install_data": PythonNET_InstallData,
      File "/home/dta/anaconda3/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dta/anaconda3/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/home/dta/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/dta/anaconda3/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/dta/anaconda3/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/home/dta/anaconda3/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-by9ey_g2/pythonnet/setup.py", line 162, in build_extension
        check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/home/dta/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON35,UCS4,MONO_LINUX,PYTHON_WITH_PYMALLOC" /p:PythonBuildDir=/tmp/pip-build-by9ey_g2/pythonnet/build/lib.linux-x86_64-3.5 /verbosity:minimal /t:Build' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/dta/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-by9ey_g2/pythonnet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-h8e01m2p-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-by9ey_g2/pythonnet/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
dta@dta-Inspiron-N5050 ~ $ 
```

**Comment by denfromufa** [comment]
@vmuriart looks like we are missing something in the source distribution, because installation works from master branch:

```
dta@dta-Inspiron-N5050 ~ $ sudo pip3 install git+https://github.com/pythonnet/pythonnet
Downloading/unpacking git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to /tmp/pip-oz23g9f4-build
  Running setup.py (path:/tmp/pip-oz23g9f4-build/setup.py) egg_info for package from git+https://github.com/pythonnet/pythonnet
    
Installing collected packages: pythonnet
  Found existing installation: pythonnet 2.2.0
    Can't uninstall 'pythonnet'. No files were found to uninstall.
  Running setup.py install for pythonnet
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 3.5.0.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
    Restoring NuGet package UnmanagedExports.1.2.7.
    Restoring NuGet package NUnit.2.6.2.
    Adding package 'NUnit.2.6.2' to folder '/tmp/pip-oz23g9f4-build/packages'
    Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-oz23g9f4-build/packages'
    Added package 'NUnit.2.6.2' to folder '/tmp/pip-oz23g9f4-build/packages'
    Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-oz23g9f4-build/packages'
    
    NuGet Config files used:
        /home/dta/.config/NuGet/NuGet.Config
    
    Feeds used:
        /home/dta/.nuget/packages/
        https://api.nuget.org/v3/index.json
    
    Installed:
        2 package(s) to packages.config projects
    clang: warning: /usr/include/python3.4m: 'linker' input unused
    XBuild Engine Version 12.0
    Mono, Version 4.2.4.0
    Copyright (C) 2005-2013 Various Mono authors
    XBuild Engine Version 12.0
    Mono, Version 4.2.4.0
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    runtime.cs(341,13): warning CS0162: Unreachable code detected
    runtime.cs(2060,16): warning CS0472: The result of comparing value type `System.IntPtr' with null is always `true'
    Configuration: ReleaseMono Platform: x64
    Configuration: ReleaseMono Platform: x64
    Configuration: Release Platform: x64
    assemblyinfo.cs(13,41): warning CS0618: `System.Security.Permissions.SecurityAction.RequestMinimum' is obsolete: `This requests should not be used'
    pythonconsole.cs(20,28): warning CS0219: The variable `a' is assigned but its value is never used
    building 'clr' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c src/monoclr/pynetinit.c -o build/temp.linux-x86_64-3.4/src/monoclr/pynetinit.o -D_REENTRANT -I/usr/lib/pkgconfig/../../include/mono-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c src/monoclr/clrmod.c -o build/temp.linux-x86_64-3.4/src/monoclr/clrmod.o -D_REENTRANT -I/usr/lib/pkgconfig/../../include/mono-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
    src/monoclr/clrmod.c:31:18: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     static PyObject *_initclr()
                      ^
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/src/monoclr/pynetinit.o build/temp.linux-x86_64-3.4/src/monoclr/clrmod.o -o build/lib.linux-x86_64-3.4/clr.cpython-34m.so -L/usr/lib/pkgconfig/../../lib -lmono-2.0 -lm -lrt -ldl -lpthread -lglib-2.0
    
  Could not find .egg-info directory in install record for pythonnet==2.2.1 from git+https://github.com/pythonnet/pythonnet
Successfully installed pythonnet
Cleaning up...
```

**Comment by denfromufa** [comment]
@vmuriart we need to include fake c libs from geninterop folder:

https://github.com/pythonnet/pythonnet/tree/master/tools/geninterop/fake_libc_include

This is explained in more details here:

https://github.com/eliben/pycparser/issues/162

**Comment by vmuriart** [comment]
Good catch. We may need to release `2.2.2` w this.

**Comment by denfromufa** [comment]
i like 2.2.2, i had 66666 emails in my inbox today.

**Comment by stonebig** [comment]
housekeeping request: update the milestone page of github https://github.com/pythonnet/pythonnet/milestones

**Comment by vmuriart** [comment]
@stonebig done. thank you for the reminder
