### ISSUE TITLE
using geninterop.py on Windows

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#394]
@tonyroberts were you able to use geinterop.py on Windows?

If yes, how did you provide fake headers to pycparser? Here is a typical problem I'm getting when re-generating interopXX.cs files:

```
pycparser.plyparser.ParseError: C://Users//denis//AppData//Local//Programs//Common//Microsoft//Visual C++ for Python//9.0//WinSDK//Include//basetsd.h:357:1: before: PtrToPtr64
```

```
(py27) c:\Python\pythonnet>python setup.py bdist_wheel
running bdist_wheel
running build
running build_ext
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 3.5.0.
NuGet.exe is up to date.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
All packages listed in packages.config are already installed.
clang.exe: warning: C:\Python\Anaconda3_64b\envs\py27\Include: 'linker' input unused
Traceback (most recent call last):
  File "tools\geninterop\geninterop.py", line 292, in <module>
    sys.exit(main())
  File "tools\geninterop\geninterop.py", line 274, in main
    ast = parser.parse(python_h)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\site-packages\pycparser\c_parser.py", line 146, in parse
    debug=debuglevel)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\site-packages\pycparser\ply\yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\site-packages\pycparser\ply\yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\site-packages\pycparser\c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "C:\Python\Anaconda3_64b\envs\py27\lib\site-packages\pycparser\plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: C://Users//denis//AppData//Local//Programs//Common//Microsoft//Visual C++ for Python//9.0//WinSDK//Include//basetsd.h:357:1: before: PtrToPtr64
Traceback (most recent call last):
  File "setup.py", line 408, in <module>
    zip_safe=False,
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python\Anaconda3_64b\envs\py27\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\command\build.py", line 127, in run
    self.run_command(cmd_name)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Python\Anaconda3_64b\envs\py27\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 194, in build_extension
    subprocess.check_call([sys.executable, geninterop, interop_file])
  File "C:\Python\Anaconda3_64b\envs\py27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python\\Anaconda3_64b\\envs\\py27\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop27.cs']' returned non-zero exit status 1
```

**Comment by denfromufa** [comment]
this is outdated
