### ISSUE TITLE
setup.py build with mono in XUbuntu can't load System.Core (NuGet?)

### ISSUE THREAD

**Issue by theresa-anne** [pythonnet/pythonnet#411]
### Environment

-   Pythonnet version: build from source
-   Python version: 2.7 in 64-bit Anaconda
-   Operating System: Linux (XUbuntu) 64-bit

### Details

I am getting started with Python for .NET in mono on XUbuntu, all 64-bit, in VirtualBox. I installed 64-bit Anaconda2, and unzipped the Python for .NET source materials into the Anaconda bin folder. Note that mono was not built using "brew" (I first discovered that here, and could give it a try). The environment can't load System.Core, and the error report mentions NuGet. I'm a bit of a novice to this community, so I come on bended knee - please feel free to point me to an older thread if necessary. I did search, and did not find what I thought I needed, but things that seem obvious to others may be a learning curve for me. Thanks. - T

-   I simply created a 64-bit Ubuntu Virtual Box, installed XUbuntu, Anaconda, and mono (no "brew").
-   Then downloaded the zip file with source code and followed the straightforward build instructions 
from GitHub. Not worried about NPython.exe just yet, just willing to import clr and reference assemblies
as necessary. Any and all help appreciated.

Someone mentioned to me that the OS installs certain Python libraries for its own use and that virtual environments with select libraries are the preferred method. If that's the case, then can someone share their experience with using selected libraries to install Python for .NET, i.e. which libraries you used and which libraries you avoided, if relevant? Thank you so much.

**Comment by vmuriart** [comment]
@theresa-anne which build instructions? Our documentation isn't very updated, so it not be correct.

**Comment by theresa-anne** [comment]
python setup.py build_ext --inplace

**Comment by vmuriart** [comment]
try `python setup.py install` it takes care of placing everything where it needs to be (ie, avoids copy and paste stuff).

Did the install complete (regardless of which setup.py command you used)?

**Comment by theresa-anne** [comment]
I don't think so, it exited with a trace report, but I soon discovered that I had exceeded my allocated disk space and had to start over with Virtual Box. Give me some time to try again.

**Comment by denfromufa** [comment]
Brew is only for OSX. Please share your terminal session for full installation steps, e.g. using asciinema.
Look at travis.yml for all prerequisites. pip install pythonnet with sudo is your safest bet, after all prerequisites are installed.

**Comment by theresa-anne** [comment]
Here's the latest attempt:

1. Create a new XUbuntu guest in Virtual Box
2. Install Guest Additions
3. sudo apt install mono-runtime
4. bash Anaconda2-4.3.0-Linux-x86_64.sh
5. cd to the Anaconda2 bin directory (home/user....)

This time I went to the wiki (could not find "travis.yml") and followed the first step of the Anaconda instructions from the wiki...

VirtualBox:~/anaconda2/bin$ pip install -i https://pypi.anaconda.org/pythonnet/simple pythonnet
Collecting pythonnet
  Downloading https://pypi.anaconda.org/pythonnet/simple/pythonnet/2.2.2/pythonnet-2.2.2.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 112kB/s 
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /home/krebst/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cTGPAM/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmprlxFZjpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  
  Unhandled Exception:
  System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
  File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at NuGet.CommandLine.Program.Main (System.String[] args) <0x40e87d50 + 0x00023> in <filename unknown>:0
  [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
  File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    at NuGet.CommandLine.Program.Main (System.String[] args) <0x40e87d50 + 0x00023> in <filename unknown>:0
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-cTGPAM/pythonnet/setup.py", line 376, in <module>
      setup_requires=setup_requires
    File "/home/krebst/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/krebst/anaconda2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-build-cTGPAM/pythonnet/setup.py", line 129, in build_extension
      self._install_packages()
    File "/tmp/pip-build-cTGPAM/pythonnet/setup.py", line 246, in _install_packages
      check_call(cmd, shell=use_shell)
    File "/home/krebst/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/krebst/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cTGPAM/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5E3ZxQ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    
    Unhandled Exception:
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
    File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
      at NuGet.CommandLine.Program.Main (System.String[] args) <0x401d1d50 + 0x00023> in <filename unknown>:0
    [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
    File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
      at NuGet.CommandLine.Program.Main (System.String[] args) <0x401d1d50 + 0x00023> in <filename unknown>:0
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cTGPAM/pythonnet/setup.py", line 376, in <module>
        setup_requires=setup_requires
      File "/home/krebst/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/krebst/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-cTGPAM/pythonnet/setup.py", line 129, in build_extension
        self._install_packages()
      File "/tmp/pip-build-cTGPAM/pythonnet/setup.py", line 246, in _install_packages
        check_call(cmd, shell=use_shell)
      File "/home/krebst/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/krebst/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-cTGPAM/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5E3ZxQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-cTGPAM/pythonnet/

**Comment by denfromufa** [comment]
Can you install mono-complete? I'm afraid mono-runtime is not enough.

**Comment by theresa-anne** [comment]
It seems to be working, but setup is taking an extremely long time to run. I'll follow up late tonight or first thing tomorrow morning to confirm it solved. Thanks for your help! Worked.

**Comment by denfromufa** [comment]
Closing, let us know if you find any issues

**Comment by theresa-anne** [comment]
reopening with one last request for feedback. Here's the latest after installing mono-complete:

** I don't recall the mono install asking me for permission to update my PATH. Could this be the issue? 

krebst@krebst-VirtualBox:~/anaconda2/bin$ pip install -i https://pypi.anaconda.org/pythonnet/simple pythonnet
Collecting pythonnet
  Downloading https://pypi.anaconda.org/pythonnet/simple/pythonnet/2.2.2/pythonnet-2.2.2.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 239kB/s 
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /home/krebst/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-FdOQqR/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp9tX0eepip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  NuGet.exe is up to date.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
  Restoring NuGet package NUnit.2.6.2.
  Restoring NuGet package UnmanagedExports.1.2.7.
    GET https://api.nuget.org/v3-flatcontainer/nunit/2.6.2/nunit.2.6.2.nupkg
    GET https://api.nuget.org/v3-flatcontainer/unmanagedexports/1.2.7/unmanagedexports.1.2.7.nupkg
    OK https://api.nuget.org/v3-flatcontainer/nunit/2.6.2/nunit.2.6.2.nupkg 277ms
  Installing NUnit 2.6.2.
    OK https://api.nuget.org/v3-flatcontainer/unmanagedexports/1.2.7/unmanagedexports.1.2.7.nupkg 542ms
  Installing UnmanagedExports 1.2.7.
  Adding package 'NUnit.2.6.2' to folder '/tmp/pip-build-FdOQqR/pythonnet/packages'
  Added package 'NUnit.2.6.2' to folder '/tmp/pip-build-FdOQqR/pythonnet/packages'
  Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-FdOQqR/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-FdOQqR/pythonnet/packages'
  
  NuGet Config files used:
      /home/krebst/.config/NuGet/NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
  
  Installed:
      2 package(s) to packages.config projects
  XBuild Engine Version 12.0
  Mono, Version 4.2.1.0
  Copyright (C) 2005-2013 Various Mono authors
  XBuild Engine Version 12.0
  Mono, Version 4.2.1.0
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  	Configuration: ReleaseMono Platform: x64
  CSC: error CS0518: The predefined type `System.Object' is not defined or imported
  CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
  CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
  CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
  CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
  CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
  CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
  CSC: error CS0518: The predefined type `System.Single' is not defined or imported
  CSC: error CS0518: The predefined type `System.Double' is not defined or imported
  CSC: error CS0518: The predefined type `System.Char' is not defined or imported
  CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
  CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
  CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
  CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
  CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
  CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
  CSC: error CS0518: The predefined type `System.String' is not defined or imported
  CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
  CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
  CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
  CSC: error CS0518: The predefined type `System.Void' is not defined or imported
  CSC: error CS0518: The predefined type `System.Array' is not defined or imported
  CSC: error CS0518: The predefined type `System.Type' is not defined or imported
  CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
  CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
  CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
  CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
  CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
  CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
  CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
  CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
  Configuration: ReleaseMono Platform: x64
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-FdOQqR/pythonnet/setup.py", line 376, in <module>
      setup_requires=setup_requires
    File "/home/krebst/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/krebst/anaconda2/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-build-FdOQqR/pythonnet/setup.py", line 202, in build_extension
      check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/home/krebst/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS4,MONO_LINUX" /p:PythonBuildDir="/tmp/pip-build-FdOQqR/pythonnet/build/lib.linux-x86_64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/krebst/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-FdOQqR/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Zh59mb-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 3.5.0.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
    All packages listed in packages.config are already installed.
    XBuild Engine Version 12.0
    Mono, Version 4.2.1.0
    Copyright (C) 2005-2013 Various Mono authors
    XBuild Engine Version 12.0
    Mono, Version 4.2.1.0
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    	Configuration: ReleaseMono Platform: x64
    CSC: error CS0518: The predefined type `System.Object' is not defined or imported
    CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
    CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
    CSC: error CS0518: The predefined type `System.Single' is not defined or imported
    CSC: error CS0518: The predefined type `System.Double' is not defined or imported
    CSC: error CS0518: The predefined type `System.Char' is not defined or imported
    CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
    CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
    CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
    CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
    CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
    CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
    CSC: error CS0518: The predefined type `System.String' is not defined or imported
    CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
    CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
    CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
    CSC: error CS0518: The predefined type `System.Void' is not defined or imported
    CSC: error CS0518: The predefined type `System.Array' is not defined or imported
    CSC: error CS0518: The predefined type `System.Type' is not defined or imported
    CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
    CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
    CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
    CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
    CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
    CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
    CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
    CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
    Configuration: ReleaseMono Platform: x64
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FdOQqR/pythonnet/setup.py", line 376, in <module>
        setup_requires=setup_requires
      File "/home/krebst/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/krebst/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/krebst/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/krebst/anaconda2/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "/tmp/pip-build-FdOQqR/pythonnet/setup.py", line 202, in build_extension
        check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/home/krebst/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS4,MONO_LINUX" /p:PythonBuildDir="/tmp/pip-build-FdOQqR/pythonnet/build/lib.linux-x86_64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/krebst/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-FdOQqR/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Zh59mb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-FdOQqR/pythonnet/
krebst@krebst-VirtualBox:~/anaconda2/bin$

**Comment by denfromufa** [comment]
you are using Mono Version 4.2.1.0 from 2013-2015. Look at installation guide for later mono versions:

http://www.mono-project.com/docs/getting-started/install/linux/

alternatively you can try our docker images:

https://github.com/pythonnet/pythonnet/issues/322

**Comment by denfromufa** [comment]
related resolved issue with the same error:

https://github.com/pythonnet/pythonnet/issues/209

**Comment by denfromufa** [comment]
@theresa-anne I'm closing this issue due to inactivity. feel free to report back.
