### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hanschoi86** [pythonnet/pythonnet#512]
### Environment

-   Pythonnet version: Latest
-   Python version: 2.7
-   Operating System: Windows 10

### Details

-  I'm trying to install pythonnet. Due to company's security policy, I cannot use pip install, so I download the zip file from Github first and use "python -m pip install setupdir/" to install it. When I do that, I get these errors. 

Processing c:\users\downloads\pythonnet-master\pythonnet-master
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command C:\Users\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\windows\\temp\\1\\pip-hbdqxf-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\windows\temp\1\tmpzgeixcpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  The operation has timed out
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\windows\temp\1\pip-hbdqxf-build\setup.py", line 408, in <module>
      zip_safe=False,
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\site-packages\wheel\bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "c:\windows\temp\1\pip-hbdqxf-build\setup.py", line 142, in build_extension
      self._install_packages()
    File "c:\windows\temp\1\pip-hbdqxf-build\setup.py", line 272, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'tools\nuget\nuget.exe update -self' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command C:\Users\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\windows\\temp\\1\\pip-hbdqxf-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\windows\temp\1\pip-crcfgo-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    The operation has timed out
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\windows\temp\1\pip-hbdqxf-build\setup.py", line 408, in <module>
        zip_safe=False,
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\setuptools\command\install.py", line 61, in run
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self.build_extension(ext)
      File "c:\windows\temp\1\pip-hbdqxf-build\setup.py", line 142, in build_extension
        self._install_packages()
      File "c:\windows\temp\1\pip-hbdqxf-build\setup.py", line 272, in _install_packages
        subprocess.check_call(cmd, shell=use_shell)
      File "C:\Users\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'tools\nuget\nuget.exe update -self' returned non-zero exit status 1

    ----------------------------------------
Command "C:\Users\AppData\Local\Continuum\Anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\windows\\temp\\1\\pip-hbdqxf-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\windows\temp\1\pip-crcfgo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\windows\temp\1\pip-hbdqxf-build\

Could anyone please shed some lights on this?

Thanks a ton!

**Comment by denfromufa** [comment]
@hanschoi86 can't you download the wheels from PYPI and install using pip:

https://pypi.python.org/packages/4f/28/e5bed7fe232d46c62bc64027071bc9f525ef1fd30dcd6fa1031891079b1b/pythonnet-2.3.0-cp27-cp27m-win32.whl#md5=87b71edbd171166aca1427e4e51a70f7

https://pypi.python.org/packages/c1/b8/75db859015c25cbf843b9e43a6a4802684e18df0c8ef925f3aa0065d1173/pythonnet-2.3.0-cp27-cp27m-win_amd64.whl#md5=63333254d80b5c99e840181f5f05f4ba

pip install wheel_name.whl

nuget timeouts on your machine when you attempt to build from source.

**Comment by denfromufa** [comment]
closed, no feedback

**Comment by teejay-87** [comment]
I encounter the same problem, but the wheel for python 3.7 seems not to exist on PyPI.

https://pypi.org/project/pythonnet/#files

**Comment by denfromufa** [comment]
Temporarily you can get python 3.7 wheels from appveyor CI artifacts (builds)

**Comment by teejay-87** [comment]
It just outputs:
```
Processing c:\users\...\downloads\pythonnet-2.4.0rc2-cp37-cp37m-win32.whl
Installing collected packages: pythonnet
Successfully installed pythonnet-2.4.0rc2
```
instead of ten of lines output by `pip install pythonnet`. Is that ok?

**Comment by filmor** [comment]
It does exist, it's just a prerelease and thus needs to be downloaded explicitly using `pip install pythonnet==2.4.0rc2`, see https://pypi.org/project/pythonnet/2.4.0rc2/#files.
