### ISSUE TITLE
Not possible to develop scripts using pythonnet __namespace__ attribute in Spyder 3

### ISSUE THREAD

**Issue by testrunner123** [pythonnet/pythonnet#520]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.5.3 32-bit/64/bit
-   Operating System: Windows 7 Pro SP1 32-bit/64-bit

### Details

-   Describe what you were trying to get done.

I want to develop python class using .NET base class in Spyder 3. I can only once use "Run" in Spyder. On next attemp TypeError comes. 

Python interpreter is started once by Spyder and runs continuously. Each time user pushes "Run" button the script is executed. This employs python basic concept that you can redefine any python native class any time. But pythonnet breaks this. I believe it is a bug, because if I comment "__namespace__" attribute in my class definitions than it works. 

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

[test3.zip](https://github.com/pythonnet/pythonnet/files/1199582/test3.zip)
1. start cc.bat in Visual Studio 2015 prompt to compile class.dll (or use attached one)
2. start Spyder 3
3. open test3.py in Spyder
4. push "run"
5. push "run" again

Console outputs in Spyder after 2nd execution looks like:
```
Python 3.5.3 |Continuum Analytics, Inc.| (default, Feb 22 2017, 21:49:24) [MSC v.1900 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

runfile('D:/temp/1/test3.py', wdir='D:/temp/1')
Hello

runfile('D:/temp/1/test3.py', wdir='D:/temp/1')
Reloaded modules: Axa.Core.Prototype, Axa.Core, Axa, CLR, clr
Traceback (most recent call last):

  File "<ipython-input-2-a72cc270f94b>", line 1, in <module>
    runfile('D:/temp/1/test3.py', wdir='D:/temp/1')

  File "C:\Miniconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Miniconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/temp/1/test3.py", line 8, in <module>
    class MyClass(Prototype.IProcessControl):

TypeError: Duplicate type name within an assembly.
```

**Comment by testrunner123** [comment]
Following sample works in Python:
```Python
class MyClass():
    def method1(self):
        print("method1")

i = MyClass()
print("Call i.method1:")
i.method1()

class MyClass():
    def method1(self):
        print("method1 new")

print("Call i.method1:")
i.method1()

j = MyClass()
print("Call newmethod1:")
j.method1()
```
But similar sample with pythonnet class brings error "TypeError: Duplicate type name within an assembly.":
```Python
import os
import clr

clr.AddReference(os.path.join(os.getcwd(),"class.dll"))

import Axa.Core.Prototype as Prototype

class MyClass(Prototype.IProcessControl):
    __namespace__ = "Axa.Core.Prototype"
    def __init__(self, back = None):
        if back != None: self._back = back
    def method1(self):
        print("method1")

i = MyClass()
print("Call method1:")
i.method1()

class MyClass(Prototype.IProcessControl):
    __namespace__ = "Axa.Core.Prototype"
    def __init__(self, back = None):
        if back != None: self._back = back
    def method1(self):
        print("new method1")

j = MyClass()
print("Call new method1:")
j.method1()
```

I found that problem is much deeper: Python class name resolution is implemented incorrect in pythonnet. Python is dynamic weak typed language, but pythonnet implementation doesn't support this. 

The implementation can be corrected by creating types in ClassDerivedObject::CreateDerivedType() with anonym name like TYPE0001, ... and modifying binder function to recognize current mapping between MyClass <-> TYPExxxx. The next call of ClassDerivedObject::CreateDerivedType() for same class will create another TYPExxxx and change mapping.

**Comment by denfromufa** [comment]
To be fair to Python - it is NOT weakly typed, but strongly typed dynamic language. With Python 3 this is getting even better. Your use case seems valid, pull requests are welcome!

**Comment by dijital20** [comment]
I have currently run aground on this too. I can't share code due to the proprietary nature of what I am working with, but I have a class that loads an assembly, and gets an interface from that assembly. It then defines an inner class inheriting from that interface, and instantiates it for use. The python class is garbage collected when it is no longer used, but as long as I run in the same process space, I get the error when I try to initialize the initial class again, at the point where the inner class is defined.

Is there any way to get the current mapped type (the python class that was implemented as a subclass of the .Net interface or class) by either namespace name or by interface?

**Comment by dijital20** [comment]
I forgot to follow up on this, in case anyone else runs into this. I have found that the following pattern works well for the situation I described above:

```python
def _get_derivative_class() -> type:
    # 1. Try to import the class. If it already exists, you've probably already created it once, so you can use it.
    try:
        from My.Namespace import MyDerivativeClass  # <-- Import the inner class (if it exists)
      
    # 2. If we get an ImportError, then the derivative class hasn't been built. Build it. Make sure to set the
    #    __namespace__ so that it is created with the appropriate .Net namespace.
    except ImportError:
        from My.App.Namespace import IMyInterface  # <-- Import the interface

        class MyDerivativeClass(IMyInterface):
            """Implements IMyInterface"""

            __namespace__ = "My.Namespace"  # <-- sets the .Net namespace

            def MyMethod(self):
                pass

    # 3. Return the class. If this fails, don't try to catch it, just go.
    return MyDerivativeClass
```

**Comment by cdfarrow** [comment]
Thanks @dijital20 for the workaround. I've got the same thing happening in my application that runs user scripts.
