### ISSUE TITLE
Failed building wheel

### ISSUE THREAD

**Issue by CodeProQuo** [pythonnet/pythonnet#562]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 2.7.10
-   Operating System: macOS Sierra 10.12.6

### Details

-   I'm trying to install pythonnet on my mac. I have pretty much the same issue as #269, I even tried the solutions suggested there but they didn't work.

-   I ran the Pypi installation command in my terminal

```
pip install pythonnet
```

-   This is the output for the command:
```Collecting pythonnet
  Using cached pythonnet-2.3.0.tar.gz
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/tmpN575Xspip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.3.0.
  Update successful.
  MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/'.
  Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.3.6.0.
  Adding package 'NUnit.3.6.0' to folder '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/packages'
  Adding package 'UnmanagedExports.1.2.7' to folder '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/packages'
  Adding package 'NUnit.ConsoleRunner.3.6.0' to folder '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/packages'
  Added package 'NUnit.ConsoleRunner.3.6.0' to folder '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/packages'
  Added package 'NUnit.3.6.0' to folder '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/packages'
  
  NuGet Config files used:
      /Users/Daan/.config/NuGet/NuGet.Config
  
  Feeds used:
      /Users/Daan/.nuget/packages/
      https://api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.4.0.0
  Copyright (C) 2005-2013 Various Mono authors
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.4.0.0
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  /private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py", line 405, in <module>
      zip_safe=False,
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Library/Python/2.7/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
      self.build_extensions()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
      self.build_extension(ext)
    File "/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py", line 222, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS2,MONO_OSX,PYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/build/lib.macosx-10.12-intel-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-s90sjL-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.3.0.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/'.
    All packages listed in packages.config are already installed.
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.4.0.0
    Copyright (C) 2005-2013 Various Mono authors
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.4.0.0
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    /private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py", line 405, in <module>
        zip_safe=False,
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
        self.build_extension(ext)
      File "/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py", line 222, in build_extension
        subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON27,PYTHON2,UCS2,MONO_OSX,PYTHON_WITHOUT_ENABLE_SHARED" /p:PythonBuildDir="/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/build/lib.macosx-10.12-intel-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-s90sjL-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/
```
- And running the command
```
/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-s90sjL-record/install-record.txt --single-version-externally-managed --compile
```
gets me
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-build-4ndxpN/pythonnet/setup.py'
```

**Comment by denfromufa** [comment]
please follow instruction for mac here:

https://github.com/pythonnet/pythonnet/issues/465

You probably need to install from master branch:

https://github.com/pythonnet/pythonnet/wiki/Installation

**Comment by CodeProQuo** [comment]
I tried installing from master but I got the same error:
```
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to /private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-x_bOjR-build
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /Users/Daan/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-x_bOjR-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-2i8JyC-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/Users/Daan/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-x_bOjR-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-2i8JyC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x8/j3mhghcd7nxc9y88z64czp1r0000gp/T/pip-x_bOjR-build/
```

As for following the instructions in #465, which python points to the anaconda libraries but I can't find clr.so

**Comment by dmitriyse** [comment]
This is generic python problem. Try to follow this like threads https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind

**Comment by dmitriyse** [comment]
```bash
pip install pip --upgrade
pip install setuptools --upgrade 
```

Should solve this issue

**Comment by hjaekel** [comment]
We try to install pythonnet on Linux and upgrading pip and setuptools does not help:

```bash
$ pip install --upgrade pip setuptools
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
Downloading/unpacking setuptools from https://pypi.python.org/packages/bd/4c/b06ab3abfc8bc93b87b70f4cab22352c3c72deba7b71390d14bfffa97c85/setuptools-36.6.0-py2.py3-none-any.whl#md5=df531523e300bc3e6b9ce4451681912c
Installing collected packages: pip, setuptools
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip setuptools
Cleaning up...

$ python --version
Python 2.7.6

$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

$ pip show setuptools
Name: setuptools
Version: 36.6.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires:

$ pip install git+https://github.com/pythonnet/pythonnet
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to /tmp/pip-zf7XdG-build
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-zf7XdG-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aX1bur-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-zf7XdG-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-aX1bur-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-zf7XdG-build/
```
What helped was another hint that we found in the thread @dmitriyse already mentioned: using `--egg`:

```bash
$ pip install --egg git+https://github.com/pythonnet/pythonnet
DEPRECATION: --egg has been deprecated and will be removed in the future. This flag is mutually exclusive with large parts of pip, and actually using it invalidates pip's ability to manage the installation process.
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to /tmp/pip-EEz_4K-build
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... done
Successfully installed pythonnet-2.4.0.dev0
```

However, the `--egg` option is deprecated.

**Comment by denfromufa** [comment]
@hjaekel we are tracking this pip+git error in another issue: https://github.com/pythonnet/pythonnet/issues/555

Thanks for your efforts @hjaekel and @CodeProQuo, please don't forget to star this project! :+1:

**Comment by phxn** [comment]
> ```shell
> pip install pip --upgrade
> pip install setuptools --upgrade 
> ```
> 
> Should solve this issue

This completely broke my setup:

ImportError: cannot import name main

**Comment by denfromufa** [comment]
@phxn please read this thread below and this has nothing to do with pythonnet. But in general I agree that users should work in virtual environment, rather than messing with system python installation:

https://github.com/pypa/pip/issues/5599

**Comment by harshikanu** [comment]
Another way to resolve this is to download Windows SDK 10 (latest version). If this alone doesn't work then download Visual Studio 2019 (again whichever is the latest version). This updates the wheel process.

**Comment by nidhinhs** [comment]
Try downloading the wheel file from https://pypi.org/project/pythonnet/#modal-close [pythonnet](https://pypi.org/project/pythonnet/#modal-close) downloads. Make sure you download the correct version and use pip install <whl file>. cp in the file name will give you the python version number it's compatible with.

**Comment by tiggitech** [comment]
> 
> 
> ```shell
> pip install pip --upgrade
> pip install setuptools --upgrade 
> ```
> 
> Should solve this issue

I wanted to install a venv for python3.8.2 and Building wheel for pandocfilters and others prdouced erros. Executing your steps and building the venv again solved my issue.

**Comment by raharth** [comment]
I face the same error using Python 3.8.8 on Ubuntu 20.04.1


```
pip install pythonnet
Collecting pythonnet
  Using cached pythonnet-2.5.2.tar.gz (1.9 MB)
Requirement already satisfied: pycparser in /home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/site-packages (from pythonnet) (2.20)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/miniconda3/envs/jonas_MAPR/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-djlwcad0
       cwd: /tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/
  Complete output (43 lines):
  running bdist_wheel
  running build
  running build_ext
  /bin/sh: 1: mono: not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py", line 630, in <module>
      setup(
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py", line 612, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py", line 249, in build_extension
      self._install_packages()
    File "/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py", line 438, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/home/user/miniconda3/envs/jonas_MAPR/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 127.
  ----------------------------------------
  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
    Running setup.py install for pythonnet ... error
    ERROR: Command errored out with exit status 1:
     command: /home/user/miniconda3/envs/jonas_MAPR/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5e5in8ac/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/miniconda3/envs/jonas_MAPR/include/python3.8/pythonnet
         cwd: /tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/miniconda3/envs/jonas_MAPR/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py'"'"'; __file__='"'"'/tmp/pip-install-65g4tt0z/pythonnet_43b957a5cf02488a8f2748b73116daee/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5e5in8ac/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/miniconda3/envs/jonas_MAPR/include/python3.8/pythonnet Check the logs for full command output.```

**Comment by lostmsu** [comment]
@raharth , from your log:

> mono: not found

**Comment by raharth** [comment]
> 
> 
> @raharth , from your log:
> 
> > mono: not found

Well... I guess I'm sorry... you were perfectly right, thank you very much!
