### ISSUE TITLE
Python.net imports/calls from a worker thread causing unhandled exceptions

### ISSUE THREAD

**Issue by scoutsmother** [pythonnet/pythonnet#580]
### Environment

-   Pythonnet version: 2.3.0 Latest development build
-   Python version: 3.5.4
-   Operating System: Windows 10
-   Developing with Visual Studio 2017 and using ReSharper as a plugin (Explains the JetBrains decompiler paths in the stack trace)

### Details

I am developing in C# and using python.net to manage my calls to the tensorflow API. I was reading up on how to use threads with python net, and included a small implementation below of what i hope to accomplish.

    private dynamic np;
    // Called from main thread to initialize the python engine.
    public PythonManager()
    {
      // Initialize the engine
      if (!PythonEngine.IsInitialized)
        PythonEngine.Initialize();

      // Allow the worker thread to aquire the GIL.
      PythonEngine.BeginAllowThreads();
    }
     // Worker thread, called externally using 
    // Thread t = new Thread(DoWork);
    // t.Start();
    public void DoWork()
    {
      // Try is to catch the exception trying to import numpy.
      try
      {
        // Aquire the lock on the GIL
        using (Py.GIL())
        {
          np = Py.Import("numpy"); // Exception raised here
        }
      }
      catch (Exception e)
      {
        Console.WriteLine(e);
        throw;
      }

      // Do work with np here...

    }

The exception caught by the try-catch is:

Message: Thread was being aborted.

Stack Trace:
`   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in C:\Users\Maailman_Mies\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\B40137DC-C681-4462-94BB-042263C28757\dc\bd5ee5e7\ImportHook.cs:line 154
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in C:\Users\Maailman_Mies\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\B40137DC-C681-4462-94BB-042263C28757\dc\bd5ee5e7\ImportHook.cs:line 154
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in C:\Users\Maailman_Mies\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\B40137DC-C681-4462-94BB-042263C28757\dc\bd5ee5e7\ImportHook.cs:line 154
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in C:\Users\Maailman_Mies\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\B40137DC-C681-4462-94BB-042263C28757\dc\bd5ee5e7\ImportHook.cs:line 154
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in C:\Users\Maailman_Mies\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\B40137DC-C681-4462-94BB-042263C28757\dc\bd5ee5e7\ImportHook.cs:line 154
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in C:\Users\Maailman_Mies\AppData\Local\JetBrains\Shared\v09\DecompilerCache\decompiler\B40137DC-C681-4462-94BB-042263C28757\dc\bd5ee5e7\ImportHook.cs:line 154
   at Python.Runtime.Runtime.PyImport_ImportModule(String name)
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at PythonTest.PythonManager.DoWork() in C:\Users\Maailman_Mies\Source\Repos\...\PythonManager.cs:line 36`

**Comment by filmor** [comment]
1. Why are you importing `numpy` within the worker thread? The modules are shared in a Python process, it should be fine to import it within your constructor.
2. What is the `InnerException`?

**Comment by dmitriyse** [comment]
I am also using numpy with pythonnet (netcore 2.0) and have no problem with it.
I think is better way to import module in the main thread and then using it in any thread.
In my project I am using additional wrapping layer, that caches PyObject wrappers of modules.

So you problem is 100% solvable.
Anyway, I will try to reproduce you problem.

**Comment by scoutsmother** [comment]
I found the source of my problem. I was creating the thread DoWork() from above using XUnit. The test runner forced the thread that was created inside the test case I made to abort. I put blocking code after the thread creation to wait until the thread finished and i could successfully use numpy and tensor flow. 

You can close this issue now.

**Comment by ArjunWhabi** [comment]
> I found the source of my problem. I was creating the thread DoWork() from above using XUnit. The test runner forced the thread that was created inside the test case I made to abort. I put blocking code after the thread creation to wait until the thread finished and i could successfully use numpy and tensor flow.

Hi @IanAPerrigo 

Im facing a very similar issue. Would it be ok if you could post your solution code . That would really help me as well

Thanks
