### ISSUE TITLE
Exception running tests in nPython in Linux

### ISSUE THREAD

**Issue by Cronan** [pythonnet/pythonnet#581]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 2.7.5
-   Operating System: Red Hat Enterprise Linux Server release 7.3 (Maipo)
-   DotNet version: 2.0.0
### Details

-   Exception running tests in nPython in Linux
- Constructor on type 'System.Reflection.Emit.TypeBuilder' not found

`dotnet ./build/lib.linux-x86_64-2.7/netcoreapp2.0/nPython.dll`

```python
>>> import sys
>>> sys.path.append('/users/isys/icronyn/pyenvs/pythonnet/lib/python2.7/site-packages/pytest-2.9.1-py2.7.egg')
>>> sys.path.append('/users/isys/icronyn/pyenvs/pythonnet/lib/python2.7/site-packages/py-1.4.31-py2.7.egg')
>>> import pytest
>>> pytest.main()
```

```
============================================================================== test session starts ==============================================================================
platform linux2 -- Python 2.7.5, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /users/isys/icronyn/git/pythonnet, inifile: 
collected 376 items 

src/tests/test_array.py .....................................F..
src/tests/test_callback.py ..
src/tests/test_class.py .......F..F..FF...
src/tests/test_clrmethod.py FFFFF
src/tests/test_compat.py ......FFFF....F.
src/tests/test_constructors.py ....
src/tests/test_conversion.py ....................
src/tests/test_delegate.py ...
Unhandled Exception: System.MissingMethodException: Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Python.Runtime.DelegateManager.GetDelegate(Type dtype, IntPtr callable) in /users/isys/icronyn/git/pythonnet/src/runtime/delegatemanager.cs:line 159
   at Python.Runtime.DelegateObject.tp_new(IntPtr tp, IntPtr args, IntPtr kw) in /users/isys/icronyn/git/pythonnet/src/runtime/delegateobject.cs:line 61
   at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw) in /users/isys/icronyn/git/pythonnet/src/runtime/metatype.cs:line 148
   at Python.Runtime.Runtime.Py_Main(Int32 argc, String[] argv)
   at Python.Runtime.PythonConsole.Main(String[] args) in /users/isys/icronyn/git/pythonnet/src/console/pythonconsole.cs:line 37
Aborted
```

**Comment by Cronan** [comment]
More detail:
```python
>>> pytest.main(['-v'])
============================================================================== test session starts ==============================================================================
platform linux2 -- Python 2.7.5, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /users/isys/icronyn/pyenvs/pythonnet/bin/python
cachedir: .cache
rootdir: /users/isys/icronyn/git/pythonnet, inifile: 
collected 376 items 

src/tests/test_array.py::test_public_array PASSED
src/tests/test_array.py::test_protected_array PASSED
src/tests/test_array.py::test_internal_array PASSED
src/tests/test_array.py::test_private_array PASSED
src/tests/test_array.py::test_array_bounds_checking PASSED
src/tests/test_array.py::test_array_contains PASSED
src/tests/test_array.py::test_boolean_array PASSED
src/tests/test_array.py::test_byte_array PASSED
src/tests/test_array.py::test_sbyte_array PASSED
src/tests/test_array.py::test_char_array PASSED
src/tests/test_array.py::test_int16_array PASSED
src/tests/test_array.py::test_int32_array PASSED
src/tests/test_array.py::test_int64_array PASSED
src/tests/test_array.py::test_uint16_array PASSED
src/tests/test_array.py::test_uint32_array PASSED
src/tests/test_array.py::test_uint64_array PASSED
src/tests/test_array.py::test_single_array PASSED
src/tests/test_array.py::test_double_array PASSED
src/tests/test_array.py::test_decimal_array PASSED
src/tests/test_array.py::test_string_array PASSED
src/tests/test_array.py::test_enum_array PASSED
src/tests/test_array.py::test_object_array PASSED
src/tests/test_array.py::test_null_array PASSED
src/tests/test_array.py::test_interface_array PASSED
src/tests/test_array.py::test_typed_array PASSED
src/tests/test_array.py::test_multi_dimensional_array PASSED
src/tests/test_array.py::test_array_iteration PASSED
src/tests/test_array.py::test_tuple_array_conversion PASSED
src/tests/test_array.py::test_tuple_nested_array_conversion PASSED
src/tests/test_array.py::test_list_array_conversion PASSED
src/tests/test_array.py::test_list_nested_array_conversion PASSED
src/tests/test_array.py::test_sequence_array_conversion PASSED
src/tests/test_array.py::test_sequence_nested_array_conversion PASSED
src/tests/test_array.py::test_tuple_array_conversion_type_checking PASSED
src/tests/test_array.py::test_list_array_conversion_type_checking PASSED
src/tests/test_array.py::test_sequence_array_conversion_type_checking PASSED
src/tests/test_array.py::test_md_array_conversion PASSED
src/tests/test_array.py::test_boxed_value_type_mutation_result FAILED
src/tests/test_array.py::test_special_array_creation PASSED
src/tests/test_array.py::test_array_abuse PASSED
src/tests/test_callback.py::test_default_for_null PASSED
src/tests/test_callback.py::test_default_for_none PASSED
src/tests/test_class.py::test_basic_reference_type PASSED
src/tests/test_class.py::test_basic_value_type PASSED
src/tests/test_class.py::test_class_standard_attrs PASSED
src/tests/test_class.py::test_class_docstrings PASSED
src/tests/test_class.py::test_class_default_str PASSED
src/tests/test_class.py::test_class_default_repr PASSED
src/tests/test_class.py::test_non_public_class PASSED
src/tests/test_class.py::test_basic_subclass FAILED
src/tests/test_class.py::test_subclass_with_no_arg_constructor PASSED
src/tests/test_class.py::test_subclass_with_various_constructors PASSED
src/tests/test_class.py::test_struct_construction FAILED
src/tests/test_class.py::test_ienumerable_iteration PASSED
src/tests/test_class.py::test_ienumerator_iteration PASSED
src/tests/test_class.py::test_override_get_item FAILED
src/tests/test_class.py::test_override_set_item FAILED
src/tests/test_class.py::test_add_and_remove_class_attribute PASSED
src/tests/test_class.py::test_comparisons PASSED
src/tests/test_class.py::test_self_callback PASSED
src/tests/test_clrmethod.py::test_set_and_get_property_from_py FAILED
src/tests/test_clrmethod.py::test_set_and_get_property_from_clr FAILED
src/tests/test_clrmethod.py::test_set_and_get_property_from_clr_and_py FAILED
src/tests/test_clrmethod.py::test_method_invocation_from_py FAILED
src/tests/test_clrmethod.py::test_method_invocation_from_clr FAILED
src/tests/test_compat.py::test_simple_import PASSED
src/tests/test_compat.py::test_simple_import_with_alias PASSED
src/tests/test_compat.py::test_dotted_name_import PASSED
src/tests/test_compat.py::test_dotted_name_import_with_alias PASSED
src/tests/test_compat.py::test_simple_import_from PASSED
src/tests/test_compat.py::test_simple_import_from_with_alias PASSED
src/tests/test_compat.py::test_dotted_name_import_from FAILED
src/tests/test_compat.py::test_dotted_name_import_from_with_alias FAILED
src/tests/test_compat.py::test_from_module_import_star FAILED
src/tests/test_compat.py::test_explicit_assembly_load FAILED
src/tests/test_compat.py::test_implicit_load_already_valid_namespace PASSED
src/tests/test_compat.py::test_import_non_existant_module PASSED
src/tests/test_compat.py::test_lookup_no_namespace_type PASSED
src/tests/test_compat.py::test_module_lookup_recursion PASSED
src/tests/test_compat.py::test_module_get_attr FAILED
src/tests/test_compat.py::test_multiple_imports PASSED
src/tests/test_constructors.py::test_enum_constructor PASSED
src/tests/test_constructors.py::test_flags_constructor PASSED
src/tests/test_constructors.py::test_struct_constructor PASSED
src/tests/test_constructors.py::test_subclass_constructor PASSED
src/tests/test_conversion.py::test_bool_conversion PASSED
src/tests/test_conversion.py::test_sbyte_conversion PASSED
src/tests/test_conversion.py::test_byte_conversion PASSED
src/tests/test_conversion.py::test_char_conversion PASSED
src/tests/test_conversion.py::test_int16_conversion PASSED
src/tests/test_conversion.py::test_int32_conversion PASSED
src/tests/test_conversion.py::test_int64_conversion PASSED
src/tests/test_conversion.py::test_uint16_conversion PASSED
src/tests/test_conversion.py::test_uint32_conversion PASSED
src/tests/test_conversion.py::test_uint64_conversion PASSED
src/tests/test_conversion.py::test_single_conversion PASSED
src/tests/test_conversion.py::test_double_conversion PASSED
src/tests/test_conversion.py::test_decimal_conversion PASSED
src/tests/test_conversion.py::test_string_conversion PASSED
src/tests/test_conversion.py::test_interface_conversion PASSED
src/tests/test_conversion.py::test_object_conversion PASSED
src/tests/test_conversion.py::test_enum_conversion PASSED
src/tests/test_conversion.py::test_null_conversion PASSED
src/tests/test_conversion.py::test_byte_array_conversion PASSED
src/tests/test_conversion.py::test_sbyte_array_conversion PASSED
src/tests/test_delegate.py::test_delegate_standard_attrs PASSED
src/tests/test_delegate.py::test_global_delegate_visibility PASSED
src/tests/test_delegate.py::test_nested_delegate_visibility PASSED
src/tests/test_delegate.py::test_delegate_from_function 
Unhandled Exception: System.MissingMethodException: Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Python.Runtime.DelegateManager.GetDelegate(Type dtype, IntPtr callable) in /users/isys/icronyn/git/pythonnet/src/runtime/delegatemanager.cs:line 159
   at Python.Runtime.DelegateObject.tp_new(IntPtr tp, IntPtr args, IntPtr kw) in /users/isys/icronyn/git/pythonnet/src/runtime/delegateobject.cs:line 61
   at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw) in /users/isys/icronyn/git/pythonnet/src/runtime/metatype.cs:line 148
   at Python.Runtime.Runtime.Py_Main(Int32 argc, String[] argv)
   at Python.Runtime.PythonConsole.Main(String[] args) in /users/isys/icronyn/git/pythonnet/src/console/pythonconsole.cs:line 37
Aborted
```

**Comment by dmitriyse** [comment]
At the first look, it's just not supported to run pytest from nPython under dotnet core 2.0
![image](https://user-images.githubusercontent.com/10322215/33911237-2704e7dc-dfab-11e7-8aa1-0dae7de15ec9.png)

If you substitute correct version of Python.Test.dll you will pass all tests.
I need to implement some dynamic path substitution depending on host (dotnet or mono)

**Comment by dmitriyse** [comment]
More general problem is now tracked here https://github.com/pythonnet/pythonnet/issues/590
