### ISSUE TITLE
Exceptions running tests in Linux: Unable to cast to Int_3_Delegate

### ISSUE THREAD

**Issue by Cronan** [pythonnet/pythonnet#589]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 2.7.5
-   Operating System: Red Hat Enterprise Linux Server release 7.3 (Maipo)
-   DotNet version: 2.0.0
### Details

-   Exception running tests in nPython in Linux
-- src/tests/test_enum.py::test_enum_set_member_fails 

`dotnet ./build/lib.linux-x86_64-2.7/netcoreapp2.0/nPython.dll`

```python
============================= test session starts ==============================
platform linux2 -- Python 2.7.5, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /users/isys/icronyn/pyenvs/pythonnet/bin/python
cachedir: .cache
Arch: x64, UCS: 4, LIBDIR: /usr/lib64, Py_ENABLE_SHARED: True
rootdir: /users/isys/icronyn/git/pythonnet, inifile: 
collected 16 items 

src/tests/test_enum.py::test_enum_set_member_fails 
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'ObjObjArgFunc' to type 'Int_3_Delegate'.
   at Python.Runtime.NativeCall.Int_Call_3(IntPtr fp, IntPtr a1, IntPtr a2, IntPtr a3) in /users/isys/icronyn/git/pythonnet/src/runtime/nativecall.cs:line 47
   at Python.Runtime.MetaType.tp_setattro(IntPtr tp, IntPtr name, IntPtr value) in /users/isys/icronyn/git/pythonnet/src/runtime/metatype.cs:line 201
   at Python.Runtime.Runtime.Py_Main(Int32 argc, String[] argv)
   at Python.Runtime.PythonConsole.Main(String[] args) in /users/isys/icronyn/git/pythonnet/src/console/pythonconsole.cs:line 37
Aborted

```

**Comment by Cronan** [comment]
Same issue:

```python
src/tests/test_event.py::test_public_instance_event 
Unhandled Exception: System.MissingMethodException: Constructor on type 'System.Reflection.Emit.TypeBuilder' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Python.Runtime.DelegateManager.GetDelegate(Type dtype, IntPtr callable) in /users/isys/icronyn/git/pythonnet/src/runtime/delegatemanager.cs:line 159
   at Python.Runtime.EventObject.AddEventHandler(IntPtr target, IntPtr handler) in /users/isys/icronyn/git/pythonnet/src/runtime/eventobject.cs:line 39
   at Python.Runtime.EventBinding.nb_inplace_add(IntPtr ob, IntPtr arg) in /users/isys/icronyn/git/pythonnet/src/runtime/eventbinding.cs:line 34
   at Python.Runtime.Runtime.Py_Main(Int32 argc, String[] argv)
   at Python.Runtime.PythonConsole.Main(String[] args) in /users/isys/icronyn/git/pythonnet/src/console/pythonconsole.cs:line 37
Aborted
```

**Comment by dmitriyse** [comment]
More general problem is now tracked here #590
This hell is going due to using Mono compiled Python.Test.dll under .net core 2.0
