### ISSUE TITLE
Is there a way to install Pythonnet from master on a offline machine

### ISSUE THREAD

**Issue by AmraniRiyad** [pythonnet/pythonnet#659]
### Environment

-   Pythonnet version: installed from `pythonnet-2.3.0-cp27-cp27m-win32.whl`
-   Python version: 2.7.2 32bit
-   Operating System: Windows 7 64bits with no internet available on this machine

### Details

I'm trying to get Pythonnet working on a WPF C# project to make a Python interpreter which can : 
- launch Python scripts
- pass objects from C# to the script

I installed Pythonnet with the `pythonnet-2.3.0-cp27-cp27m-win32.whl`. I tried this :
```
using(Py.GIL())
{
    //ANY CODE
}
```
And got this error :

> Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Python.Runtime!Python.Runtime.Runtime::PyDict_GetItemString' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

I get PInvokeStackImbalance with all of the calls to the Python.Runtime like PythonEngine.Initialize,  PythonEngine.PythonHome, Py.GIL(), Py.Import().

Following issue  #561 and #485 and the troubleshooting wiki i tried to get Pythonnet from master and installing it with :
- `pip install C:\Users\user\Downloads\pythonnet-master`
- `python setup.py install`
- `python setup.py bdist_wheel --xplat`

But obviously the three commands got the same problem which is nuget access because i can't have internet on this machine.

```
C:\Users\user\Downloads>pip install C:\Users\user\Downloads\pythonnet-master
Processing c:\users\user\downloads\pythonnet-master
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\
temp\\pip-3sg2kq-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compil
e(code, __file__, 'exec'))" bdist_wheel -d c:\users\user\appdata\local\temp\tmpwp0qznpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Recherche de mises . jour depuis https://www.nuget.org/api/v2/.
  Le nom distant n'a pas pu ^tre r'solu: 'www.nuget.org'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\user\appdata\local\temp\pip-3sg2kq-build\setup.py", line 527, in <module>
      zip_safe=False,
    File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\python27\lib\distutils\core.py", line 152, in setup
      dist.run_commands()
    File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\users\user\appdata\local\temp\pip-3sg2kq-build\setup.py", line 475, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\python27\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "c:\users\user\appdata\local\temp\pip-3sg2kq-build\setup.py", line 168, in build_extension
      self._install_packages()
    File "c:\users\user\appdata\local\temp\pip-3sg2kq-build\setup.py", line 330, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "c:\python27\lib\subprocess.py", line 511, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'tools\nuget\nuget.exe update -self' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Found existing installation: pythonnet 2.3.0
    Uninstalling pythonnet-2.3.0:
      Successfully uninstalled pythonnet-2.3.0
  Running setup.py install for pythonnet ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local
\\temp\\pip-3sg2kq-build\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(comp
ile(code, __file__, 'exec'))" install --record c:\users\user\appdata\local\temp\pip-ypbzmw-record\install-record.txt --single-versio
n-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
  Rolling back uninstall of pythonnet
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\user\\appdata\\local\\temp\\pip-3sg2kq-build
\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exe
c'))" install --record c:\users\user\appdata\local\temp\pip-ypbzmw-record\install-record.txt --single-version-externally-managed --c
ompile" failed with error code 1 in c:\users\user\appdata\local\temp\pip-3sg2kq-build\
```
Any suggestions on how can i make this work on a offline machine ?

**Comment by denfromufa** [comment]
grab binaries from appveyor based on instructions in wiki:

https://github.com/pythonnet/pythonnet/wiki/Installation

**Comment by Hypn0tical** [comment]
I am facing the same error and have no idea how appveyor and the link could help me. Can you be more specific please? Thanks

**Comment by lostmsu** [comment]
@Hypn0tical were you unable to install wheels from AppVeyor? Why?
