### ISSUE TITLE
Got `System.NullReferenceException: Object reference not set to an instance of an object.` when pass a byte[] argument

### ISSUE THREAD

**Issue by PaleNeutron** [pythonnet/pythonnet#664]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6
-   Operating System:  Windows 10

### Details

   In python:

```python
    import sys
    sys.path.append(".\lib")
    clr.AddReference("EncryptEmulator")
    from EncryptEmulator import *
    my_instance = Program()
    with open("quest_skip", 'rb') as f:
        i_b = f.read()
    # i_b = Array[Byte](i_b)
    body = Program.Decrypt(i_b)
```
 in C# I have:

```C#
static public string Decrypt(byte[] input_b)
```
    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
E:\Documents\prcd_unpack\PrrdMonitor>python PcrdMonitor.py
Traceback (most recent call last):
  File "PcrdMonitor.py", line 35, in <module>
    body = Program.Decrypt(i_b)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Cute.CryptAES.DecryptRJ256Api(Byte[] sEncryptedString)
   at EncryptEmulator.Program.Decrypt(Byte[] input_b)
```

**Comment by PaleNeutron** [comment]
Found a mistake in my C# code.
