### ISSUE TITLE
Wrong exception passed from static getter

### ISSUE THREAD

**Issue by skuvv** [pythonnet/pythonnet#671]
### Environment

-   Pythonnet version: 2.3
-   Python version: 3.6.5
-   Operating System: Windows 7 x64

### Details

-   Describe what you were trying to get done.
My test class:

```csharp
using System;
namespace CsExceptionTest
{
    public class Class1
    {
        public static Class1 GetInstance
        {
            get
            {
                //throw new Exception("GetInstance::Exception");
                return new Class1();
            }
        }

        public Class1()
        {
            throw new Exception("Class1::Exception");
        }
    }
}

```
Next, when I call GetInstance I get wrong exception instead exception from ctr Class1.
Repro steps:
```python
>>> import sys, clr
>>> sys.path.append(r'F:\CsExceptionTest\bin\Debug')
>>> import CsExceptionTest

>>> instance = CsExceptionTest.Class1()
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    instance = CsExceptionTest.Class1()
System.Exception: Class1::Exception
   at CsExceptionTest.Class1..ctor() in F:\CsExceptionTest\Class1.cs:line 17

>>> CsExceptionTest.Class1.GetInstance
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    CsExceptionTest.Class1.GetInstance
TypeError: Exception has been thrown by the target of an invocation.
```
    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    print('TODO')
```

-   If there was a crash, please include the traceback here.

```python
    print('TODO')
```

**Comment by denfromufa** [comment]
@skuvv what are you expecting here?

**Comment by skuvv** [comment]
@denfromufa, obviously, for a line of code:
```python
>>> CsExceptionTest.Class1.GetInstance
```
"System.Exception: Class1::Exception"
In other words, how can I understand what happened in c # without any error information?
TypeError in this case does not provide error message as I expected.

**Comment by denfromufa** [comment]
@skuvv have you tried the master branch?
