### ISSUE TITLE
wheel doesn't get auto installed in master (x64)

### ISSUE THREAD

**Issue by SlimeQ** [pythonnet/pythonnet#682]
### Environment

-   Pythonnet version: master (6/6/18)
-   Python version: 2.7.15
-   Operating System: Windows 10

### Details

-   Describe what you were trying to get done.

    I'm attempting to install pythonnet

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```
python setup.py build_ext --inplace
```

-   If there was a crash, please include the traceback here.

```
>python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    from wheel import bdist_wheel
ImportError: No module named wheel
```

I was able to easily fix this issue by running `pip install wheel`. I see the dependency in requirements.txt so I'm not really sure why it wasn't auto-installed.

**Comment by denfromufa** [comment]
@SlimeQ as you can see, requirements.txt is used only in CI:

https://github.com/pythonnet/pythonnet/search?q=requirements.txt&unscoped_q=requirements.txt

Can you report back your pip/setuptools versions? Are you using conda? This maybe your issue:

https://realwecan.blogspot.com/2018/01/while-compiling-tensorflow-from-source.html

**Comment by SlimeQ** [comment]
I'm also getting the `could not find ildasm.exe` error which #216 indicates may be related to wheel? The suggested fix (UnmanagedExports.1.2.7) is irrelevant as it's already been upgraded in master

**Comment by denfromufa** [comment]
@SlimeQ can you try installing from master like this? What Visual Studio setup do you have?

```
(base) C:\Users\denis.akhiyarov>pip install git+https://github.com/pythonnet/pythonnet
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to c:\users\denis~1.akh\appdata\local\temp\pip-req-build-_atl1juq
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... done
  Stored in directory: C:\Users\DENIS~1.AKH\AppData\Local\Temp\pip-ephem-wheel-cache-mx0nipoj\wheels\a0\50\fb\5a5a945b4f0001742d290048624c009db1917f90eba143f0e9
Successfully built pythonnet
Installing collected packages: pythonnet
Successfully installed pythonnet-2.4.0.dev0
```

**Comment by SlimeQ** [comment]
No good. I have VS 2017
```
C:\Users\quincyc>pip install git+https://github.com/pythonnet/pythonnet
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\quincyc\\appdata\\local\\temp\\pip-req-build-fjje_x\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\quincyc\appdata\local\temp\pip-wheel-adppmx --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 4.6.2.
  Update successful.
  MSBuild auto-detection: using msbuild version '15.7.179.6572' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Adding package 'UnmanagedExports.1.2.7' to folder 'c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages'
  Adding package 'NUnit.3.7.1' to folder 'c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages'
  Added package 'NUnit.3.7.1' to folder 'c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages'

  NuGet Config files used:
      c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\NuGet.Config
      C:\Users\quincyc\AppData\Roaming\NuGet\NuGet.Config

  Feeds used:
      C:\Users\quincyc\.nuget\packages\
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://api.nuget.org/v3/index.json

  Installed:
      3 package(s) to packages.config projects
  Microsoft (R) Manifest Tool
  Copyright (c) Microsoft Corporation.
  All rights reserved.
  Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.

  delegatemanager.cs(204,13): warning CS0162: Unreachable code detected [c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\runtime\Python.Runtime.csproj]
  pyobject.cs(50,13): warning CS0162: Unreachable code detected [c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\runtime\Python.Runtime.csproj]
  pyscope.cs(534,13): warning CS0162: Unreachable code detected [c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\runtime\Python.Runtime.csproj]
  pythonexception.cs(67,13): warning CS0162: Unreachable code detected [c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\runtime\Python.Runtime.csproj]
    Python.Runtime -> c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\runtime\bin\Python.Runtime.dll
    Python.Test -> c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\testing\bin\Python.Test.dll
  dynamic.cs(121,28): warning CS0618: 'PythonEngine.RunString(string, IntPtr?, IntPtr?)' is obsolete: 'RunString is deprecated and will be removed. Use Exec/Eval/RunSimpleString instead.' [c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\embed_tests\Python.EmbeddingTest.csproj]
    Python.EmbeddingTest -> c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\embed_tests\bin\Python.EmbeddingTest.dll
    Console -> c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\console\bin\nPython.exe
    clrmodule -> c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\clrmodule\bin\clrmodule.dll
  c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\packages\UnmanagedExports.1.2.7\tools\RGiesecke.DllExport.targets(58,3): error : Microsoft.Build.Utilities.ToolLocationHelper could not find ildasm.exe. [c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\src\clrmodule\clrmodule.csproj]
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\setup.py", line 527, in <module>
      zip_safe=False,
    File "c:\python27\lib\site-packages\setuptools\__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "c:\python27\lib\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\setup.py", line 475, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "c:\python27\lib\site-packages\wheel\bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "c:\python27\lib\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\python27\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\python27\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\setup.py", line 265, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "c:\python27\lib\subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" pythonnet.sln /p:Configuration=ReleaseWin /p:Platform=x64 /p:DefineConstants="PYTHON27%3BPYTHON2%3BUCS2" /p:PythonBuildDir="c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\build\lib.win-amd64-2.7" /p:PythonInteropFile="interop27.cs" /verbosity:minimal /p:PythonManifest="c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\build\lib.win-amd64-2.7\app.manifest" /t:Build' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\quincyc\\appdata\\local\\temp\\pip-req-build-fjje_x\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\quincyc\appdata\local\temp\pip-record-ckxdh4\install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\quincyc\\appdata\\local\\temp\\pip-req-build-fjje_x\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\quincyc\appdata\local\temp\pip-record-ckxdh4\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\quincyc\appdata\local\temp\pip-req-build-fjje_x\
```

**Comment by SlimeQ** [comment]
Just a note, I've already upgraded both pip and setuptools to the latest versions.

**Comment by denfromufa** [comment]
@SlimeQ did you run `pip install wheel`?

**Comment by denfromufa** [comment]
closing due to inactivity, you can grab the latest wheels from appveyor artifacts.
