### ISSUE TITLE
System.BadImageFormatException in Window Form Visual Studio 2017

### ISSUE THREAD

**Issue by STREETKILLER007** [pythonnet/pythonnet#717]
**Environment**

1) Pythonnet version: v2.3.0

![11](https://user-images.githubusercontent.com/13400998/44086065-ff67be9e-9fed-11e8-9988-ecd65bebee96.PNG)

i downloaded this from "Manage Nuget-Package" in Visual Studio 2017 Community

2) Python version: Python 3.6.5 (Amaconda 3)

Already `pip install pythonnet` in the environment.

3) Operating System: Window 7, 64 bit

4) Software Used : Microsoft Visual Studio Community 2017

4.1) .net framework : 4

5) python version from cmd

![111](https://user-images.githubusercontent.com/13400998/44086598-ac621c10-9fef-11e8-90d8-b6347bdb3b4f.PNG)

6) where python from cmd

![112](https://user-images.githubusercontent.com/13400998/44086721-06cef010-9ff0-11e8-8bde-65fe1ef78dc6.PNG)

7) path includes 

M:\Anaconda3;M:\Anaconda3\Library\mingww64\bin;M:\Anaconda3\Library\usr\bin;M:\Anaconda3\Library\bin;M:\Anaconda3\Scripts

**Details**

To do : Trying to implement Python in c# form

Progress :  

running this code.

```
private static void button_Click(object sender, EventArgs e)
{
    using (Py.GIL())   
    {
         dynamic myVisbrain = Py.Import("Visbrain"); 
    }
}
```

when debug,

from program.cs

`Application.Run(new Form1()); // crashes here`

error message :  
```
Exception thrown: 'System.BadImageFormatException' in System.Windows.Forms.dll
An unhandled exception of type 'System.BadImageFormatException' occurred in System.Windows.Forms.dll
Could not load file or assembly 'Python.Runtime, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```

stack trace : 

```
System.BadImageFormatException
  HResult=0x8007000B
  Message=Could not load file or assembly 'Python.Runtime, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
  Source=WindowsFormsAppJTTH
  StackTrace:
   at WindowsFormsAppJTTH.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\Administrator\source\repos\WindowsFormsAppJTTH\WindowsFormsAppJTTH\Form1.cs:line 219
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at WindowsFormsAppJTTH.Program.Main() in C:\Users\Administrator\source\repos\WindowsFormsAppJTTH\WindowsFormsAppJTTH\Program.cs:line 19
```

Would like to know how to solve this, thank you.

**Comment by denfromufa** [comment]
this is duplicate, next time please search the issue tracker and wiki:

https://github.com/pythonnet/pythonnet/issues/472
