### ISSUE TITLE
NuGet throws error parsing pythonnet.sln during installation

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [pythonnet/pythonnet#729]
### Environment

-   Pythonnet version: Have tried the latest git build, and the pip version
-   Python version: 3.5.5
-   Mono version: 5.10.1.57
-   Operating System: Arch Linux 

### Details

-   Attempting to install

-   Tried to install via (in virtualenv and not):

```
pip install pythonnet
```
```
pip install git+https://github.com/pythonnet/pythonnet
```

- Error log:

```log
(env) 15:34:31 levi ~/dev/courts/database/db_manager/temp/pythonnet λ pip install pythonnet
Collecting pythonnet
  Using cached https://files.pythonhosted.org/packages/89/3b/a22cd45b591d6cf490ee8b24d52b9db1f30b4b478b64a9b231c53474731e/pythonnet-2.3.0.tar.gz
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /home/levi/dev/courts/database/db_manager/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ma5hweb/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpe4a0c4axpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.7.1.
  Update successful.
  MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
  Error parsing solution file at /tmp/pip-build-_ma5hweb/pythonnet/pythonnet.sln:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-_ma5hweb/pythonnet/setup.py", line 405, in <module>
      zip_safe=False,
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/levi/dev/courts/database/db_manager/env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-build-_ma5hweb/pythonnet/setup.py", line 139, in build_extension
      self._install_packages()
    File "/tmp/pip-build-_ma5hweb/pythonnet/setup.py", line 273, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln -o packages' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/levi/dev/courts/database/db_manager/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ma5hweb/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k_dp3mjw-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/levi/dev/courts/database/db_manager/env/include/site/python3.5/pythonnet:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.7.1.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
    Error parsing solution file at /tmp/pip-build-_ma5hweb/pythonnet/pythonnet.sln:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_ma5hweb/pythonnet/setup.py", line 405, in <module>
        zip_safe=False,
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/levi/dev/courts/database/db_manager/env/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-_ma5hweb/pythonnet/setup.py", line 139, in build_extension
        self._install_packages()
      File "/tmp/pip-build-_ma5hweb/pythonnet/setup.py", line 273, in _install_packages
        subprocess.check_call(cmd, shell=use_shell)
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln -o packages' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/levi/dev/courts/database/db_manager/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ma5hweb/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k_dp3mjw-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/levi/dev/courts/database/db_manager/env/include/site/python3.5/pythonnet" failed with error code 1 in /tmp/pip-build-_ma5hweb/pythonnet/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by CaerphillyMediaLtd** [comment]
I reinstalled mono-develop and now I get the following error:

```
(env) 18:24:23 levi ~/dev/courts/database/db_manager/temp/pythonnet λ pip install pythonnet
Collecting pythonnet
  Using cached https://files.pythonhosted.org/packages/89/3b/a22cd45b591d6cf490ee8b24d52b9db1f30b4b478b64a9b231c53474731e/pythonnet-2.3.0.tar.gz
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /home/levi/dev/courts/database/db_manager/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8pc9f000/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp208l02blpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.7.1.
  Update successful.
  MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
  Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
  Restoring NuGet package NUnit.3.6.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Adding package 'NUnit.3.6.0' to folder '/tmp/pip-build-8pc9f000/pythonnet/packages'
  Adding package 'NUnit.ConsoleRunner.3.6.0' to folder '/tmp/pip-build-8pc9f000/pythonnet/packages'
  Adding package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-8pc9f000/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/tmp/pip-build-8pc9f000/pythonnet/packages'
  Added package 'NUnit.ConsoleRunner.3.6.0' to folder '/tmp/pip-build-8pc9f000/pythonnet/packages'
  Added package 'NUnit.3.6.0' to folder '/tmp/pip-build-8pc9f000/pythonnet/packages'
  
  NuGet Config files used:
      /home/levi/.config/NuGet/NuGet.Config
  
  Feeds used:
      /home/levi/.nuget/packages/
      https://api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  clang-6.0: warning: /usr/include/python3.5m: 'linker' input unused [-Wunused-command-line-argument]
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.10.1.57
  Copyright (C) 2005-2013 Various Mono authors
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  XBuild Engine Version 14.0
  Mono, Version 5.10.1.57
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  /tmp/pip-build-8pc9f000/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-8pc9f000/pythonnet/setup.py", line 405, in <module>
      zip_safe=False,
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/levi/dev/courts/database/db_manager/env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-build-8pc9f000/pythonnet/setup.py", line 222, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON35,PYTHON3,UCS4,MONO_LINUX,PYTHON_WITH_PYMALLOC" /p:PythonBuildDir="/tmp/pip-build-8pc9f000/pythonnet/build/lib.linux-x86_64-3.5" /p:PythonInteropFile="interop35m.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /home/levi/dev/courts/database/db_manager/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8pc9f000/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p4fbp5h3-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/levi/dev/courts/database/db_manager/env/include/site/python3.5/pythonnet:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.7.1.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
    All packages listed in packages.config are already installed.
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.10.1.57
    Copyright (C) 2005-2013 Various Mono authors
    
    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
    
    XBuild Engine Version 14.0
    Mono, Version 5.10.1.57
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    /tmp/pip-build-8pc9f000/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8pc9f000/pythonnet/setup.py", line 405, in <module>
        zip_safe=False,
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/levi/dev/courts/database/db_manager/env/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-8pc9f000/pythonnet/setup.py", line 222, in build_extension
        subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON35,PYTHON3,UCS4,MONO_LINUX,PYTHON_WITH_PYMALLOC" /p:PythonBuildDir="/tmp/pip-build-8pc9f000/pythonnet/build/lib.linux-x86_64-3.5" /p:PythonInteropFile="interop35m.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1
    
    ----------------------------------------
Command "/home/levi/dev/courts/database/db_manager/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8pc9f000/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p4fbp5h3-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/levi/dev/courts/database/db_manager/env/include/site/python3.5/pythonnet" failed with error code 1 in /tmp/pip-build-8pc9f000/pythonnet/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by denfromufa** [comment]
related #744

**Comment by jkirk** [comment]
@CaerphillyMediaLtd Any update on this? Were you able to solve this issue?

**Comment by filmor** [comment]
As this issue hasn't been updated in quite a while, I'll close it for now. Feel free to reopen if this is still relevant and update it with all additional information you can provide.

**Comment by liujiaruirz** [comment]
Got the same error. Any updates?
