### ISSUE TITLE
System.IO.FileNotFoundException when adding reference

### ISSUE THREAD

**Issue by davidguaita** [pythonnet/pythonnet#735]
### Environment

-   Pythonnet version: 2.4.0.dev0
-   Python version: Python 3.5.5 :: Anaconda, Inc.
-   Operating System: Linux Centos 7.0 
-   Mono version 5.14.0.177

### Details

-   Describe what you were trying to get done.
    Trying to add a reference, it throws a System.IO.FileNotFoundException, even if the file exists at that path.
    The dll target runtime is v4.0.30319, it was build for .net target 4.5
   
    _TODO_

-   What commands did you run to trigger this issue? If you can provide a
    [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
    this will help us understand the issue.

```python
    import clr
    clr.AddReference('/opt/app/XXXX/YYYY/Simulator.dll')
```

-   If there was a crash, please include the traceback here.

```python
    Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
System.IO.FileNotFoundException: Unable to find assembly '/opt/app/XXXX/YYYY/Simulator.dll'.
  at Python.Runtime.CLRModule.AddReference (System.String name) [0x00072] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0

```

**Comment by denfromufa** [comment]
Have you tried adding reference to assembly without ".dll" in the specified full path?

**Comment by davidguaita** [comment]
Thanks for your reply.

I've just tried, and it crashes:
Command: 
```
clr.AddReference('/opt/app/XXXX/YYYY/Simulator')
```
Output:
```
mono_class_from_mono_type: implement me 0x00

* Assertion: should not be reached at class.c:1868

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes (System.Reflection.Assembly,bool) [0x00017] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at System.Reflection.Assembly.GetTypes () [0x00000] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at Python.Runtime.AssemblyManager.ScanAssembly (System.Reflection.Assembly) [0x00000] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at Python.Runtime.AssemblyManager.AssemblyLoadHandler (object,System.AssemblyLoadEventArgs) [0x00012] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at System.AppDomain.DoAssemblyLoad (System.Reflection.Assembly) [0x00016] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) [0x0004f] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom (string,bool) [0x0000b] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at System.Reflection.Assembly.LoadFrom (string) [0x00000] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at Python.Runtime.AssemblyManager.LoadAssemblyPath (string) [0x0000c] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at Python.Runtime.AssemblyManager.ResolveHandler (object,System.ResolveEventArgs) [0x00051] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at System.AppDomain.DoAssemblyResolve (string,System.Reflection.Assembly,bool) [0x00075] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object__this___object_object_byte (object,intptr,intptr,intptr) [0x0001e] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.AppDomain.LoadAssembly (System.AppDomain,string,System.Security.Policy.Evidence,bool) [0x00017] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at System.AppDomain.Load (string,System.Security.Policy.Evidence,bool) [0x00021] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at System.AppDomain.Load (string) [0x00000] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at (wrapper remoting-invoke-with-check) System.AppDomain.Load (string) [0x00032] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at System.Reflection.Assembly.Load (string) [0x00005] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at Python.Runtime.AssemblyManager.LoadAssembly (string) [0x00002] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at Python.Runtime.CLRModule.AddReference (string) [0x00027] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_object_object (object,intptr,intptr,intptr) [0x0004f] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) [0x0000c] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) [0x0003b] in <07ee25a61b9a464bb090b7d7d8a4a4c1>:0
  at Python.Runtime.MethodBinder.Invoke (intptr,intptr,intptr,System.Reflection.MethodBase,System.Reflection.MethodInfo[]) [0x00064] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at Python.Runtime.MethodObject.Invoke (intptr,intptr,intptr,System.Reflection.MethodBase) [0x00000] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at Python.Runtime.MethodObject.Invoke (intptr,intptr,intptr) [0x00000] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at Python.Runtime.ModuleFunctionObject.tp_call (intptr,intptr,intptr) [0x00006] in <03e2ba2d5de9403ba8e3f8b36216e30f>:0
  at (wrapper native-to-managed) Python.Runtime.ModuleFunctionObject.tp_call (intptr,intptr,intptr) <0x00097>
/proc/self/maps:
41cb6000-41cc6000 rwxp 00000000 00:00 0
41dbc000-41e3f000 rwxp 00000000 00:00 0
55edd2d0f000-55edd2fb9000 r-xp 00000000 08:03 22974177                   /root/anaconda3/envs/py35/bin/python3.5
55edd31b9000-55edd31bb000 r--p 002aa000 08:03 22974177                   /root/anaconda3/envs/py35/bin/python3.5
55edd31bb000-55edd321d000 rw-p 002ac000 08:03 22974177                   /root/anaconda3/envs/py35/bin/python3.5
55edd321d000-55edd324d000 rw-p 00000000 00:00 0
55edd4585000-55edd4fe8000 rw-p 00000000 00:00 0                          [heap]
7f9dc362f000-7f9dc3b31000 r--p 00000000 08:03 140356437                  /opt/app/BPAI/aiengine/UnityEditor.dll
7f9dc3b31000-7f9dc4000000 r--p 00000000 08:03 140355096                  /opt/app/BPAI/aiengine/Assembly-CSharp.dll.dll
7f9dc4000000-7f9dc4021000 rw-p 00000000 00:00 0
7f9dc4021000-7f9dc8000000 ---p 00000000 00:00 0
7f9dc802f000-7f9dc8145000 rw-p 00000000 00:00 0
7f9dc8145000-7f9dc818c000 r--p 00000000 08:03 140355094                  /opt/app/BPAI/aiengine/Assembly-CSharp-firstpass.dll.dll
7f9dc818c000-7f9dc820c000 rw-p 00000000 00:00 0
7f9dc820f000-7f9dc83f4000 r--p 00000000 08:03 140356439                  /opt/app/BPAI/aiengine/UnityEngine.dll
7f9dc83f4000-7f9dc84b4000 rw-p 00000000 00:00 0
7f9dc84b8000-7f9dc8538000 rw-p 00000000 00:00 0
7f9dc853b000-7f9dc883d000 r--p 00000000 08:03 137319614                  /usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
7f9dc883d000-7f9dc8b00000 r--p 00000000 08:03 69718812                   /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
7f9dc8b00000-7f9dc8c00000 rw-p 00000000 00:00 0
7f9dc8c07000-7f9dc8c18000 r--p 00000000 08:03 140356427                  /opt/app/BPAI/aiengine/Simulator.dll
7f9dc8c18000-7f9dc8c36000 r--p 00000000 08:03 202734444                  /usr/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
7f9dc8c36000-7f9dc8c82000 r--p 00000000 08:03 17484043                   /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
7f9dc8c82000-7f9dc8d7b000 r--p 00000000 08:03 137320769                  /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll
7f9dc8d7b000-7f9dc8d7c000 ---p 00000000 00:00 0
7f9dc8d7c000-7f9dc8d7d000 rw-p 00000000 00:00 0
7f9dc8d7d000-7f9dc8d85000 ---p 00000000 00:00 0
7f9dc8d85000-7f9dc8ffc000 rw-p 00000000 00:00 0
7f9dc8fff000-7f9dc9fff000 rw-p 00000000 00:00 0
7f9dc9fff000-7f9dca000000 ---p 00000000 00:00 0
7f9dca000000-7f9dcac00000 rw-p 00000000 00:00 0
7f9dcac08000-7f9dcac0c000 rw-p 00000000 00:00 0
7f9dcac0d000-7f9dcac0e000 rw-p 00000000 00:00 0
7f9dcac0e000-7f9dcafe0000 r--p 00000000 08:03 5464196                    /usr/lib/mono/4.5/mscorlib.dll
7f9dcafe0000-7f9dcafe1000 rw-p 00000000 00:00 0
7f9dcafe1000-7f9dcb040000 ---p 00000000 00:00 0
7f9dcb040000-7f9dcb084000 r-xp 00000000 08:03 70684839                   /root/anaconda3/envs/py35/lib/libpcre.so.1.2.10
7f9dcb084000-7f9dcb283000 ---p 00044000 08:03 70684839                   /root/anaconda3/envs/py35/lib/libpcre.so.1.2.10
7f9dcb283000-7f9dcb284000 r--p 00043000 08:03 70684839                   /root/anaconda3/envs/py35/lib/libpcre.so.1.2.10
7f9dcb284000-7f9dcb285000 rw-p 00044000 08:03 70684839                   /root/anaconda3/envs/py35/lib/libpcre.so.1.2.10
7f9dcb285000-7f9dcb296000 r-xp 00000000 08:03 134662578                  /root/anaconda3/envs/py35/lib/libgcc_s.so.1
7f9dcb296000-7f9dcb495000 ---p 00011000 08:03 134662578                  /root/anaconda3/envs/py35/lib/libgcc_s.so.1
7f9dcb495000-7f9dcb496000 r--p 00010000 08:03 134662578                  /root/anaconda3/envs/py35/lib/libgcc_s.so.1
7f9dcb496000-7f9dcb497000 rw-p 00011000 08:03 134662578                  /root/anaconda3/envs/py35/lib/libgcc_s.so.1
7f9dcb497000-7f9dcb5ae000 r-xp 00000000 08:03 22863596                   /root/anaconda3/envs/py35/lib/libglib-2.0.so.0.5600.1
7f9dcb5ae000-7f9dcb7ad000 ---p 00117000 08:03 22863596                   /root/anaconda3/envs/py35/lib/libglib-2.0.so.0.5600.1
7f9dcb7ad000-7f9dcb7ae000 r--p 00116000 08:03 22863596                   /root/anaconda3/envs/py35/lib/libglib-2.0.so.0.5600.1
7f9dcb7ae000-7f9dcb7af000 rw-p 00117000 08:03 22863596                   /root/anaconda3/envs/py35/lib/libglib-2.0.so.0.5600.1
7f9dcb7af000-7f9dcb7b0000 rw-p 00000000 00:00 0
7f9dcb7b0000-7f9dcbbda000 r-xp 00000000 08:03 233374356                  /usr/lib/libmonosgen-2.0.so.1.0.0
7f9dcbbda000-7f9dcbdda000 ---p 0042a000 08:03 233374356                  /usr/lib/libmonosgen-2.0.so.1.0.0
7f9dcbdda000-7f9dcbde1000 r--p 0042a000 08:03 233374356                  /usr/lib/libmonosgen-2.0.so.1.0.0
7f9dcbde1000-7f9dcbde7000 rw-p 00431000 08:03 233374356                  /usr/lib/libmonosgen-2.0.so.1.0.0
7f9dcbde7000-7f9dcbdfe000 rw-p 00000000 00:00 0
7f9dcbdfe000-7f9dcbe01000 r-xp 00000000 08:03 147582940                  /root/anaconda3/envs/py35/lib/python3.5/site-packages/clr.cpython-35m-x86_64-linux-gnu.so
7f9dcbe01000-7f9dcc000000 ---p 00003000 08:03 147582940                  /root/anaconda3/envs/py35/lib/python3.5/site-packages/clr.cpython-35m-x86_64-linux-gnu.so
7f9dcc000000-7f9dcc001000 r--p 00002000 08:03 147582940                  /root/anaconda3/envs/py35/lib/python3.5/site-packages/clr.cpython-35m-x86_64-linux-gnu.so
7f9dcc001000-7f9dcc002000 rw-p 00003000 08:03 147582940                  /root/anaconda3/envs/py35/lib/python3.5/site-packages/clr.cpython-35m-x86_64-linux-gnu.so
7f9dcc002000-7f9dcc038000 r-xp 00000000 08:03 22817136                   /root/anaconda3/envs/py35/lib/libtinfow.so.6.1
7f9dcc038000-7f9dcc238000 ---p 00036000 08:03 22817136                   /root/anaconda3/envs/py35/lib/libtinfow.so.6.1
7f9dcc238000-7f9dcc23c000 r--p 00036000 08:03 22817136                   /root/anaconda3/envs/py35/lib/libtinfow.so.6.1
7f9dcc23c000-7f9dcc23d000 rw-p 0003a000 08:03 22817136                   /root/anaconda3/envs/py35/lib/libtinfow.so.6.1
7f9dcc23d000-7f9dcc274000 r-xp 00000000 08:03 70682427                   /root/anaconda3/envs/py35/lib/libncursesw.so.6.1
7f9dcc274000-7f9dcc474000 ---p 00037000 08:03 70682427                   /root/anaconda3/envs/py35/lib/libncursesw.so.6.1
7f9dcc474000-7f9dcc475000 r--p 00037000 08:03 70682427                   /root/anaconda3/envs/py35/lib/libncursesw.so.6.1
7f9dcc475000-7f9dcc476000 rw-p 00038000 08:03 70682427                   /root/anaconda3/envs/py35/lib/libncursesw.so.6.1
7f9dcc476000-7f9dcc4b7000 r-xp 00000000 08:03 22863637                   /root/anaconda3/envs/py35/lib/libreadline.so.7.0
7f9dcc4b7000-7f9dcc6b7000 ---p 00041000 08:03 22863637                   /root/anaconda3/envs/py35/lib/libreadline.so.7.0
7f9dcc6b7000-7f9dcc6b9000 r--p 00041000 08:03 22863637                   /root/anaconda3/envs/py35/lib/libreadline.so.7.0
7f9dcc6b9000-7f9dcc6bf000 rw-p 00043000 08:03 22863637                   /root/anaconda3/envs/py35/lib/libreadline.so.7.0
7f9dcc6bf000-7f9dcc6c1000 rw-p 00000000 00:00 0
7f9dcc6c1000-7f9dcc6c7000 r-xp 00000000 08:03 211484684                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/readline.cpython-35m-x86_64-linux-gnu.so
7f9dcc6c7000-7f9dcc8c6000 ---p 00006000 08:03 211484684                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/readline.cpython-35m-x86_64-linux-gnu.so
7f9dcc8c6000-7f9dcc8c7000 r--p 00005000 08:03 211484684                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/readline.cpython-35m-x86_64-linux-gnu.so
7f9dcc8c7000-7f9dcc8c9000 rw-p 00006000 08:03 211484684                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/readline.cpython-35m-x86_64-linux-gnu.so
7f9dcc8c9000-7f9dcc909000 rw-p 00000000 00:00 0
7f9dcc909000-7f9dcc90c000 r-xp 00000000 08:03 211484539                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/_heapq.cpython-35m-x86_64-linux-gnu.so
7f9dcc90c000-7f9dccb0b000 ---p 00003000 08:03 211484539                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/_heapq.cpython-35m-x86_64-linux-gnu.so
7f9dccb0b000-7f9dccb0c000 r--p 00002000 08:03 211484539                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/_heapq.cpython-35m-x86_64-linux-gnu.so
7f9dccb0c000-7f9dccb0e000 rw-p 00003000 08:03 211484539                  /root/anaconda3/envs/py35/lib/python3.5/lib-dynload/_heapq.cpython-35m-x86_64-linux-gnu.so
7f9dccb0e000-7f9dccb4e000 rw-p 00000000 00:00 0
7f9dccb4e000-7f9dd3077000 r--p 00000000 08:03 201343790                  /usr/lib/locale/locale-archive
7f9dd3077000-7f9dd3178000 r-xp 00000000 08:03 134291613                  /usr/lib64/libm-2.17.so
7f9dd3178000-7f9dd3377000 ---p 00101000 08:03 134291613                  /usr/lib64/libm-2.17.so
7f9dd3377000-7f9dd3378000 r--p 00100000 08:03 134291613                  /usr/lib64/libm-2.17.so
7f9dd3378000-7f9dd3379000 rw-p 00101000 08:03 134291613                  /usr/lib64/libm-2.17.so
7f9dd3379000-7f9dd3380000 r-xp 00000000 08:03 137837220                  /usr/lib64/librt-2.17.so
7f9dd3380000-7f9dd357f000 ---p 00007000 08:03 137837220                  /usr/lib64/librt-2.17.so
7f9dd357f000-7f9dd3580000 r--p 00006000 08:03 137837220                  /usr/lib64/librt-2.17.so
7f9dd3580000-7f9dd3581000 rw-p 00007000 08:03 137837220                  /usr/lib64/librt-2.17.so
7f9dd3581000-7f9dd3583000 r-xp 00000000 08:03 137837224                  /usr/lib64/libutil-2.17.so
7f9dd3583000-7f9dd3782000 ---p 00002000 08:03 137837224                  /usr/lib64/libutil-2.17.so
7f9dd3782000-7f9dd3783000 r--p 00001000 08:03 137837224                  /usr/lib64/libutil-2.17.so
7f9dd3783000-7f9dd3784000 rw-p 00002000 08:03 137837224                  /usr/lib64/libutil-2.17.so
7f9dd3784000-7f9dd3786000 r-xp 00000000 08:03 134291581                  /usr/lib64/libdl-2.17.so
7f9dd3786000-7f9dd3986000 ---p 00002000 08:03 134291581                  /usr/lib64/libdl-2.17.so
7f9dd3986000-7f9dd3987000 r--p 00002000 08:03 134291581                  /usr/lib64/libdl-2.17.so
7f9dd3987000-7f9dd3988000 rw-p 00003000 08:03 134291581                  /usr/lib64/libdl-2.17.so
7f9dd3988000-7f9dd3b4b000 r-xp 00000000 08:03 134291572                  /usr/lib64/libc-2.17.so
7f9dd3b4b000-7f9dd3d4a000 ---p 001c3000 08:03 134291572                  /usr/lib64/libc-2.17.so
7f9dd3d4a000-7f9dd3d4e000 r--p 001c2000 08:03 134291572                  /usr/lib64/libc-2.17.so
7f9dd3d4e000-7f9dd3d50000 rw-p 001c6000 08:03 134291572                  /usr/lib64/libc-2.17.so
7f9dd3d50000-7f9dd3d55000 rw-p 00000000 00:00 0
7f9dd3d55000-7f9dd3d6c000 r-xp 00000000 08:03 137837216                  /usr/lib64/libpthread-2.17.so
7f9dd3d6c000-7f9dd3f6b000 ---p 00017000 08:03 137837216                  /usr/lib64/libpthread-2.17.so
7f9dd3f6b000-7f9dd3f6c000 r--p 00016000 08:03 137837216                  /usr/lib64/libpthread-2.17.so
7f9dd3f6c000-7f9dd3f6d000 rw-p 00017000 08:03 137837216                  /usr/lib64/libpthread-2.17.so
7f9dd3f6d000-7f9dd3f71000 rw-p 00000000 00:00 0
7f9dd3f71000-7f9dd3f93000 r-xp 00000000 08:03 134291556                  /usr/lib64/ld-2.17.so
7f9dd3f93000-7f9dd3f94000 rw-p 00000000 00:00 0
7f9dd3f94000-7f9dd3f95000 r--p 00000000 08:03 134291437                  /opt/app/BPAI/aiengine/TestLibrary3.dll
7f9dd3f95000-7f9dd3f9a000 rw-p 00000000 00:00 0
7f9dd3f9a000-7f9dd3fbc000 r--p 00000000 08:03 144400326                  /root/anaconda3/envs/py35/lib/python3.5/site-packages/Python.Runtime.dll
7f9dd3fbc000-7f9dd4188000 rw-p 00000000 00:00 0
7f9dd4188000-7f9dd4189000 rw-s 00000000 00:12 141028                     /dev/shm/mono.6203
7f9dd4189000-7f9dd418a000 rw-p 00000000 00:00 0
7f9dd418a000-7f9dd4191000 r--s 00000000 08:03 19914                      /usr/lib64/gconv/gconv-modules.cache
7f9dd4191000-7f9dd4192000 rw-p 00000000 00:00 0
7f9dd4192000-7f9dd4193000 r--p 00021000 08:03 134291556                  /usr/lib64/ld-2.17.so
7f9dd4193000-7f9dd4194000 rw-p 00022000 08:03 134291556                  /usr/lib64/ld-2.17.so
7f9dd4194000-7f9dd4195000 rw-p 00000000 00:00 0
7fff40dd6000-7fff40dde000 ---p 00000000 00:00 0
7fff415b4000-7fff415d5000 rw-p 00000000 00:00 0                          [stack]
7fff415fa000-7fff415fc000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Native stacktrace:

        /lib/libmonosgen-2.0.so.1(+0xe94f9) [0x7f9dcb8994f9]
        /lib64/libpthread.so.0(+0xf6d0) [0x7f9dd3d646d0]
        /lib64/libc.so.6(gsignal+0x37) [0x7f9dd39be277]
        /lib64/libc.so.6(abort+0x148) [0x7f9dd39bf968]
        /lib/libmonosgen-2.0.so.1(+0x2e5604) [0x7f9dcba95604]
        /lib/libmonosgen-2.0.so.1(monoeg_g_logv+0x40) [0x7f9dcbaa9800]
        /lib/libmonosgen-2.0.so.1(monoeg_assertion_message+0xd7) [0x7f9dcbaa99a7]
        /lib/libmonosgen-2.0.so.1(mono_class_from_mono_type+0x30f) [0x7f9dcb961f0f]
        /lib/libmonosgen-2.0.so.1(+0x2612e8) [0x7f9dcba112e8]
        /lib/libmonosgen-2.0.so.1(+0x2615a9) [0x7f9dcba115a9]
        /lib/libmonosgen-2.0.so.1(+0x1d75a4) [0x7f9dcb9875a4]
        /lib/libmonosgen-2.0.so.1(+0x1e1053) [0x7f9dcb991053]
        [0x41df3eff]

Debug info from gdb:

[New LWP 6208]
[New LWP 6207]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007f9dd3d64279 in waitpid () from /lib64/libpthread.so.0
  Id   Target Id         Frame
  3    Thread 0x7f9dca7ff700 (LWP 6207) "SGen worker" 0x00007f9dd3d60995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2    Thread 0x7f9dc8f7b700 (LWP 6208) "Finalizer" 0x00007f9dd3d62afb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
* 1    Thread 0x7f9dd4182740 (LWP 6203) "python" 0x00007f9dd3d64279 in waitpid () from /lib64/libpthread.so.0

Thread 3 (Thread 0x7f9dca7ff700 (LWP 6207)):
#0  0x00007f9dd3d60995 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f9dcba8a973 in mono_os_cond_wait (mutex=0x7f9dcbdfb400 <lock>, cond=0x7f9dcbdfb3c0 <work_cond>) at ../../mono/utils/mono-os-mutex.h:173
#2  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#3  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#4  0x00007f9dd3d5ce25 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f9dd3a86bad in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7f9dc8f7b700 (LWP 6208)):
#0  0x00007f9dd3d62afb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
#1  0x00007f9dd3d62b8f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007f9dd3d62c2b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x00007f9dcba3c87c in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x7f9dcbdecb20 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:209
#4  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x7f9dcbdecb20 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:43
#5  finalizer_thread (unused=unused@entry=0x0) at gc.c:903
#6  0x00007f9dcb9f4623 in start_wrapper_internal (stack_ptr=<optimized out>, start_info=0x0) at threads.c:1098
#7  start_wrapper (data=0x55edd4736910) at threads.c:1158
#8  0x00007f9dd3d5ce25 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f9dd3a86bad in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f9dd4182740 (LWP 6203)):
#0  0x00007f9dd3d64279 in waitpid () from /lib64/libpthread.so.0
#1  0x00007f9dcb8995be in mono_handle_native_crash (signal=0x7f9dcbad46a6 "SIGABRT", ctx=<optimized out>, info=<optimized out>) at mini-exceptions.c:3048
#2  <signal handler called>
#3  0x00007f9dd39be277 in raise () from /lib64/libc.so.6
#4  0x00007f9dd39bf968 in abort () from /lib64/libc.so.6
#5  0x00007f9dcba95604 in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=0x55edd4fd0e80 "* Assertion: should not be reached at class.c:1868\n") at mono-log-common.c:135
#6  0x00007f9dcbaa9800 in monoeg_g_logv (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x7f9dcbab3208 "* Assertion: should not be reached at %s:%d\n", args=args@entry=0x7fff415d0cf8) at goutput.c:115
#7  0x00007f9dcbaa99a7 in monoeg_assertion_message (format=format@entry=0x7f9dcbab3208 "* Assertion: should not be reached at %s:%d\n") at goutput.c:146
#8  0x00007f9dcb961f0f in mono_class_from_mono_type (type=type@entry=0x55edd4d20978) at class.c:1868
#9  0x00007f9dcba112e8 in mono_type_get_object_checked (domain=domain@entry=0x55edd46cd270, type=0x55edd4d20978, error=error@entry=0x7fff415d1090) at reflection.c:446
#10 0x00007f9dcba115a9 in mono_type_get_object_handle (domain=domain@entry=0x55edd46cd270, type=<optimized out>, error=error@entry=0x7fff415d1090) at reflection.c:559
#11 0x00007f9dcb9875a4 in image_get_type (tdef=0x55edd4d467f0, exportedOnly=0 '\000', error=0x7fff415d1090, exceptions=0x55edd46c1770, res=0x55edd46c1778, count=35, table_idx=37, image=0x55edd4d466f0, domain=0x55edd46cd270) at icall.c:5540
#12 mono_module_get_types (domain=domain@entry=0x55edd46cd270, image=image@entry=0x55edd4d466f0, exceptions=exceptions@entry=0x55edd46c1770, exportedOnly=exportedOnly@entry=0 '\000', error=error@entry=0x7fff415d1090) at icall.c:5576
#13 0x00007f9dcb991053 in ves_icall_System_Reflection_Assembly_GetTypes (assembly_handle=0x55edd46c1768, exportedOnly=<optimized out>, error=0x7fff415d1090) at icall.c:5644
#14 0x0000000041df3eff in ?? ()
#15 0x0000000000000000 in ?? ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================


```

**Comment by denfromufa** [comment]
@davidguaita are you able to run the test suite of pythonnet on this linux system? if yes, then the issue is likely in your dll or a use case not covered by the pythonnet test suite. also check with previous versions of mono, because we have seen some instabilities in few mono releases.

**Comment by davidguaita** [comment]
@denfromufa 
Thanks for your response.
I've run the test suite on the linux system and it gave no errors.
Also tried that dll with mono version 4.8.0 and had the same results.
I think the problem must be something with that dll, because I build some other simple dll for testing and they run without problems..
Sorry, there's any info related to troubleshooting your dll?

**Comment by denfromufa** [comment]
@davidguaita we have a troubleshooting guide here:

https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX

Few things to troubleshoot:

1. Pythonnet bug or Mono bug. Try filing an issue on Mono issue tracker. The error looks like a execution path where the Mono runtime should not have entered in the first place.
2. Try running the same code with .NET Core on Linux. Pythonnet support is partial for .NET Core, you have to use nPython executable instead of importing clr.
3. Try switching the Python runtime/version - there are some differences between 2.7-3.6 and between CPython/Anaconda.

**Comment by davidguaita** [comment]
@dentromufa
Thank you very much!
I'll try to fix it.

**Comment by denfromufa** [comment]
closed due to inactivity
