### ISSUE TITLE
.net core assembly version Redirect

### ISSUE THREAD

**Issue by sunliusi** [pythonnet/pythonnet#739]
my package using .net core self contain. when i publish to server:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Thread, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。
   at InQuant.OpenApi.Market.MarketWrapper..ctor(StrategyService strategySvr)
   at InQuant.OpenApi.StrategyService..ctor()

import sys
import clr
import System
clr.AddReference('InQuant.OpenApi')
import InQuant.OpenApi

class StrategyTemplate(object):
    def __init__(self):	
        self.__strategyService = InQuant.OpenApi.StrategyService()

the .net dll  "InQuant.OpenApi" depend on System.Threading. i think i should to redirect  assembly version.  What should I do?

**Comment by sunliusi** [comment]
The python.net maybe don't support .netcore, i just change to .net framework.
