### ISSUE TITLE
Multiple Initialize/Shutdown sequences problem with C# classes exported to python.

### ISSUE THREAD

**Issue by jfu334** [pythonnet/pythonnet#743]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.6
-   Operating System: Win10

### Details

I want to use pythonnet to provide a python integration for a product. I export a C# class to a python module A with the .ToPython() call to provide a clean API to those who will write python code. 

Then an other python module is loaded that accesses the python module A and the exported C# class contained. 

The code looks like this from the C# side: 

```
PythonEngine.Initialize();
_pyThreadsHandle=PythonEngine.BeginAllowThreads();

// make the py module containing c# api
using(Py.GIL())
{
	_pyApiModule=PythonEngine.ModuleFromString("A", /*content of module A*/);
	_pyApiModule.SetAttr("csApi", _csApi.ToPython());
}

// load other modules that import A and use A.csApi. 
using(Py.GIL())
{
	var pyModule=PythonEngine.ImportModule(/*module B*/);
}	

// later on: 
PythonEngine.EndAllowThreads(_pyThreadsHandle);
PythonEngine.Shutdown();
```
The first time this code works as expected, but on second iteration it crashes with the exception below. 
In the global code of B, an 

Module A:
```python

# import python wrapper objects from c# assembly
import clr
from SomeCsharpAssembly import SomeCsharpClass

# api handle set by SetAttr after import
csApi=None
```

Module B:
```python
import A

x=A.SomeCsharpClass(arguments)
csApi.someMethod(x)
```

The exception
```
Arithmetic operation resulted in an overflow.
  System.OverflowException
   at System.IntPtr.op_Explicit(IntPtr value)
   at Python.Runtime.ManagedType.GetManagedObject(IntPtr ob) in D:\somePath\pythonnet-2.3.0\src\runtime\managedtype.cs:line 31
   at Python.Runtime.ClassObject.tp_new(IntPtr tp, IntPtr args, IntPtr kw) in D:\somePath\pythonnet-2.3.0\src\runtime\classobject.cs:line 53
   at e__NativeCall.Call_3(IntPtr , IntPtr , IntPtr , IntPtr )
   at Python.Runtime.NativeCall.Call_3(IntPtr fp, IntPtr a1, IntPtr a2, IntPtr a3) in D:\somePath\pythonnet-2.3.0\src\runtime\nativecall.cs:line 128
   at Python.Runtime.MetaType.tp_call(IntPtr tp, IntPtr args, IntPtr kw) in D:\somePath\pythonnet-2.3.0\src\runtime\metatype.cs:line 154
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.ImportHook.__import__(IntPtr self, IntPtr args, IntPtr kw) in D:\somePath\pythonnet-2.3.0\src\runtime\importhook.cs:line 236
   at Python.Runtime.Runtime.PyImport_ImportModule(String name)
   at Python.Runtime.PythonEngine.ImportModule(String name) in D:\somePath\pythonnet-2.3.0\src\runtime\pythonengine.cs:line 387
```
To me this looks like it's crashing when the constructor of SomeCsharpClass is called. If I remove this part of code, it works. 

I've digged a bit around the pythonnet code and to me it looks like on several places caching structures are not cleared after Shutdown and reused after next Init. For example, if I disable caching in classmanager.cs completely, the code still runs perfect for the first iteration, but the exception on second iteration turns into an access violation.

But this is only a guess.

**Comment by denfromufa** [comment]
@jfu334 this has been raised multiple times in this issue tracker. there is no one clear solution.

**Comment by jfu334** [comment]
It would be nice to mention this bug somewhere in the docs. The init/shutdown calls suggest to the user that the lifetime of the pythonnet bindings starts with init and stops with shutdown and can be repeated as often as desired. 

However it seems that when using pythonnet as intended, only one cycle is supported. There is no warning about this and the occurring errors don't tell the user that he didn't do anything wrong but acted in the misbelief that init->shutdown can't be repeated.

**Comment by jfu334** [comment]
I think the static design of the bindings in part of this problem. Would there be support for a change that switches from the static classes to an instance-bound implementation?

**Comment by denfromufa** [comment]
Contributions are welcome!

**Comment by benoithudson** [comment]
This is somewhat related to #714 which I fixed with the very hacky idea of pointing to native code that's never freed, even after shutdown. Somewhat less hacky would be to implement all the slots in a native library.

**Comment by murtazabasu** [comment]
Is there any progress in this regard? 
Have been facing this problem for a quite a while now and was searching for a fix until I bumped into this issue.
The first cycle works perfectly however the second cycle throws exception if the PythonEngine is Shutdown after 1st cycle.
