### ISSUE TITLE
xbuild error trying to install pythonnet

### ISSUE THREAD

**Issue by AbhimanyuAryan** [pythonnet/pythonnet#744]
I don't know how to solve this error. I'm on macos mojave. I have visual studio installed on mac along with that xamarin, mono and .net core

```
pip install pythonnet                                                       ✔ master
Collecting pythonnet
  Downloading https://files.pythonhosted.org/packages/89/3b/a22cd45b591d6cf490ee8b24d52b9db1f30b4b478b64a9b231c53474731e/pythonnet-2.3.0.tar.gz (1.5MB)
    100% |████████████████████████████████| 1.5MB 4.7MB/s
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet ... error
  Complete output from command /Users/abhimanyuaryan/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-wheel-puve2b2z --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.7.1.
  Update successful.
  MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin'.
  Restoring NuGet package NUnit.3.6.0.
  Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
    GET https://api.nuget.org/v3-flatcontainer/nunit/3.6.0/nunit.3.6.0.nupkg
    GET https://api.nuget.org/v3-flatcontainer/unmanagedexports/1.2.7/unmanagedexports.1.2.7.nupkg
    GET https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/3.6.0/nunit.consolerunner.3.6.0.nupkg
    OK https://api.nuget.org/v3-flatcontainer/unmanagedexports/1.2.7/unmanagedexports.1.2.7.nupkg 978ms
  Installing UnmanagedExports 1.2.7.
  Adding package 'UnmanagedExports.1.2.7' to folder '/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/packages'
  Added package 'UnmanagedExports.1.2.7' to folder '/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/packages'
    OK https://api.nuget.org/v3-flatcontainer/nunit.consolerunner/3.6.0/nunit.consolerunner.3.6.0.nupkg 2310ms
  Installing NUnit.ConsoleRunner 3.6.0.
  Adding package 'NUnit.ConsoleRunner.3.6.0' to folder '/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/packages'
  Added package 'NUnit.ConsoleRunner.3.6.0' to folder '/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/packages'
    OK https://api.nuget.org/v3-flatcontainer/nunit/3.6.0/nunit.3.6.0.nupkg 3129ms
  Installing NUnit 3.6.0.
  Adding package 'NUnit.3.6.0' to folder '/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/packages'
  Added package 'NUnit.3.6.0' to folder '/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/packages'

  NuGet Config files used:
      /Users/abhimanyuaryan/.config/NuGet/NuGet.Config

  Feeds used:
      /Users/abhimanyuaryan/.nuget/packages/
      https://api.nuget.org/v3/index.json

  Installed:
      3 package(s) to packages.config projects
  clang: warning: /Users/abhimanyuaryan/anaconda/include/python3.6m: 'linker' input unused [-Wunused-command-line-argument]

  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

  XBuild Engine Version 14.0
  Mono, Version 5.12.0.0
  Copyright (C) 2005-2013 Various Mono authors

  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

  XBuild Engine Version 14.0
  Mono, Version 5.12.0.0
  Copyright (C) 2005-2013 Various Mono authors
  		Configuration: ReleaseMono Platform: x64
  /private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py", line 405, in <module>
      zip_safe=False,
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py", line 222, in build_extension
      subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
    File "/Users/abhimanyuaryan/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON36,PYTHON3,UCS4,MONO_OSX,PYTHON_WITH_PYMALLOC" /p:PythonBuildDir="/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/build/lib.macosx-10.7-x86_64-3.6" /p:PythonInteropFile="interop36m.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1.

  ----------------------------------------
  Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet ... error
    Complete output from command /Users/abhimanyuaryan/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-record-2mzh8y3s/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.7.1.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin'.
    All packages listed in packages.config are already installed.

    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

    XBuild Engine Version 14.0
    Mono, Version 5.12.0.0
    Copyright (C) 2005-2013 Various Mono authors

    >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<

    XBuild Engine Version 14.0
    Mono, Version 5.12.0.0
    Copyright (C) 2005-2013 Various Mono authors
    		Configuration: ReleaseMono Platform: x64
    /private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/src/runtime/Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py", line 405, in <module>
        zip_safe=False,
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py", line 222, in build_extension
        subprocess.check_call(" ".join(cmd + ["/t:Build"]), shell=use_shell)
      File "/Users/abhimanyuaryan/anaconda/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'xbuild pythonnet.sln /p:Configuration=ReleaseMono /p:Platform=x64 /p:DefineConstants="PYTHON36,PYTHON3,UCS4,MONO_OSX,PYTHON_WITH_PYMALLOC" /p:PythonBuildDir="/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/build/lib.macosx-10.7-x86_64-3.6" /p:PythonInteropFile="interop36m.cs" /verbosity:minimal /t:Build' returned non-zero exit status 1.

    ----------------------------------------
Command "/Users/abhimanyuaryan/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-record-2mzh8y3s/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/5n/ghyfb6n9387_h2w5ycg9pd980000gn/T/pip-install-6cea6_qj/pythonnet/
pip install pythonnet  17.57s user 4.69s system 46% cpu 47.967 total
```

**Comment by denfromufa** [comment]
So the error is actually this one:

```
Python.Runtime.csproj: error : Error executing task Copy: Error converting Property named 'SourceFiles' with value '$(TargetAssemblyPdb)' to type Microsoft.Build.Framework.ITaskItem[]: Can't concatenate Item list with other strings where an item list is expected ('@(_OutDirItem->'%(FullPath)')', 'Python.Runtime.pdb'). Use semi colon to separate items.
```

This has been reported here before, so nothing Mac OSX specific:

https://github.com/pythonnet/pythonnet/issues/729

Closing as duplicate.
