### ISSUE TITLE
Offline installation for linux

### ISSUE THREAD

**Issue by shaielc** [pythonnet/pythonnet#750]
### Environment

-   Pythonnet version:
-   Python version:
-   Operating System: ubuntu 16.04

### Details
Is there a way to install pythonnet on a linux machine that doesn't have a connection to the internet?

tried installing from master and got this : 

running bdist_wheel
running build
running build_ext
Checking for updates from https://www.nuget.org/api/v2/.
Error: NameResolutionFailure
Traceback (most recent call last):
  File "setup.py", line 527, in <module>
    zip_safe=False,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 475, in run
    return bdist_wheel.bdist_wheel.run(self)
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 168, in build_extension
    self._install_packages()
  File "setup.py", line 330, in _install_packages
    subprocess.check_call(cmd, shell=use_shell)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1

second why no support for .NET core on linux?

thx

**Comment by filmor** [comment]
You can build the wheel on anothermachine and copy it over. nuget is only needed for the buils process.

Regarding.NET core, check the open issues and pull requests, there has been some work in this direction.
