### ISSUE TITLE
pythonnet install fails with anaconda

### ISSUE THREAD

**Issue by mtclare** [pythonnet/pythonnet#847]
### Environment

-   Pythonnet version: 2.3.0
-   Python version: 3.7
-   Operating System: Windows 10

### Details

Trying to install pythonnet using anaconda 1.97 and python 3.7.  This is a new windows 10 install and may be missing something needed.

Getting this result:

Looking in indexes: https&#58;://pypi.anaconda.org/pythonnet/simple
Collecting pythonnet
  Downloading https&#58;://pypi.anaconda.org/pythonnet/simple/pythonnet/2.3.0/pythonnet-2.3.0.tar.gz (1.5MB)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py): started
  Building wheel for pythonnet (setup.py): finished with status 'error'
  Complete output from command C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mtclare\\AppData\\Local\\Temp\\pip-install-_yp252ux\\pythonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\mtclare\AppData\Local\Temp\pip-wheel-fivdy8em --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https&#58;://www.nuget.org/api/v2/.
  Currently running NuGet.exe 3.5.0.
  Updating NuGet.exe to 4.9.4.
  Update successful.
  MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
  Restoring NuGet package NUnit.3.6.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Restoring NuGet package NUnit.ConsoleRunner.3.6.0.
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\packages'
  Adding package 'NUnit.ConsoleRunner.3.6.0' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\packages'
  Adding package 'NUnit.3.6.0' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\packages'
  Added package 'NUnit.ConsoleRunner.3.6.0' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\packages'
  Added package 'NUnit.3.6.0' to folder 'C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\packages'
  
  NuGet Config files used:
      C:\Users\mtclare\AppData\Roaming\NuGet\NuGet.Config
  
  Feeds used:
      C:\Users\mtclare\.nuget\packages\
      https&#58;://api.nuget.org/v3/index.json
  
  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "tools\geninterop\geninterop.py", line 292, in <module>
      sys.exit(main())
    File "tools\geninterop\geninterop.py", line 272, in main
      python_h = preprocess_python_headers()
    File "tools\geninterop\geninterop.py", line 192, in preprocess_python_headers
      for line in _check_output(cmd).splitlines():
    File "tools\geninterop\geninterop.py", line 41, in _check_output
      output = subprocess.check_output(*args, **kwargs)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 1178, in _execute_child
      startupinfo)
  FileNotFoundError: [WinError 2] The system cannot find the file specified
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\setup.py", line 405, in <module>
      zip_safe=False,
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\setup.py", line 191, in build_extension
      subprocess.check_call([sys.executable, geninterop, interop_file])
    File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\mtclare\\AppData\\Local\\Continuum\\anaconda3\\envs\\TEST\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop37.cs']' returned non-zero exit status 1.
  
  ----------------------------------------
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    Complete output from command C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mtclare\\AppData\\Local\\Temp\\pip-install-_yp252ux\\pythonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mtclare\AppData\Local\Temp\pip-record-3uhoty5i\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Checking for updates from https&#58;://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.9.4.
    NuGet.exe is up to date.
    MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319'.
    All packages listed in packages.config are already installed.
    Traceback (most recent call last):
      File "tools\geninterop\geninterop.py", line 292, in <module>
        sys.exit(main())
      File "tools\geninterop\geninterop.py", line 272, in main
        python_h = preprocess_python_headers()
      File "tools\geninterop\geninterop.py", line 192, in preprocess_python_headers
        for line in _check_output(cmd).splitlines():
      File "tools\geninterop\geninterop.py", line 41, in _check_output
        output = subprocess.check_output(*args, **kwargs)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\setup.py", line 405, in <module>
        zip_safe=False,
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\setup.py", line 191, in build_extension
        subprocess.check_call([sys.executable, geninterop, interop_file])
      File "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Users\\mtclare\\AppData\\Local\\Continuum\\anaconda3\\envs\\TEST\\python.exe', 'tools\\geninterop\\geninterop.py', 'src\\runtime\\interop37.cs']' returned non-zero exit status 1.
    
    ----------------------------------------
  Failed building wheel for pythonnet
Command "C:\Users\mtclare\AppData\Local\Continuum\anaconda3\envs\TEST\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mtclare\\AppData\\Local\\Temp\\pip-install-_yp252ux\\pythonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mtclare\AppData\Local\Temp\pip-record-3uhoty5i\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\mtclare\AppData\Local\Temp\pip-install-_yp252ux\pythonnet\

**Comment by mtclare** [comment]
Note: This is a brand new computer and does not have a global install of Python yet.. just the Python under Anaconda.  So typing "python.exe" at the cmd line returns file not found.

**Comment by mtclare** [comment]
It seemed to install fine using anaconda with python 2.7 and "pip install pythonnet".  I am not sure why a separate anaconda install of python 3.7 does not work.

**Comment by denfromufa** [comment]
Pythonnet for Python 3.7 is in the master branch. Have a look at installation wiki.
