### ISSUE TITLE
ImportError: System.NotImplementedException: No support for armv7l

### ISSUE THREAD

**Issue by bimajatiwijaya** [pythonnet/pythonnet#873]
### Environment

-   Pythonnet version: 
     - 2.4.0 & 2.4.1.dev0
-   Python version: 2.7.9
-   Operating System: Raspbian GNU/Linux 8 (jessie)

### Details
- Installation 
    - sudo pip install git+https://github.com/pythonnet/pythonnet
    - sudo pip install pythonnet==2.4.0 
-   Error triggered when import clr

```python
    import clr
    clr.AddReference("myLib")
```

-   Traceback (most recent call last):
>>> import clr
  File "<stdin>", line 1, in <module>
ImportError: System.NotImplementedException: No support for armv7l
  at Python.Runtime.TypeManager+NativeCode.get_Active () [0x0002a] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.TypeManager.InitializeNativeCodePage () [0x00017] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.TypeManager.InitializeSlots (System.IntPtr type, System.Type impl) [0x000ad] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.TypeManager.CreateMetaType (System.Type impl) [0x00077] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.MetaType.Initialize () [0x00000] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.Runtime.Initialize (System.Boolean initSigs) [0x002a2] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.PythonEngine.Initialize (System.Collections.Generic.IEnumerable`1[T] args, System.Boolean setSysArgv, System.Boolean initSigs) [0x00014] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.PythonEngine.Initialize (System.Boolean setSysArgv, System.Boolean initSigs) [0x00005] in <9666540cfc85422bb7aded792ea4f880>:0
  at Python.Runtime.PythonEngine.InitExt () [0x00000] in <9666540cfc85422bb7aded792ea4f880>:0

**Comment by bimajatiwijaya** [comment]
For now i reset commit to https://github.com/pythonnet/pythonnet/commit/6d68d70db037ed27fc0d8f24302202a2be8224f6 and "No support for armv7l" solved.

**Comment by maurice1103** [comment]
Can you probably explain to me (with the command line commands) how you solved it? I tried it yesterday for several hours and failed miserably...

**Comment by maurice1103** [comment]
### Environment

-   Pythonnet version: 2.4.0 
-   Python version: 2.7.13
-   Operating System: Raspbian GNU/Linux 9.9 (stretch)

### Details

-   git clone https://github.com/pythonnet/pythonnet
-   python setup.py bdist_wheel --xplat
-   pip install --no-index --find-links=.\dist\ pythonnet
-   Error triggered when import clr

```python
    import clr
```

-   Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: System.NotImplementedException: No support for armv7l
  at Python.Runtime.TypeManager+NativeCode.get_Active () [0x0002a] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.TypeManager.InitializeNativeCodePage () [0x00017] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.TypeManager.InitializeSlots (System.IntPtr type, System.Type impl) [0x000ad] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.TypeManager.CreateMetaType (System.Type impl) [0x00077] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.MetaType.Initialize () [0x00000] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.Runtime.Initialize (System.Boolean initSigs) [0x002a2] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.PythonEngine.Initialize (System.Collections.Generic.IEnumerable`1[T] args, System.Boolean setSysArgv, System.Boolean initSigs) [0x00014] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.PythonEngine.Initialize (System.Boolean setSysArgv, System.Boolean initSigs) [0x00005] in <3c181e2b216e4da7b915e672de4e00f2>:0 
  at Python.Runtime.PythonEngine.InitExt () [0x00000] in <3c181e2b216e4da7b915e672de4e00f2>:0

**Comment by bimajatiwijaya** [comment]
1. uninstall pythonnet
2. clone to /home/user/pythonnet
3. cd /home/user/pythonnet
4. git reset --hard 6d68d70db037ed27fc0d8f24302202a2be8224f6
5. Then install [it](https://github.com/pythonnet/pythonnet/wiki/Installation#github-installation-from-master-branch)

**Comment by maurice1103** [comment]
thx a lot for your help but im still getting the same error....
Is probabla still something wrong with my .whl file?
[Pythonnet.zip](https://github.com/pythonnet/pythonnet/files/3305214/Pythonnet.zip)

**Comment by bimajatiwijaya** [comment]
@maurice1103 we have different environment python version & OS version please try to make it equal.

**Comment by filmor** [comment]
The problematic PR is #752, I have created a pull request for this but have right now no easy way of testing it. Could you both check whether it works for you with

    pip install git+https://github.com/filmor/pythonnet.git@support-arm

?

**Comment by filmor** [comment]
This should be fixed on master, please reopen if it isn't.
