### ISSUE TITLE
Not able to install Pythonnet on Jenkins

### ISSUE THREAD

**Issue by abhi19935** [pythonnet/pythonnet#919]
### Environment

-   Pythonnet version: 2.3.0 or higher
-   Python version: 2.7

### Details

-   I am trying to install pythonnet in my build Pre-Build step as Execute Shell on Central Jenkins (not local Jenkins) using 
1. pip install pythonnet --user
2. pip install git+https://github.com/pythonnet/pythonnet
3. git clone https://github.com/pythonnet/pythonnet
    cd pythonnet
    python setup.py bdist_wheel --xplat
    pip install --no-index --find-links=.\dist\ pythonnet
 None of above 3 is working, also i am able to install other packages using pip

For 1 I am getting below error:
+ pip install pythonnet --user
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pythonnet
  Downloading https://files.pythonhosted.org/packages/4a/0a/5964a5a1fdf207fab8e718edd1f8d3578e0681577fe9abe0d9006f9718c2/pythonnet-2.4.0.tar.gz (1.8MB)
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py): started
  Building wheel for pythonnet (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-PxBK14/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-PxBK14/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-hnzgPf --python-tag cp27
       cwd: /tmp/pip-install-PxBK14/pythonnet/
  Complete output (41 lines):
  running bdist_wheel
  running build
  running build_ext
  /bin/sh: mono: command not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-PxBK14/pythonnet/setup.py", line 658, in <module>
      zip_safe=False,
    File "/home/jenkins/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
      dist.run_commands()
    File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-PxBK14/pythonnet/setup.py", line 610, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/home/jenkins/.local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-install-PxBK14/pythonnet/setup.py", line 245, in build_extension
      self._install_packages()
    File "/tmp/pip-install-PxBK14/pythonnet/setup.py", line 424, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 127

  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-PxBK14/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-PxBK14/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-beg4Xn/install-record.txt --single-version-externally-managed --compile --user --prefix=
         cwd: /tmp/pip-install-PxBK14/pythonnet/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-PxBK14/pythonnet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-PxBK14/pythonnet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-beg4Xn/install-record.txt --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

For 2 I am getting below error:

+ pip install git+https://github.com/pythonnet/pythonnet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting git+https://github.com/pythonnet/pythonnet
  Cloning https://github.com/pythonnet/pythonnet to /tmp/pip-req-build-68J81H
  Running command git clone -q https://github.com/pythonnet/pythonnet /tmp/pip-req-build-68J81H
Building wheels for collected packages: pythonnet
  Building wheel for pythonnet (setup.py): started
  Building wheel for pythonnet (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-68J81H/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-68J81H/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5_jfQa --python-tag cp27
       cwd: /tmp/pip-req-build-68J81H/
  Complete output (43 lines):
  /home/jenkins/.local/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
    normalized_version,
  running bdist_wheel
  running build
  running build_ext
  /bin/sh: mono: command not found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-68J81H/setup.py", line 665, in <module>
      zip_safe=False,
    File "/home/jenkins/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
      dist.run_commands()
    File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-68J81H/setup.py", line 615, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/home/jenkins/.local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-req-build-68J81H/setup.py", line 249, in build_extension
      self._install_packages()
    File "/tmp/pip-req-build-68J81H/setup.py", line 429, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 127

  ERROR: Failed building wheel for pythonnet
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-68J81H/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-68J81H/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2BZMcS/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-req-build-68J81H/
    Complete output (8 lines):
    /home/jenkins/.local/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
      normalized_version,
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-68J81H/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-68J81H/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2BZMcS/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

For 3 I am getting error:
+ git clone https://github.com/pythonnet/pythonnet
Cloning into 'pythonnet'...
+ cd pythonnet
+ python setup.py bdist_wheel --xplat
/home/jenkins/.local/lib/python2.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
  normalized_version,
running bdist_wheel
running build
running build_ext
/bin/sh: dotnet: command not found
Traceback (most recent call last):
  File "setup.py", line 665, in <module>
    zip_safe=False,
  File "/home/jenkins/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 615, in run
    return bdist_wheel.bdist_wheel.run(self)
  File "/home/jenkins/.local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
    self.run_command('build')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "setup.py", line 249, in build_extension
    self._install_packages()
  File "setup.py", line 420, in _install_packages
    subprocess.check_call(cmd, shell=use_shell)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'dotnet msbuild /t:Restore pythonnet.15.sln /p:Configuration=ReleaseMono /p:Platform=x64' returned non-zero exit status 127
Build step 'Execute shell' marked build as failure
Finished: FAILURE

Any help will be highly appreciated

**Comment by Cronan** [comment]
1) I think [this](https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind) is your problem - try updating/installing or updating setuptools and wheel.
2) Same as above.
3) Status 127 is from Unix,. command not found. So, dotnet not installed or not on the path.

**Comment by abhi19935** [comment]
i have these pip-19.2.1, setuptools-41.0.1, wheel-0.33.4 and these seem to be the latest one, so looks like these are not an issue
any other suggestions

**Comment by filmor** [comment]
You apparently have neither mono nor the dotnet-core-sdk installed, either of which is required.
