### ISSUE TITLE
windows 10, python 3.5rc1, VS2015 installation issue

### ISSUE THREAD

**Issue by denfromufa** [pythonnet/pythonnet#92]
```
C:\Windows\system32>pip install pythonnet==2.1.0.dev1 --use-wheel
Collecting pythonnet==2.1.0.dev1
  Using cached pythonnet-2.1.0.dev1.tar.gz
Installing collected packages: pythonnet
  Running setup.py install for pythonnet
    Complete output from command C:\Python\Python35-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\dta\\AppData\\Local\\Temp\\pip-build-p5hlpays\\pythonnet\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\dta\AppData\Local\Temp\pip-ugwmq80q-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Installing 'NUnit 2.6.2'.
    Successfully installed 'NUnit 2.6.2'.
    Installing 'UnmanagedExports 1.2.6'.
    Successfully installed 'UnmanagedExports 1.2.6'.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dta\AppData\Local\Temp\pip-build-p5hlpays\pythonnet\setup.py", line 314, in <module>
        "install_data": PythonNET_InstallData,
      File "C:\Python\Python35-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python\Python35-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python\Python35-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python\Python35-32\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python\Python35-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Python\Python35-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python\Python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python\Python35-32\lib\distutils\command\build_ext.py", line 338, in run
        self.build_extensions()
      File "C:\Python\Python35-32\lib\distutils\command\build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "C:\Python\Python35-32\lib\distutils\command\build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Python\Python35-32\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Python\Python35-32\lib\distutils\command\build_ext.py", line 477, in _filter_build_errors
        yield
      File "C:\Python\Python35-32\lib\distutils\command\build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\dta\AppData\Local\Temp\pip-build-p5hlpays\pythonnet\setup.py", line 155, in build_extension
        manifest = self._get_manifest(dest_dir)
      File "C:\Users\dta\AppData\Local\Temp\pip-build-p5hlpays\pythonnet\setup.py", line 169, in _get_manifest
        mt = _find_msbuild_tool("mt.exe", use_windows_sdk=True)
      File "C:\Users\dta\AppData\Local\Temp\pip-build-p5hlpays\pythonnet\setup.py", line 61, in _find_msbuild_tool
        raise RuntimeError("%s could not be found" % sdk_name)
    RuntimeError: Windows SDK could not be found

    ----------------------------------------
Command "C:\Python\Python35-32\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\dta\\AppData\\Local\\Temp\\pip-build-p5hlpays\\pythonnet\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\dta\AppData\Local\Temp\pip-ugwmq80q-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\dta\AppData\Local\Temp\pip-build-p5hlpays\pythonnet
```

**Comment by tonyroberts** [comment]
This error is telling you that you don't have the Windows SDK installed.

**Comment by denfromufa** [comment]
I thought Python 3.5 is using VS2015 with C++   included, which I have
installed on that machine. Maybe 64bit again requires funky Windows SDK?

**Comment by tonyroberts** [comment]
Python 3.5 support hasn't been added. Again, PyPI tells you the supported versions.

Adding 3.5 support shouldn't be that hard. If you want to take a go at that send a PR when you're done and I can review it for you if you like.

**Comment by gnychis** [comment]
@tonyroberts has anyone started on Python 3.5 support yet that you know of?

**Comment by denfromufa** [comment]
https://github.com/pythonnet/pythonnet/issues/103
