### ISSUE TITLE
Python 3.7 installation fail

### ISSUE THREAD

**Issue by prokotg** [pythonnet/pythonnet#937]
Hey there, I was recently trying to put pythonnet on docker image to mimic building failures on my other project CI system. I just can't think about anything else that could help right now. I was trying to get different combinations of python and pythonnet.

Here is the Docker File content:

```
FROM python:3.7

RUN python -V
RUN apt-get update
RUN apt install -y mono-devel clang python3-dev libglib2.0-dev
RUN pip3 install --upgrade setuptools
RUN pip3 install pycparser ply
RUN pip3 install git+https://github.com/pythonnet/pythonnet
```

I am getting the following errors
```

  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hick4r43/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hick4r43/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ndiqui2g --python-tag cp37
       cwd: /tmp/pip-req-build-hick4r43/
  Complete output (67 lines):
  /usr/local/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
    normalized_version,
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 5.1.0.
  Update successful.
  MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
  
  >>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
  
  MSBUILD: error MSBUILD0004: Too many project files specified
  
  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
  Index was outside the bounds of the array.
  MSBuild auto-detection: using msbuild version '' from '/usr/bin'.
  Error parsing solution file at /tmp/pip-req-build-hick4r43/pythonnet.sln: Invalid Image
  Traceback (most recent call last):
    File "/tmp/pip-req-build-hick4r43/setup.py", line 437, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -MSBuildVersion 14 -o packages' returned non-zero exit status 1.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-hick4r43/setup.py", line 665, in <module>
      zip_safe=False,
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-hick4r43/setup.py", line 615, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-req-build-hick4r43/setup.py", line 249, in build_extension
      self._install_packages()
    File "/tmp/pip-req-build-hick4r43/setup.py", line 442, in _install_packages
      subprocess.check_call(cmd, shell=use_shell)
    File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe restore pythonnet.sln  -o packages' returned non-zero exit status 1.
  ----------------------------------------

  ERROR: Failed building wheel for pythonnet

  Running setup.py clean for pythonnet

Failed to build pythonnet

Installing collected packages: pythonnet

  Running setup.py install for pythonnet: started

    Running setup.py install for pythonnet: finished with status 'error'

    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hick4r43/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hick4r43/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0w9kyb2s/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-req-build-hick4r43/
    Complete output (8 lines):
    /usr/local/lib/python3.7/site-packages/setuptools/dist.py:472: UserWarning: Normalizing '2.4.1-dev' to '2.4.1.dev0'
      normalized_version,
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --single-version-externally-managed not recognized
    ----------------------------------------

ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-hick4r43/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-hick4r43/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0w9kyb2s/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Error: ResponseItem.ErrorDetail[code=1,message=The command '/bin/sh -c pip3 install git+https://github.com/pythonnet/pythonnet' returned a non-zero code: 1]
Failed to deploy 'nda Dockerfile: Dockerfile': The command '/bin/sh -c pip3 install git+https://github.com/pythonnet/pythonnet' returned a non-zero code: 1

```

Any ideas? What am I missing here?

Thank you :)

**Comment by Cronan** [comment]
This looks like a [similar issue](https://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind):

`option --single-version-externally-managed not recognized`

**Comment by prokotg** [comment]
@Cronan it is not. I have seen it before and I upgraded setupwheels. It actually seems the error was produced by few missing dependencies and not-right mono version and I _kinda_ fixed that. What I did I tried to reproduce the environment from DockerFile from here https://github.com/jonemo/pythonnet-docker and it worked I think it is crucial to connect right python, mono and pythonnet versions but I can't figure it out with python 3.7. How can I know which version of mono is supposed to be installed ?

**Comment by Cronan** [comment]
AFAIK it's 5.2, 6.0.0 caused us some recent problems.

**Comment by prokotg** [comment]
I managed to install it with 5.18.0.240. I attach DockerFile to mimic the environment for anyone interested.

```
FROM ubuntu:18.04

RUN apt-get update -y && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa

RUN  apt install -y python3.7
RUN  apt-get install -y libglib2.0-dev

RUN ln -sf /usr/bin/python3.7 /usr/bin/python3

RUN apt-get install -y curl
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py



RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/ubuntu bionic/snapshots/5.18.0.240/.  main">/etc/apt/sources.list.d/mono-official.list
RUN apt-get update
RUN apt-get install -y clang
RUN apt-get install -y mono-devel
RUN apt install -y  python3.7-dev libglib2.0-dev


RUN pip3 install pycparser \
  && pip3 install pythonnet
```

Cheers

**Comment by Cronan** [comment]
Thank you @prokotg that's good to know.
