### ISSUE TITLE
Cythonized python.net code cannot find system assemblies

### ISSUE THREAD

**Issue by crayxt** [pythonnet/pythonnet#941]
Dup of my SO question https://stackoverflow.com/questions/57493309/cythonized-python-net-code-cannot-find-system-assemblies

When I compile the python code which uses python.net to access .Net assemblies, it can't find those assemblies. Without compilation it works ok.

For demo code, I used https://github.com/pythonnet/pythonnet/blob/master/demo/helloform.py

My setup.py file

```
from distutils.core import setup
from distutils.extension import Extension
from Cython.Build import cythonize

ext_modules = [
    Extension(
        'helloform',
        sources = ['helloform.py'],
        language = 'c++'
      )
]

setup(
  name = 'helloform',
  ext_modules = cythonize(ext_modules),
)
```
Then I build it with python setup.py build_ext --inplace.

I wanted to load compiled module from Python prompt with import helloform but it failed with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "helloform.py", line 8, in init helloform
ModuleNotFoundError: No module named 'System'
```

**Comment by filmor** [comment]
I'd guess that cython handles `__import__` by itself in some way that is incompatible with our hook. Not much we can do about this until #727 is implemented.

**Comment by donno** [comment]
Could the functionality that drives the __import__ override be provided via a named function that can be called? For example, `System = clr.ImportModule('System')`

Or possibly using the return value of `clr.AddReference(...)`, i.e that turns the `System.RuntimeType` into the `ModuleObject` (and also register it under clr, i.e clr.System).

**Comment by filmor** [comment]
It could and it should, good idea.

**Comment by crayxt** [comment]
Dear all, is there any news on this subject? thanks,

**Comment by Anderu123** [comment]
> Could the functionality that drives the **import** override be provided via a named function that can be called? For example, `System = clr.ImportModule('System')`
> 
> Or possibly using the return value of `clr.AddReference(...)`, i.e that turns the `System.RuntimeType` into the `ModuleObject` (and also register it under clr, i.e clr.System).



> Could the functionality that drives the **import** override be provided via a named function that can be called? For example, `System = clr.ImportModule('System')`
> 
> Or possibly using the return value of `clr.AddReference(...)`, i.e that turns the `System.RuntimeType` into the `ModuleObject` (and also register it under clr, i.e clr.System).

Hi sir, could you kindly show me examples of how to retrieve/use the method/function out of ModuleObject, cause I kept attribute error out of it, appreciate it alot.

**Comment by josephernest** [comment]
> Could the functionality that drives the import override be provided via a named function that can be called? For example, `System = clr.ImportModule('System')`

Good idea. Is this feature available? Do you know where in the source code of `clr` is done this `import` override?
