### ISSUE TITLE
Support for Jetson Nano (aarch64 architecture)

### ISSUE THREAD

**Issue by MPMongrel** [pythonnet/pythonnet#982]
### Environment

-   Pythonnet version: 2.4.0
-   Python version: 3.6 (3.7, any)
-   Operating System: Linux aarch64

### Details

- Python.Runtime crashes when used on a Jetson Nano. 
- Request: Enable support or provide hints for a workaround.

Exception:
```
Unhandled exception: System.NotImplementedException: No support for aarch64
   at Python.Runtime.TypeManager.NativeCode.get_Active()
   at Python.Runtime.TypeManager.InitializeNativeCodePage()
   at Python.Runtime.TypeManager.InitializeSlots(IntPtr type, Type impl)
   at Python.Runtime.TypeManager.CreateMetaType(Type impl)
   at Python.Runtime.MetaType.Initialize()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
```

Thanks!

**Comment by filmor** [comment]
Add the missing architecture here https://github.com/pythonnet/pythonnet/blob/master/src/runtime/runtime.cs#L146 and in the respective enum and you should be good to go. PR is welcome.

**Comment by Cronan** [comment]
@MPMongrel please let us know if this resolved your issue

**Comment by MPMongrel** [comment]
@Cronan & @filmor  Apologies for not coming back to this earlier. I did make very similar changes locally already, but forgot about creating a PR. I now removed my own changes and applied the ones from #986 and verified that they still work.
Thank you!
